/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) sim_car_impl_dae_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_low CASADI_PREFIX(low)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

static const casadi_int casadi_s0[1] = {0};
static const casadi_int casadi_s1[1] = {1};
static const casadi_int casadi_s2[1] = {3};
static const casadi_int casadi_s3[2] = {0, 9};
static const casadi_int casadi_s4[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s5[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s6[3] = {0, 0, 0};

static const casadi_real casadi_c0[5] = {1.0000000000000019e-06, 9.9999999999999995e-07, 1.0000000000000002e-06, 1.0000000000000002e-06, 1.0000000000000019e-06};
static const casadi_real casadi_c1[9] = {0., 0., 0., 0., 2., 4., 4., 4., 4.};

/* kapparef_s:(x)->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c1,casadi_s3,casadi_s2,casadi_s1,casadi_c0,1,(&w0),casadi_s0, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* sim_car_impl_dae_fun:(i0[7],i1[7],i2[2],i3[],i4[])->(o0[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+5, *cs;
  casadi_real *w0=w+12, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, *w18=w+36;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 7, w0);
  /* #1: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = 3 */
  w2 = 3.;
  /* #3: @2 = (@1-@2) */
  w2  = (w1-w2);
  /* #4: @3 = 2 */
  w3 = 2.;
  /* #5: @2 = (@2/@3) */
  w2 /= w3;
  /* #6: @3 = 0 */
  w3 = 0.;
  /* #7: @2 = fmax(@2,@3) */
  w2  = casadi_fmax(w2,w3);
  /* #8: @3 = 1 */
  w3 = 1.;
  /* #9: @2 = fmin(@2,@3) */
  w2  = casadi_fmin(w2,w3);
  /* #10: @3 = input[0][2] */
  w3 = arg[0] ? arg[0][2] : 0;
  /* #11: @4 = cos(@3) */
  w4 = cos( w3 );
  /* #12: @4 = (@1*@4) */
  w4  = (w1*w4);
  /* #13: @5 = input[0][4] */
  w5 = arg[0] ? arg[0][4] : 0;
  /* #14: @6 = sin(@3) */
  w6 = sin( w3 );
  /* #15: @6 = (@5*@6) */
  w6  = (w5*w6);
  /* #16: @4 = (@4-@6) */
  w4 -= w6;
  /* #17: @6 = 1 */
  w6 = 1.;
  /* #18: @7 = input[0][1] */
  w7 = arg[0] ? arg[0][1] : 0;
  /* #19: @8 = input[0][0] */
  w8 = arg[0] ? arg[0][0] : 0;
  /* #20: @9 = kapparef_s(@8) */
  arg1[0]=(&w8);
  res1[0]=(&w9);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #21: @9 = (@7*@9) */
  w9  = (w7*w9);
  /* #22: @6 = (@6-@9) */
  w6 -= w9;
  /* #23: @4 = (@4/@6) */
  w4 /= w6;
  /* #24: @4 = (@2*@4) */
  w4  = (w2*w4);
  /* #25: @6 = 1 */
  w6 = 1.;
  /* #26: @6 = (@6-@2) */
  w6 -= w2;
  /* #27: @2 = cos(@3) */
  w2 = cos( w3 );
  /* #28: @2 = (@1*@2) */
  w2  = (w1*w2);
  /* #29: @9 = sin(@3) */
  w9 = sin( w3 );
  /* #30: @9 = (@5*@9) */
  w9  = (w5*w9);
  /* #31: @2 = (@2-@9) */
  w2 -= w9;
  /* #32: @9 = 1 */
  w9 = 1.;
  /* #33: @10 = kapparef_s(@8) */
  arg1[0]=(&w8);
  res1[0]=(&w10);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #34: @10 = (@7*@10) */
  w10  = (w7*w10);
  /* #35: @9 = (@9-@10) */
  w9 -= w10;
  /* #36: @2 = (@2/@9) */
  w2 /= w9;
  /* #37: @6 = (@6*@2) */
  w6 *= w2;
  /* #38: @4 = (@4+@6) */
  w4 += w6;
  /* #39: @6 = 3 */
  w6 = 3.;
  /* #40: @6 = (@1-@6) */
  w6  = (w1-w6);
  /* #41: @2 = 2 */
  w2 = 2.;
  /* #42: @6 = (@6/@2) */
  w6 /= w2;
  /* #43: @2 = 0 */
  w2 = 0.;
  /* #44: @6 = fmax(@6,@2) */
  w6  = casadi_fmax(w6,w2);
  /* #45: @2 = 1 */
  w2 = 1.;
  /* #46: @6 = fmin(@6,@2) */
  w6  = casadi_fmin(w6,w2);
  /* #47: @2 = sin(@3) */
  w2 = sin( w3 );
  /* #48: @2 = (@1*@2) */
  w2  = (w1*w2);
  /* #49: @9 = cos(@3) */
  w9 = cos( w3 );
  /* #50: @9 = (@5*@9) */
  w9  = (w5*w9);
  /* #51: @2 = (@2+@9) */
  w2 += w9;
  /* #52: @2 = (@6*@2) */
  w2  = (w6*w2);
  /* #53: @9 = 1 */
  w9 = 1.;
  /* #54: @9 = (@9-@6) */
  w9 -= w6;
  /* #55: @6 = sin(@3) */
  w6 = sin( w3 );
  /* #56: @6 = (@1*@6) */
  w6  = (w1*w6);
  /* #57: @10 = cos(@3) */
  w10 = cos( w3 );
  /* #58: @10 = (@5*@10) */
  w10  = (w5*w10);
  /* #59: @6 = (@6+@10) */
  w6 += w10;
  /* #60: @9 = (@9*@6) */
  w9 *= w6;
  /* #61: @2 = (@2+@9) */
  w2 += w9;
  /* #62: @9 = 3 */
  w9 = 3.;
  /* #63: @9 = (@1-@9) */
  w9  = (w1-w9);
  /* #64: @6 = 2 */
  w6 = 2.;
  /* #65: @9 = (@9/@6) */
  w9 /= w6;
  /* #66: @6 = 0 */
  w6 = 0.;
  /* #67: @9 = fmax(@9,@6) */
  w9  = casadi_fmax(w9,w6);
  /* #68: @6 = 1 */
  w6 = 1.;
  /* #69: @9 = fmin(@9,@6) */
  w9  = casadi_fmin(w9,w6);
  /* #70: @6 = input[0][5] */
  w6 = arg[0] ? arg[0][5] : 0;
  /* #71: @10 = kapparef_s(@8) */
  arg1[0]=(&w8);
  res1[0]=(&w10);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #72: @10 = (@7*@10) */
  w10  = (w7*w10);
  /* #73: @11 = cos(@3) */
  w11 = cos( w3 );
  /* #74: @11 = (@1*@11) */
  w11  = (w1*w11);
  /* #75: @12 = sin(@3) */
  w12 = sin( w3 );
  /* #76: @12 = (@5*@12) */
  w12  = (w5*w12);
  /* #77: @11 = (@11-@12) */
  w11 -= w12;
  /* #78: @10 = (@10*@11) */
  w10 *= w11;
  /* #79: @11 = 1 */
  w11 = 1.;
  /* #80: @12 = kapparef_s(@8) */
  arg1[0]=(&w8);
  res1[0]=(&w12);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #81: @12 = (@7*@12) */
  w12  = (w7*w12);
  /* #82: @11 = (@11-@12) */
  w11 -= w12;
  /* #83: @10 = (@10/@11) */
  w10 /= w11;
  /* #84: @10 = (@6-@10) */
  w10  = (w6-w10);
  /* #85: @10 = (@9*@10) */
  w10  = (w9*w10);
  /* #86: @11 = 1 */
  w11 = 1.;
  /* #87: @11 = (@11-@9) */
  w11 -= w9;
  /* #88: @9 = kapparef_s(@8) */
  arg1[0]=(&w8);
  res1[0]=(&w9);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #89: @9 = (@7*@9) */
  w9  = (w7*w9);
  /* #90: @12 = cos(@3) */
  w12 = cos( w3 );
  /* #91: @12 = (@1*@12) */
  w12  = (w1*w12);
  /* #92: @3 = sin(@3) */
  w3 = sin( w3 );
  /* #93: @3 = (@5*@3) */
  w3  = (w5*w3);
  /* #94: @12 = (@12-@3) */
  w12 -= w3;
  /* #95: @9 = (@9*@12) */
  w9 *= w12;
  /* #96: @12 = 1 */
  w12 = 1.;
  /* #97: @3 = kapparef_s(@8) */
  arg1[0]=(&w8);
  res1[0]=(&w3);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #98: @7 = (@7*@3) */
  w7 *= w3;
  /* #99: @12 = (@12-@7) */
  w12 -= w7;
  /* #100: @9 = (@9/@12) */
  w9 /= w12;
  /* #101: @9 = (@6-@9) */
  w9  = (w6-w9);
  /* #102: @11 = (@11*@9) */
  w11 *= w9;
  /* #103: @10 = (@10+@11) */
  w10 += w11;
  /* #104: @11 = 3 */
  w11 = 3.;
  /* #105: @11 = (@1-@11) */
  w11  = (w1-w11);
  /* #106: @9 = 2 */
  w9 = 2.;
  /* #107: @11 = (@11/@9) */
  w11 /= w9;
  /* #108: @9 = 0 */
  w9 = 0.;
  /* #109: @11 = fmax(@11,@9) */
  w11  = casadi_fmax(w11,w9);
  /* #110: @9 = 1 */
  w9 = 1.;
  /* #111: @11 = fmin(@11,@9) */
  w11  = casadi_fmin(w11,w9);
  /* #112: @9 = input[2][0] */
  w9 = arg[2] ? arg[2][0] : 0;
  /* #113: @12 = 0.0005 */
  w12 = 5.0000000000000001e-04;
  /* #114: @7 = 92731.3 */
  w7 = 9.2731265615302604e+04;
  /* #115: @3 = input[0][6] */
  w3 = arg[0] ? arg[0][6] : 0;
  /* #116: @8 = 1.4 */
  w8 = 1.3999999999999999e+00;
  /* #117: @8 = (@8*@6) */
  w8 *= w6;
  /* #118: @8 = (@5+@8) */
  w8  = (w5+w8);
  /* #119: @8 = (@8/@1) */
  w8 /= w1;
  /* #120: @8 = (@3-@8) */
  w8  = (w3-w8);
  /* #121: @7 = (@7*@8) */
  w7 *= w8;
  /* #122: @12 = (@12*@7) */
  w12 *= w7;
  /* #123: @7 = sin(@3) */
  w7 = sin( w3 );
  /* #124: @12 = (@12*@7) */
  w12 *= w7;
  /* #125: @12 = (@9-@12) */
  w12  = (w9-w12);
  /* #126: @7 = (@5*@6) */
  w7  = (w5*w6);
  /* #127: @12 = (@12+@7) */
  w12 += w7;
  /* #128: @12 = (@11*@12) */
  w12  = (w11*w12);
  /* #129: @7 = 1 */
  w7 = 1.;
  /* #130: @7 = (@7-@11) */
  w7 -= w11;
  /* #131: @7 = (@7*@9) */
  w7 *= w9;
  /* #132: @12 = (@12+@7) */
  w12 += w7;
  /* #133: @7 = 3 */
  w7 = 3.;
  /* #134: @7 = (@1-@7) */
  w7  = (w1-w7);
  /* #135: @11 = 2 */
  w11 = 2.;
  /* #136: @7 = (@7/@11) */
  w7 /= w11;
  /* #137: @11 = 0 */
  w11 = 0.;
  /* #138: @7 = fmax(@7,@11) */
  w7  = casadi_fmax(w7,w11);
  /* #139: @11 = 1 */
  w11 = 1.;
  /* #140: @7 = fmin(@7,@11) */
  w7  = casadi_fmin(w7,w11);
  /* #141: @11 = 0.0005 */
  w11 = 5.0000000000000001e-04;
  /* #142: @8 = 92731.3 */
  w8 = 9.2731265615302604e+04;
  /* #143: @13 = 1.4 */
  w13 = 1.3999999999999999e+00;
  /* #144: @13 = (@13*@6) */
  w13 *= w6;
  /* #145: @13 = (@13-@5) */
  w13 -= w5;
  /* #146: @8 = (@8*@13) */
  w8 *= w13;
  /* #147: @8 = (@8/@1) */
  w8 /= w1;
  /* #148: @13 = 92731.3 */
  w13 = 9.2731265615302604e+04;
  /* #149: @14 = 1.4 */
  w14 = 1.3999999999999999e+00;
  /* #150: @14 = (@14*@6) */
  w14 *= w6;
  /* #151: @14 = (@5+@14) */
  w14  = (w5+w14);
  /* #152: @14 = (@14/@1) */
  w14 /= w1;
  /* #153: @14 = (@3-@14) */
  w14  = (w3-w14);
  /* #154: @13 = (@13*@14) */
  w13 *= w14;
  /* #155: @14 = cos(@3) */
  w14 = cos( w3 );
  /* #156: @13 = (@13*@14) */
  w13 *= w14;
  /* #157: @8 = (@8+@13) */
  w8 += w13;
  /* #158: @11 = (@11*@8) */
  w11 *= w8;
  /* #159: @8 = (@1*@6) */
  w8  = (w1*w6);
  /* #160: @11 = (@11-@8) */
  w11 -= w8;
  /* #161: @11 = (@7*@11) */
  w11  = (w7*w11);
  /* #162: @8 = 1 */
  w8 = 1.;
  /* #163: @8 = (@8-@7) */
  w8 -= w7;
  /* #164: @7 = 1.4 */
  w7 = 1.3999999999999999e+00;
  /* #165: @13 = input[2][1] */
  w13 = arg[2] ? arg[2][1] : 0;
  /* #166: @14 = (@13*@1) */
  w14  = (w13*w1);
  /* #167: @15 = (@3*@9) */
  w15  = (w3*w9);
  /* #168: @14 = (@14+@15) */
  w14 += w15;
  /* #169: @7 = (@7*@14) */
  w7 *= w14;
  /* #170: @14 = 2.8 */
  w14 = 2.7999999999999998e+00;
  /* #171: @7 = (@7/@14) */
  w7 /= w14;
  /* #172: @8 = (@8*@7) */
  w8 *= w7;
  /* #173: @11 = (@11+@8) */
  w11 += w8;
  /* #174: @8 = 3 */
  w8 = 3.;
  /* #175: @8 = (@1-@8) */
  w8  = (w1-w8);
  /* #176: @7 = 2 */
  w7 = 2.;
  /* #177: @8 = (@8/@7) */
  w8 /= w7;
  /* #178: @7 = 0 */
  w7 = 0.;
  /* #179: @8 = fmax(@8,@7) */
  w8  = casadi_fmax(w8,w7);
  /* #180: @7 = 1 */
  w7 = 1.;
  /* #181: @8 = fmin(@8,@7) */
  w8  = casadi_fmin(w8,w7);
  /* #182: @7 = 0.000255102 */
  w7 = 2.5510204081632655e-04;
  /* #183: @14 = 1.4 */
  w14 = 1.3999999999999999e+00;
  /* #184: @15 = 92731.3 */
  w15 = 9.2731265615302604e+04;
  /* #185: @16 = 1.4 */
  w16 = 1.3999999999999999e+00;
  /* #186: @16 = (@16*@6) */
  w16 *= w6;
  /* #187: @16 = (@5+@16) */
  w16  = (w5+w16);
  /* #188: @16 = (@16/@1) */
  w16 /= w1;
  /* #189: @16 = (@3-@16) */
  w16  = (w3-w16);
  /* #190: @15 = (@15*@16) */
  w15 *= w16;
  /* #191: @14 = (@14*@15) */
  w14 *= w15;
  /* #192: @15 = cos(@3) */
  w15 = cos( w3 );
  /* #193: @14 = (@14*@15) */
  w14 *= w15;
  /* #194: @15 = 1.4 */
  w15 = 1.3999999999999999e+00;
  /* #195: @16 = 92731.3 */
  w16 = 9.2731265615302604e+04;
  /* #196: @17 = 1.4 */
  w17 = 1.3999999999999999e+00;
  /* #197: @17 = (@17*@6) */
  w17 *= w6;
  /* #198: @17 = (@17-@5) */
  w17 -= w5;
  /* #199: @16 = (@16*@17) */
  w16 *= w17;
  /* #200: @16 = (@16/@1) */
  w16 /= w1;
  /* #201: @15 = (@15*@16) */
  w15 *= w16;
  /* #202: @14 = (@14-@15) */
  w14 -= w15;
  /* #203: @7 = (@7*@14) */
  w7 *= w14;
  /* #204: @7 = (@8*@7) */
  w7  = (w8*w7);
  /* #205: @14 = 1 */
  w14 = 1.;
  /* #206: @14 = (@14-@8) */
  w14 -= w8;
  /* #207: @1 = (@13*@1) */
  w1  = (w13*w1);
  /* #208: @3 = (@3*@9) */
  w3 *= w9;
  /* #209: @1 = (@1+@3) */
  w1 += w3;
  /* #210: @3 = 2.8 */
  w3 = 2.7999999999999998e+00;
  /* #211: @1 = (@1/@3) */
  w1 /= w3;
  /* #212: @14 = (@14*@1) */
  w14 *= w1;
  /* #213: @7 = (@7+@14) */
  w7 += w14;
  /* #214: @18 = vertcat(@4, @2, @10, @12, @11, @7, @13) */
  rr=w18;
  *rr++ = w4;
  *rr++ = w2;
  *rr++ = w10;
  *rr++ = w12;
  *rr++ = w11;
  *rr++ = w7;
  *rr++ = w13;
  /* #215: @0 = (@0-@18) */
  for (i=0, rr=w0, cs=w18; i<7; ++i) (*rr++) -= (*cs++);
  /* #216: output[0][0] = @0 */
  casadi_copy(w0, 7, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int sim_car_impl_dae_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int sim_car_impl_dae_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int sim_car_impl_dae_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void sim_car_impl_dae_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int sim_car_impl_dae_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void sim_car_impl_dae_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void sim_car_impl_dae_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void sim_car_impl_dae_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int sim_car_impl_dae_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int sim_car_impl_dae_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real sim_car_impl_dae_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* sim_car_impl_dae_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* sim_car_impl_dae_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* sim_car_impl_dae_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* sim_car_impl_dae_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int sim_car_impl_dae_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 43;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
