/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) sim_car_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_low CASADI_PREFIX(low)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[1] = {0};
static const casadi_int casadi_s1[1] = {1};
static const casadi_int casadi_s2[1] = {3};
static const casadi_int casadi_s3[2] = {0, 9};
static const casadi_int casadi_s4[1] = {2};
static const casadi_int casadi_s5[2] = {0, 7};
static const casadi_int casadi_s6[5] = {0, 8, 17, 21, 25};
static const casadi_int casadi_s7[3] = {2, 5, 10};
static const casadi_int casadi_s8[6] = {3, 6, 11, 14, 18, 22};
static const casadi_int casadi_s9[6] = {4, 7, 12, 15, 19, 23};
static const casadi_int casadi_s10[4] = {13, 16, 20, 24};
static const casadi_int casadi_s11[36] = {7, 7, 0, 2, 4, 7, 13, 19, 23, 26, 0, 2, 0, 2, 0, 1, 2, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 2, 3, 4, 5, 3, 4, 5};
static const casadi_int casadi_s12[36] = {7, 7, 0, 5, 8, 14, 18, 22, 26, 26, 0, 1, 2, 3, 4, 2, 3, 4, 0, 1, 2, 3, 4, 5, 3, 4, 5, 6, 3, 4, 5, 6, 3, 4, 5, 6};
static const casadi_int casadi_s13[17] = {7, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s14[3] = {0, 1, 3};
static const casadi_int casadi_s15[3] = {2, 4, 5};
static const casadi_int casadi_s16[11] = {7, 2, 0, 3, 6, 3, 4, 5, 4, 5, 6};
static const casadi_int casadi_s17[16] = {2, 7, 0, 0, 0, 0, 1, 3, 5, 6, 0, 0, 1, 0, 1, 1};
static const casadi_int casadi_s18[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s19[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s20[3] = {0, 0, 0};
static const casadi_int casadi_s21[3] = {7, 0, 0};

static const casadi_real casadi_c0[5] = {1.0000000000000019e-06, 9.9999999999999995e-07, 1.0000000000000002e-06, 1.0000000000000002e-06, 1.0000000000000019e-06};
static const casadi_real casadi_c1[9] = {0., 0., 0., 0., 2., 4., 4., 4., 4.};
static const casadi_real casadi_c2[4] = {-2.7528570785764761e-21, 1.0587911840678754e-22, 0., 2.5410988417629010e-21};
static const casadi_real casadi_c3[7] = {0., 0., 0., 2., 4., 4., 4.};

/* kapparef_s:(x)->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c1,casadi_s3,casadi_s2,casadi_s1,casadi_c0,1,(&w0),casadi_s0, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_kapparef_s:(x,out_f[1x1,0nz],fwd_x)->(fwd_f) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c3,casadi_s5,casadi_s4,casadi_s1,casadi_c2,1,(&w0),casadi_s0, iw, w);
  /* #2: @0 = input[2][0] */
  w0 = arg[2] ? arg[2][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* sim_car_impl_dae_jac_x_xdot_u_z:(i0[7],i1[7],i2[2],i3[],i4[])->(o0[7x7,26nz],o1[7x7,7nz],o2[7x2,6nz],o3[7x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+4, *rr, *ss;
  const casadi_int *cii;
  const casadi_real **arg1=arg+5, *cs;
  casadi_real *w0=w+12, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, *w18=w+54, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35, w36, w37, w38, w40, w41, w42, w43, w44, w45, w46, w47, w48, w49, w50, w51, w52, w53, w54, w55, w56, w57, w58, w59, w60, w61, w62, w63, w64, w65, w66, w67, w68, w69, w70, w71, w72, w73, w74, w75, w76, w77, w78, w79, w80, w81, w82, w83, w84, w85, w86, w87, w88, w89, w90, w91, w92, w93, w94, w95, w96, *w97=w+133, *w98=w+138, *w102=w+143, *w103=w+145, *w104=w+148, *w105=w+151, *w106=w+157, *w107=w+163, *w108=w+167, *w109=w+171, *w110=w+197, *w111=w+204;
  /* #0: @0 = zeros(7x7,26nz) */
  casadi_clear(w0, 26);
  /* #1: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = 3 */
  w2 = 3.;
  /* #3: @2 = (@1-@2) */
  w2  = (w1-w2);
  /* #4: @3 = 2 */
  w3 = 2.;
  /* #5: @2 = (@2/@3) */
  w2 /= w3;
  /* #6: @3 = 0 */
  w3 = 0.;
  /* #7: @4 = fmax(@2,@3) */
  w4  = casadi_fmax(w2,w3);
  /* #8: @5 = 1 */
  w5 = 1.;
  /* #9: @6 = fmin(@4,@5) */
  w6  = casadi_fmin(w4,w5);
  /* #10: @7 = input[0][2] */
  w7 = arg[0] ? arg[0][2] : 0;
  /* #11: @8 = cos(@7) */
  w8 = cos( w7 );
  /* #12: @9 = (@1*@8) */
  w9  = (w1*w8);
  /* #13: @10 = input[0][4] */
  w10 = arg[0] ? arg[0][4] : 0;
  /* #14: @11 = sin(@7) */
  w11 = sin( w7 );
  /* #15: @12 = (@10*@11) */
  w12  = (w10*w11);
  /* #16: @9 = (@9-@12) */
  w9 -= w12;
  /* #17: @12 = 1 */
  w12 = 1.;
  /* #18: @13 = input[0][1] */
  w13 = arg[0] ? arg[0][1] : 0;
  /* #19: @14 = input[0][0] */
  w14 = arg[0] ? arg[0][0] : 0;
  /* #20: @15 = kapparef_s(@14) */
  arg1[0]=(&w14);
  res1[0]=(&w15);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #21: @16 = (@13*@15) */
  w16  = (w13*w15);
  /* #22: @12 = (@12-@16) */
  w12 -= w16;
  /* #23: @9 = (@9/@12) */
  w9 /= w12;
  /* #24: @16 = (@9/@12) */
  w16  = (w9/w12);
  /* #25: @17 = 00 */
  /* #26: @18 = ones(7x1,2nz) */
  casadi_fill(w18, 2, 1.);
  /* #27: {@19, NULL, NULL, NULL, NULL, NULL, @20} = vertsplit(@18) */
  w19 = w18[0];
  w20 = w18[1];
  /* #28: @21 = fwd1_kapparef_s(@14, @17, @19) */
  arg1[0]=(&w14);
  arg1[1]=0;
  arg1[2]=(&w19);
  res1[0]=(&w21);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #29: @21 = (@13*@21) */
  w21  = (w13*w21);
  /* #30: @21 = (@16*@21) */
  w21  = (w16*w21);
  /* #31: @21 = (@6*@21) */
  w21  = (w6*w21);
  /* #32: @22 = 1 */
  w22 = 1.;
  /* #33: @22 = (@22-@6) */
  w22 -= w6;
  /* #34: @23 = cos(@7) */
  w23 = cos( w7 );
  /* #35: @24 = (@1*@23) */
  w24  = (w1*w23);
  /* #36: @25 = sin(@7) */
  w25 = sin( w7 );
  /* #37: @26 = (@10*@25) */
  w26  = (w10*w25);
  /* #38: @24 = (@24-@26) */
  w24 -= w26;
  /* #39: @26 = 1 */
  w26 = 1.;
  /* #40: @27 = kapparef_s(@14) */
  arg1[0]=(&w14);
  res1[0]=(&w27);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #41: @28 = (@13*@27) */
  w28  = (w13*w27);
  /* #42: @26 = (@26-@28) */
  w26 -= w28;
  /* #43: @24 = (@24/@26) */
  w24 /= w26;
  /* #44: @28 = (@24/@26) */
  w28  = (w24/w26);
  /* #45: @17 = 00 */
  /* #46: @29 = fwd1_kapparef_s(@14, @17, @19) */
  arg1[0]=(&w14);
  arg1[1]=0;
  arg1[2]=(&w19);
  res1[0]=(&w29);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #47: @29 = (@13*@29) */
  w29  = (w13*w29);
  /* #48: @29 = (@28*@29) */
  w29  = (w28*w29);
  /* #49: @29 = (@22*@29) */
  w29  = (w22*w29);
  /* #50: @21 = (@21+@29) */
  w21 += w29;
  /* #51: @17 = 00 */
  /* #52: @29 = 1 */
  w29 = 1.;
  /* #53: @30 = 3 */
  w30 = 3.;
  /* #54: @30 = (@1-@30) */
  w30  = (w1-w30);
  /* #55: @31 = 2 */
  w31 = 2.;
  /* #56: @30 = (@30/@31) */
  w30 /= w31;
  /* #57: @31 = 0 */
  w31 = 0.;
  /* #58: @32 = fmax(@30,@31) */
  w32  = casadi_fmax(w30,w31);
  /* #59: @33 = 1 */
  w33 = 1.;
  /* #60: @34 = fmin(@32,@33) */
  w34  = casadi_fmin(w32,w33);
  /* #61: @29 = (@29-@34) */
  w29 -= w34;
  /* #62: @35 = cos(@7) */
  w35 = cos( w7 );
  /* #63: @36 = (@1*@35) */
  w36  = (w1*w35);
  /* #64: @37 = sin(@7) */
  w37 = sin( w7 );
  /* #65: @38 = (@10*@37) */
  w38  = (w10*w37);
  /* #66: @36 = (@36-@38) */
  w36 -= w38;
  /* #67: @39 = 00 */
  /* #68: @38 = fwd1_kapparef_s(@14, @39, @19) */
  arg1[0]=(&w14);
  arg1[1]=0;
  arg1[2]=(&w19);
  res1[0]=(&w38);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #69: @38 = (@13*@38) */
  w38  = (w13*w38);
  /* #70: @38 = (@36*@38) */
  w38  = (w36*w38);
  /* #71: @40 = 1 */
  w40 = 1.;
  /* #72: @41 = kapparef_s(@14) */
  arg1[0]=(&w14);
  res1[0]=(&w41);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #73: @42 = (@13*@41) */
  w42  = (w13*w41);
  /* #74: @40 = (@40-@42) */
  w40 -= w42;
  /* #75: @38 = (@38/@40) */
  w38 /= w40;
  /* #76: @42 = kapparef_s(@14) */
  arg1[0]=(&w14);
  res1[0]=(&w42);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #77: @43 = (@13*@42) */
  w43  = (w13*w42);
  /* #78: @44 = (@43*@36) */
  w44  = (w43*w36);
  /* #79: @44 = (@44/@40) */
  w44 /= w40;
  /* #80: @45 = (@44/@40) */
  w45  = (w44/w40);
  /* #81: @39 = 00 */
  /* #82: @46 = fwd1_kapparef_s(@14, @39, @19) */
  arg1[0]=(&w14);
  arg1[1]=0;
  arg1[2]=(&w19);
  res1[0]=(&w46);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #83: @46 = (@13*@46) */
  w46  = (w13*w46);
  /* #84: @46 = (@45*@46) */
  w46  = (w45*w46);
  /* #85: @38 = (@38+@46) */
  w38 += w46;
  /* #86: @38 = (@29*@38) */
  w38  = (w29*w38);
  /* #87: @38 = (-@38) */
  w38 = (- w38 );
  /* #88: @46 = cos(@7) */
  w46 = cos( w7 );
  /* #89: @47 = (@1*@46) */
  w47  = (w1*w46);
  /* #90: @48 = sin(@7) */
  w48 = sin( w7 );
  /* #91: @49 = (@10*@48) */
  w49  = (w10*w48);
  /* #92: @47 = (@47-@49) */
  w47 -= w49;
  /* #93: @39 = 00 */
  /* #94: @49 = fwd1_kapparef_s(@14, @39, @19) */
  arg1[0]=(&w14);
  arg1[1]=0;
  arg1[2]=(&w19);
  res1[0]=(&w49);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #95: @49 = (@13*@49) */
  w49  = (w13*w49);
  /* #96: @49 = (@47*@49) */
  w49  = (w47*w49);
  /* #97: @50 = 1 */
  w50 = 1.;
  /* #98: @51 = kapparef_s(@14) */
  arg1[0]=(&w14);
  res1[0]=(&w51);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #99: @52 = (@13*@51) */
  w52  = (w13*w51);
  /* #100: @50 = (@50-@52) */
  w50 -= w52;
  /* #101: @49 = (@49/@50) */
  w49 /= w50;
  /* #102: @52 = kapparef_s(@14) */
  arg1[0]=(&w14);
  res1[0]=(&w52);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #103: @53 = (@13*@52) */
  w53  = (w13*w52);
  /* #104: @54 = (@53*@47) */
  w54  = (w53*w47);
  /* #105: @54 = (@54/@50) */
  w54 /= w50;
  /* #106: @55 = (@54/@50) */
  w55  = (w54/w50);
  /* #107: @39 = 00 */
  /* #108: @56 = fwd1_kapparef_s(@14, @39, @19) */
  arg1[0]=(&w14);
  arg1[1]=0;
  arg1[2]=(&w19);
  res1[0]=(&w56);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #109: @13 = (@13*@56) */
  w13 *= w56;
  /* #110: @13 = (@55*@13) */
  w13  = (w55*w13);
  /* #111: @49 = (@49+@13) */
  w49 += w13;
  /* #112: @49 = (@34*@49) */
  w49  = (w34*w49);
  /* #113: @38 = (@38-@49) */
  w38 -= w49;
  /* #114: @49 = 3 */
  w49 = 3.;
  /* #115: @49 = (@1-@49) */
  w49  = (w1-w49);
  /* #116: @13 = 2 */
  w13 = 2.;
  /* #117: @49 = (@49/@13) */
  w49 /= w13;
  /* #118: @13 = 0 */
  w13 = 0.;
  /* #119: @56 = fmax(@49,@13) */
  w56  = casadi_fmax(w49,w13);
  /* #120: @14 = 1 */
  w14 = 1.;
  /* #121: @19 = fmin(@56,@14) */
  w19  = casadi_fmin(w56,w14);
  /* #122: @57 = input[0][6] */
  w57 = arg[0] ? arg[0][6] : 0;
  /* #123: @58 = sin(@57) */
  w58 = sin( w57 );
  /* #124: @59 = 0.0005 */
  w59 = 5.0000000000000001e-04;
  /* #125: @60 = 92731.3 */
  w60 = 9.2731265615302604e+04;
  /* #126: @61 = (@60*@20) */
  w61  = (w60*w20);
  /* #127: @61 = (@59*@61) */
  w61  = (w59*w61);
  /* #128: @61 = (@58*@61) */
  w61  = (w58*w61);
  /* #129: @62 = 1.4 */
  w62 = 1.3999999999999999e+00;
  /* #130: @63 = input[0][5] */
  w63 = arg[0] ? arg[0][5] : 0;
  /* #131: @64 = (@62*@63) */
  w64  = (w62*w63);
  /* #132: @64 = (@10+@64) */
  w64  = (w10+w64);
  /* #133: @64 = (@64/@1) */
  w64 /= w1;
  /* #134: @65 = (@57-@64) */
  w65  = (w57-w64);
  /* #135: @65 = (@60*@65) */
  w65  = (w60*w65);
  /* #136: @65 = (@59*@65) */
  w65  = (w59*w65);
  /* #137: @66 = cos(@57) */
  w66 = cos( w57 );
  /* #138: @66 = (@66*@20) */
  w66 *= w20;
  /* #139: @66 = (@65*@66) */
  w66  = (w65*w66);
  /* #140: @61 = (@61+@66) */
  w61 += w66;
  /* #141: @61 = (@19*@61) */
  w61  = (w19*w61);
  /* #142: @61 = (-@61) */
  w61 = (- w61 );
  /* #143: @66 = 3 */
  w66 = 3.;
  /* #144: @66 = (@1-@66) */
  w66  = (w1-w66);
  /* #145: @67 = 2 */
  w67 = 2.;
  /* #146: @66 = (@66/@67) */
  w66 /= w67;
  /* #147: @67 = 0 */
  w67 = 0.;
  /* #148: @68 = fmax(@66,@67) */
  w68  = casadi_fmax(w66,w67);
  /* #149: @69 = 1 */
  w69 = 1.;
  /* #150: @70 = fmin(@68,@69) */
  w70  = casadi_fmin(w68,w69);
  /* #151: @71 = 0.0005 */
  w71 = 5.0000000000000001e-04;
  /* #152: @72 = cos(@57) */
  w72 = cos( w57 );
  /* #153: @73 = 92731.3 */
  w73 = 9.2731265615302604e+04;
  /* #154: @74 = (@73*@20) */
  w74  = (w73*w20);
  /* #155: @74 = (@72*@74) */
  w74  = (w72*w74);
  /* #156: @75 = 1.4 */
  w75 = 1.3999999999999999e+00;
  /* #157: @76 = (@75*@63) */
  w76  = (w75*w63);
  /* #158: @76 = (@10+@76) */
  w76  = (w10+w76);
  /* #159: @76 = (@76/@1) */
  w76 /= w1;
  /* #160: @77 = (@57-@76) */
  w77  = (w57-w76);
  /* #161: @77 = (@73*@77) */
  w77  = (w73*w77);
  /* #162: @78 = sin(@57) */
  w78 = sin( w57 );
  /* #163: @78 = (@78*@20) */
  w78 *= w20;
  /* #164: @78 = (@77*@78) */
  w78  = (w77*w78);
  /* #165: @74 = (@74-@78) */
  w74 -= w78;
  /* #166: @74 = (@71*@74) */
  w74  = (w71*w74);
  /* #167: @74 = (@70*@74) */
  w74  = (w70*w74);
  /* #168: @78 = 1 */
  w78 = 1.;
  /* #169: @78 = (@78-@70) */
  w78 -= w70;
  /* #170: @79 = 0.357143 */
  w79 = 3.5714285714285715e-01;
  /* #171: @80 = 1.4 */
  w80 = 1.3999999999999999e+00;
  /* #172: @81 = input[2][0] */
  w81 = arg[2] ? arg[2][0] : 0;
  /* #173: @82 = (@81*@20) */
  w82  = (w81*w20);
  /* #174: @82 = (@80*@82) */
  w82  = (w80*w82);
  /* #175: @82 = (@79*@82) */
  w82  = (w79*w82);
  /* #176: @82 = (@78*@82) */
  w82  = (w78*w82);
  /* #177: @74 = (@74+@82) */
  w74 += w82;
  /* #178: @82 = 3 */
  w82 = 3.;
  /* #179: @82 = (@1-@82) */
  w82  = (w1-w82);
  /* #180: @83 = 2 */
  w83 = 2.;
  /* #181: @82 = (@82/@83) */
  w82 /= w83;
  /* #182: @83 = 0 */
  w83 = 0.;
  /* #183: @84 = fmax(@82,@83) */
  w84  = casadi_fmax(w82,w83);
  /* #184: @85 = 1 */
  w85 = 1.;
  /* #185: @86 = fmin(@84,@85) */
  w86  = casadi_fmin(w84,w85);
  /* #186: @87 = 0.000255102 */
  w87 = 2.5510204081632655e-04;
  /* #187: @88 = cos(@57) */
  w88 = cos( w57 );
  /* #188: @89 = 1.4 */
  w89 = 1.3999999999999999e+00;
  /* #189: @90 = 92731.3 */
  w90 = 9.2731265615302604e+04;
  /* #190: @91 = (@90*@20) */
  w91  = (w90*w20);
  /* #191: @91 = (@89*@91) */
  w91  = (w89*w91);
  /* #192: @91 = (@88*@91) */
  w91  = (w88*w91);
  /* #193: @92 = 1.4 */
  w92 = 1.3999999999999999e+00;
  /* #194: @93 = (@92*@63) */
  w93  = (w92*w63);
  /* #195: @93 = (@10+@93) */
  w93  = (w10+w93);
  /* #196: @93 = (@93/@1) */
  w93 /= w1;
  /* #197: @94 = (@57-@93) */
  w94  = (w57-w93);
  /* #198: @94 = (@90*@94) */
  w94  = (w90*w94);
  /* #199: @94 = (@89*@94) */
  w94  = (w89*w94);
  /* #200: @95 = sin(@57) */
  w95 = sin( w57 );
  /* #201: @95 = (@95*@20) */
  w95 *= w20;
  /* #202: @95 = (@94*@95) */
  w95  = (w94*w95);
  /* #203: @91 = (@91-@95) */
  w91 -= w95;
  /* #204: @91 = (@87*@91) */
  w91  = (w87*w91);
  /* #205: @91 = (@86*@91) */
  w91  = (w86*w91);
  /* #206: @95 = 1 */
  w95 = 1.;
  /* #207: @95 = (@95-@86) */
  w95 -= w86;
  /* #208: @96 = 0.357143 */
  w96 = 3.5714285714285715e-01;
  /* #209: @20 = (@81*@20) */
  w20  = (w81*w20);
  /* #210: @20 = (@96*@20) */
  w20  = (w96*w20);
  /* #211: @20 = (@95*@20) */
  w20  = (w95*w20);
  /* #212: @91 = (@91+@20) */
  w91 += w20;
  /* #213: @39 = 00 */
  /* #214: @97 = vertcat(@21, @17, @38, @61, @74, @91, @39) */
  rr=w97;
  *rr++ = w21;
  *rr++ = w38;
  *rr++ = w61;
  *rr++ = w74;
  *rr++ = w91;
  /* #215: @97 = (-@97) */
  for (i=0, rr=w97, cs=w97; i<5; ++i) *rr++ = (- *cs++ );
  /* #216: @98 = @97[:5] */
  for (rr=w98, ss=w97+0; ss!=w97+5; ss+=1) *rr++ = *ss;
  /* #217: (@0[0, 8, 17, 21, 25] = @98) */
  for (cii=casadi_s6, rr=w0, ss=w98; cii!=casadi_s6+5; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #218: @21 = ones(7x1,1nz) */
  w21 = 1.;
  /* #219: {NULL, @38, NULL, NULL, NULL, NULL, NULL} = vertsplit(@21) */
  w38 = w21;
  /* #220: @15 = (@15*@38) */
  w15 *= w38;
  /* #221: @16 = (@16*@15) */
  w16 *= w15;
  /* #222: @16 = (@6*@16) */
  w16  = (w6*w16);
  /* #223: @27 = (@27*@38) */
  w27 *= w38;
  /* #224: @28 = (@28*@27) */
  w28 *= w27;
  /* #225: @28 = (@22*@28) */
  w28  = (w22*w28);
  /* #226: @16 = (@16+@28) */
  w16 += w28;
  /* #227: @17 = 00 */
  /* #228: @42 = (@42*@38) */
  w42 *= w38;
  /* #229: @36 = (@36*@42) */
  w36 *= w42;
  /* #230: @36 = (@36/@40) */
  w36 /= w40;
  /* #231: @41 = (@41*@38) */
  w41 *= w38;
  /* #232: @45 = (@45*@41) */
  w45 *= w41;
  /* #233: @36 = (@36+@45) */
  w36 += w45;
  /* #234: @36 = (@29*@36) */
  w36  = (w29*w36);
  /* #235: @36 = (-@36) */
  w36 = (- w36 );
  /* #236: @52 = (@52*@38) */
  w52 *= w38;
  /* #237: @47 = (@47*@52) */
  w47 *= w52;
  /* #238: @47 = (@47/@50) */
  w47 /= w50;
  /* #239: @51 = (@51*@38) */
  w51 *= w38;
  /* #240: @55 = (@55*@51) */
  w55 *= w51;
  /* #241: @47 = (@47+@55) */
  w47 += w55;
  /* #242: @47 = (@34*@47) */
  w47  = (w34*w47);
  /* #243: @36 = (@36-@47) */
  w36 -= w47;
  /* #244: @39 = 00 */
  /* #245: @99 = 00 */
  /* #246: @100 = 00 */
  /* #247: @101 = 00 */
  /* #248: @18 = vertcat(@16, @17, @36, @39, @99, @100, @101) */
  rr=w18;
  *rr++ = w16;
  *rr++ = w36;
  /* #249: @18 = (-@18) */
  for (i=0, rr=w18, cs=w18; i<2; ++i) *rr++ = (- *cs++ );
  /* #250: @102 = @18[:2] */
  for (rr=w102, ss=w18+0; ss!=w18+2; ss+=1) *rr++ = *ss;
  /* #251: (@0[1:17:8] = @102) */
  for (rr=w0+1, ss=w102; rr!=w0+17; rr+=8) *rr = *ss++;
  /* #252: @16 = cos(@7) */
  w16 = cos( w7 );
  /* #253: @36 = ones(7x1,1nz) */
  w36 = 1.;
  /* #254: {NULL, NULL, @47, NULL, NULL, NULL, NULL} = vertsplit(@36) */
  w47 = w36;
  /* #255: @16 = (@16*@47) */
  w16 *= w47;
  /* #256: @16 = (@10*@16) */
  w16  = (w10*w16);
  /* #257: @16 = (-@16) */
  w16 = (- w16 );
  /* #258: @36 = sin(@7) */
  w36 = sin( w7 );
  /* #259: @36 = (@36*@47) */
  w36 *= w47;
  /* #260: @36 = (@1*@36) */
  w36  = (w1*w36);
  /* #261: @16 = (@16-@36) */
  w16 -= w36;
  /* #262: @16 = (@16/@12) */
  w16 /= w12;
  /* #263: @16 = (@6*@16) */
  w16  = (w6*w16);
  /* #264: @36 = cos(@7) */
  w36 = cos( w7 );
  /* #265: @36 = (@36*@47) */
  w36 *= w47;
  /* #266: @36 = (@10*@36) */
  w36  = (w10*w36);
  /* #267: @36 = (-@36) */
  w36 = (- w36 );
  /* #268: @55 = sin(@7) */
  w55 = sin( w7 );
  /* #269: @55 = (@55*@47) */
  w55 *= w47;
  /* #270: @55 = (@1*@55) */
  w55  = (w1*w55);
  /* #271: @36 = (@36-@55) */
  w36 -= w55;
  /* #272: @36 = (@36/@26) */
  w36 /= w26;
  /* #273: @36 = (@22*@36) */
  w36  = (w22*w36);
  /* #274: @16 = (@16+@36) */
  w16 += w36;
  /* #275: @36 = 3 */
  w36 = 3.;
  /* #276: @36 = (@1-@36) */
  w36  = (w1-w36);
  /* #277: @55 = 2 */
  w55 = 2.;
  /* #278: @36 = (@36/@55) */
  w36 /= w55;
  /* #279: @55 = 0 */
  w55 = 0.;
  /* #280: @51 = fmax(@36,@55) */
  w51  = casadi_fmax(w36,w55);
  /* #281: @38 = 1 */
  w38 = 1.;
  /* #282: @52 = fmin(@51,@38) */
  w52  = casadi_fmin(w51,w38);
  /* #283: @45 = cos(@7) */
  w45 = cos( w7 );
  /* #284: @45 = (@45*@47) */
  w45 *= w47;
  /* #285: @45 = (@1*@45) */
  w45  = (w1*w45);
  /* #286: @41 = sin(@7) */
  w41 = sin( w7 );
  /* #287: @41 = (@41*@47) */
  w41 *= w47;
  /* #288: @41 = (@10*@41) */
  w41  = (w10*w41);
  /* #289: @45 = (@45-@41) */
  w45 -= w41;
  /* #290: @45 = (@52*@45) */
  w45  = (w52*w45);
  /* #291: @41 = 1 */
  w41 = 1.;
  /* #292: @41 = (@41-@52) */
  w41 -= w52;
  /* #293: @42 = cos(@7) */
  w42 = cos( w7 );
  /* #294: @42 = (@42*@47) */
  w42 *= w47;
  /* #295: @42 = (@1*@42) */
  w42  = (w1*w42);
  /* #296: @28 = sin(@7) */
  w28 = sin( w7 );
  /* #297: @28 = (@28*@47) */
  w28 *= w47;
  /* #298: @28 = (@10*@28) */
  w28  = (w10*w28);
  /* #299: @42 = (@42-@28) */
  w42 -= w28;
  /* #300: @42 = (@41*@42) */
  w42  = (w41*w42);
  /* #301: @45 = (@45+@42) */
  w45 += w42;
  /* #302: @42 = cos(@7) */
  w42 = cos( w7 );
  /* #303: @42 = (@42*@47) */
  w42 *= w47;
  /* #304: @42 = (@10*@42) */
  w42  = (w10*w42);
  /* #305: @42 = (-@42) */
  w42 = (- w42 );
  /* #306: @28 = sin(@7) */
  w28 = sin( w7 );
  /* #307: @28 = (@28*@47) */
  w28 *= w47;
  /* #308: @28 = (@1*@28) */
  w28  = (w1*w28);
  /* #309: @42 = (@42-@28) */
  w42 -= w28;
  /* #310: @42 = (@43*@42) */
  w42  = (w43*w42);
  /* #311: @42 = (@42/@40) */
  w42 /= w40;
  /* #312: @42 = (@29*@42) */
  w42  = (w29*w42);
  /* #313: @42 = (-@42) */
  w42 = (- w42 );
  /* #314: @28 = cos(@7) */
  w28 = cos( w7 );
  /* #315: @28 = (@28*@47) */
  w28 *= w47;
  /* #316: @28 = (@10*@28) */
  w28  = (w10*w28);
  /* #317: @28 = (-@28) */
  w28 = (- w28 );
  /* #318: @27 = sin(@7) */
  w27 = sin( w7 );
  /* #319: @27 = (@27*@47) */
  w27 *= w47;
  /* #320: @27 = (@1*@27) */
  w27  = (w1*w27);
  /* #321: @28 = (@28-@27) */
  w28 -= w27;
  /* #322: @28 = (@53*@28) */
  w28  = (w53*w28);
  /* #323: @28 = (@28/@50) */
  w28 /= w50;
  /* #324: @28 = (@34*@28) */
  w28  = (w34*w28);
  /* #325: @42 = (@42-@28) */
  w42 -= w28;
  /* #326: @17 = 00 */
  /* #327: @39 = 00 */
  /* #328: @99 = 00 */
  /* #329: @100 = 00 */
  /* #330: @103 = vertcat(@16, @45, @42, @17, @39, @99, @100) */
  rr=w103;
  *rr++ = w16;
  *rr++ = w45;
  *rr++ = w42;
  /* #331: @103 = (-@103) */
  for (i=0, rr=w103, cs=w103; i<3; ++i) *rr++ = (- *cs++ );
  /* #332: @104 = @103[:3] */
  for (rr=w104, ss=w103+0; ss!=w103+3; ss+=1) *rr++ = *ss;
  /* #333: (@0[2, 5, 10] = @104) */
  for (cii=casadi_s7, rr=w0, ss=w104; cii!=casadi_s7+3; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #334: @4 = (@4<=@5) */
  w4  = (w4<=w5);
  /* #335: @3 = (@3<=@2) */
  w3  = (w3<=w2);
  /* #336: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #337: @5 = ones(7x1,1nz) */
  w5 = 1.;
  /* #338: {NULL, NULL, NULL, @16, NULL, NULL, NULL} = vertsplit(@5) */
  w16 = w5;
  /* #339: @2 = (@2*@16) */
  w2 *= w16;
  /* #340: @3 = (@3*@2) */
  w3 *= w2;
  /* #341: @4 = (@4*@3) */
  w4 *= w3;
  /* #342: @9 = (@9*@4) */
  w9 *= w4;
  /* #343: @8 = (@8*@16) */
  w8 *= w16;
  /* #344: @8 = (@8/@12) */
  w8 /= w12;
  /* #345: @8 = (@6*@8) */
  w8  = (w6*w8);
  /* #346: @9 = (@9+@8) */
  w9 += w8;
  /* #347: @23 = (@23*@16) */
  w23 *= w16;
  /* #348: @23 = (@23/@26) */
  w23 /= w26;
  /* #349: @23 = (@22*@23) */
  w23  = (w22*w23);
  /* #350: @24 = (@24*@4) */
  w24 *= w4;
  /* #351: @23 = (@23-@24) */
  w23 -= w24;
  /* #352: @9 = (@9+@23) */
  w9 += w23;
  /* #353: @23 = sin(@7) */
  w23 = sin( w7 );
  /* #354: @24 = (@1*@23) */
  w24  = (w1*w23);
  /* #355: @4 = cos(@7) */
  w4 = cos( w7 );
  /* #356: @8 = (@10*@4) */
  w8  = (w10*w4);
  /* #357: @24 = (@24+@8) */
  w24 += w8;
  /* #358: @51 = (@51<=@38) */
  w51  = (w51<=w38);
  /* #359: @55 = (@55<=@36) */
  w55  = (w55<=w36);
  /* #360: @36 = 0.5 */
  w36 = 5.0000000000000000e-01;
  /* #361: @36 = (@36*@16) */
  w36 *= w16;
  /* #362: @55 = (@55*@36) */
  w55 *= w36;
  /* #363: @51 = (@51*@55) */
  w51 *= w55;
  /* #364: @24 = (@24*@51) */
  w24 *= w51;
  /* #365: @23 = (@23*@16) */
  w23 *= w16;
  /* #366: @23 = (@52*@23) */
  w23  = (w52*w23);
  /* #367: @24 = (@24+@23) */
  w24 += w23;
  /* #368: @23 = sin(@7) */
  w23 = sin( w7 );
  /* #369: @55 = (@23*@16) */
  w55  = (w23*w16);
  /* #370: @55 = (@41*@55) */
  w55  = (w41*w55);
  /* #371: @23 = (@1*@23) */
  w23  = (w1*w23);
  /* #372: @7 = cos(@7) */
  w7 = cos( w7 );
  /* #373: @36 = (@10*@7) */
  w36  = (w10*w7);
  /* #374: @23 = (@23+@36) */
  w23 += w36;
  /* #375: @23 = (@23*@51) */
  w23 *= w51;
  /* #376: @55 = (@55-@23) */
  w55 -= w23;
  /* #377: @24 = (@24+@55) */
  w24 += w55;
  /* #378: @54 = (@63-@54) */
  w54  = (w63-w54);
  /* #379: @32 = (@32<=@33) */
  w32  = (w32<=w33);
  /* #380: @31 = (@31<=@30) */
  w31  = (w31<=w30);
  /* #381: @30 = 0.5 */
  w30 = 5.0000000000000000e-01;
  /* #382: @30 = (@30*@16) */
  w30 *= w16;
  /* #383: @31 = (@31*@30) */
  w31 *= w30;
  /* #384: @32 = (@32*@31) */
  w32 *= w31;
  /* #385: @54 = (@54*@32) */
  w54 *= w32;
  /* #386: @46 = (@46*@16) */
  w46 *= w16;
  /* #387: @46 = (@53*@46) */
  w46  = (w53*w46);
  /* #388: @46 = (@46/@50) */
  w46 /= w50;
  /* #389: @46 = (@34*@46) */
  w46  = (w34*w46);
  /* #390: @54 = (@54-@46) */
  w54 -= w46;
  /* #391: @35 = (@35*@16) */
  w35 *= w16;
  /* #392: @35 = (@43*@35) */
  w35  = (w43*w35);
  /* #393: @35 = (@35/@40) */
  w35 /= w40;
  /* #394: @35 = (@29*@35) */
  w35  = (w29*w35);
  /* #395: @35 = (-@35) */
  w35 = (- w35 );
  /* #396: @44 = (@63-@44) */
  w44  = (w63-w44);
  /* #397: @44 = (@44*@32) */
  w44 *= w32;
  /* #398: @35 = (@35-@44) */
  w35 -= w44;
  /* #399: @54 = (@54+@35) */
  w54 += w35;
  /* #400: @65 = (@65*@58) */
  w65 *= w58;
  /* #401: @65 = (@81-@65) */
  w65  = (w81-w65);
  /* #402: @35 = (@10*@63) */
  w35  = (w10*w63);
  /* #403: @65 = (@65+@35) */
  w65 += w35;
  /* #404: @56 = (@56<=@14) */
  w56  = (w56<=w14);
  /* #405: @13 = (@13<=@49) */
  w13  = (w13<=w49);
  /* #406: @49 = 0.5 */
  w49 = 5.0000000000000000e-01;
  /* #407: @49 = (@49*@16) */
  w49 *= w16;
  /* #408: @13 = (@13*@49) */
  w13 *= w49;
  /* #409: @56 = (@56*@13) */
  w56 *= w13;
  /* #410: @65 = (@65*@56) */
  w65 *= w56;
  /* #411: @64 = (@64/@1) */
  w64 /= w1;
  /* #412: @64 = (@64*@16) */
  w64 *= w16;
  /* #413: @64 = (@60*@64) */
  w64  = (w60*w64);
  /* #414: @64 = (@59*@64) */
  w64  = (w59*w64);
  /* #415: @64 = (@58*@64) */
  w64  = (w58*w64);
  /* #416: @64 = (@19*@64) */
  w64  = (w19*w64);
  /* #417: @65 = (@65-@64) */
  w65 -= w64;
  /* #418: @56 = (@81*@56) */
  w56  = (w81*w56);
  /* #419: @65 = (@65-@56) */
  w65 -= w56;
  /* #420: @56 = 92731.3 */
  w56 = 9.2731265615302604e+04;
  /* #421: @64 = 1.4 */
  w64 = 1.3999999999999999e+00;
  /* #422: @13 = (@64*@63) */
  w13  = (w64*w63);
  /* #423: @13 = (@13-@10) */
  w13 -= w10;
  /* #424: @13 = (@56*@13) */
  w13  = (w56*w13);
  /* #425: @13 = (@13/@1) */
  w13 /= w1;
  /* #426: @77 = (@77*@72) */
  w77 *= w72;
  /* #427: @77 = (@13+@77) */
  w77  = (w13+w77);
  /* #428: @77 = (@71*@77) */
  w77  = (w71*w77);
  /* #429: @49 = (@1*@63) */
  w49  = (w1*w63);
  /* #430: @77 = (@77-@49) */
  w77 -= w49;
  /* #431: @68 = (@68<=@69) */
  w68  = (w68<=w69);
  /* #432: @67 = (@67<=@66) */
  w67  = (w67<=w66);
  /* #433: @66 = 0.5 */
  w66 = 5.0000000000000000e-01;
  /* #434: @66 = (@66*@16) */
  w66 *= w16;
  /* #435: @67 = (@67*@66) */
  w67 *= w66;
  /* #436: @68 = (@68*@67) */
  w68 *= w67;
  /* #437: @77 = (@77*@68) */
  w77 *= w68;
  /* #438: @76 = (@76/@1) */
  w76 /= w1;
  /* #439: @76 = (@76*@16) */
  w76 *= w16;
  /* #440: @76 = (@73*@76) */
  w76  = (w73*w76);
  /* #441: @76 = (@72*@76) */
  w76  = (w72*w76);
  /* #442: @13 = (@13/@1) */
  w13 /= w1;
  /* #443: @13 = (@13*@16) */
  w13 *= w16;
  /* #444: @76 = (@76-@13) */
  w76 -= w13;
  /* #445: @76 = (@71*@76) */
  w76  = (w71*w76);
  /* #446: @13 = (@63*@16) */
  w13  = (w63*w16);
  /* #447: @76 = (@76-@13) */
  w76 -= w13;
  /* #448: @76 = (@70*@76) */
  w76  = (w70*w76);
  /* #449: @77 = (@77+@76) */
  w77 += w76;
  /* #450: @76 = input[2][1] */
  w76 = arg[2] ? arg[2][1] : 0;
  /* #451: @13 = (@76*@16) */
  w13  = (w76*w16);
  /* #452: @13 = (@80*@13) */
  w13  = (w80*w13);
  /* #453: @79 = (@79*@13) */
  w79 *= w13;
  /* #454: @79 = (@78*@79) */
  w79  = (w78*w79);
  /* #455: @13 = (@76*@1) */
  w13  = (w76*w1);
  /* #456: @67 = (@57*@81) */
  w67  = (w57*w81);
  /* #457: @13 = (@13+@67) */
  w13 += w67;
  /* #458: @13 = (@80*@13) */
  w13  = (w80*w13);
  /* #459: @67 = 2.8 */
  w67 = 2.7999999999999998e+00;
  /* #460: @13 = (@13/@67) */
  w13 /= w67;
  /* #461: @13 = (@13*@68) */
  w13 *= w68;
  /* #462: @79 = (@79-@13) */
  w79 -= w13;
  /* #463: @77 = (@77+@79) */
  w77 += w79;
  /* #464: @94 = (@94*@88) */
  w94 *= w88;
  /* #465: @79 = 1.4 */
  w79 = 1.3999999999999999e+00;
  /* #466: @13 = 92731.3 */
  w13 = 9.2731265615302604e+04;
  /* #467: @68 = 1.4 */
  w68 = 1.3999999999999999e+00;
  /* #468: @67 = (@68*@63) */
  w67  = (w68*w63);
  /* #469: @67 = (@67-@10) */
  w67 -= w10;
  /* #470: @67 = (@13*@67) */
  w67  = (w13*w67);
  /* #471: @67 = (@67/@1) */
  w67 /= w1;
  /* #472: @66 = (@79*@67) */
  w66  = (w79*w67);
  /* #473: @94 = (@94-@66) */
  w94 -= w66;
  /* #474: @94 = (@87*@94) */
  w94  = (w87*w94);
  /* #475: @84 = (@84<=@85) */
  w84  = (w84<=w85);
  /* #476: @83 = (@83<=@82) */
  w83  = (w83<=w82);
  /* #477: @82 = 0.5 */
  w82 = 5.0000000000000000e-01;
  /* #478: @82 = (@82*@16) */
  w82 *= w16;
  /* #479: @83 = (@83*@82) */
  w83 *= w82;
  /* #480: @84 = (@84*@83) */
  w84 *= w83;
  /* #481: @94 = (@94*@84) */
  w94 *= w84;
  /* #482: @93 = (@93/@1) */
  w93 /= w1;
  /* #483: @93 = (@93*@16) */
  w93 *= w16;
  /* #484: @93 = (@90*@93) */
  w93  = (w90*w93);
  /* #485: @93 = (@89*@93) */
  w93  = (w89*w93);
  /* #486: @93 = (@88*@93) */
  w93  = (w88*w93);
  /* #487: @67 = (@67/@1) */
  w67 /= w1;
  /* #488: @67 = (@67*@16) */
  w67 *= w16;
  /* #489: @67 = (@79*@67) */
  w67  = (w79*w67);
  /* #490: @93 = (@93+@67) */
  w93 += w67;
  /* #491: @93 = (@87*@93) */
  w93  = (w87*w93);
  /* #492: @93 = (@86*@93) */
  w93  = (w86*w93);
  /* #493: @94 = (@94+@93) */
  w94 += w93;
  /* #494: @16 = (@76*@16) */
  w16  = (w76*w16);
  /* #495: @96 = (@96*@16) */
  w96 *= w16;
  /* #496: @96 = (@95*@96) */
  w96  = (w95*w96);
  /* #497: @76 = (@76*@1) */
  w76 *= w1;
  /* #498: @81 = (@57*@81) */
  w81  = (w57*w81);
  /* #499: @76 = (@76+@81) */
  w76 += w81;
  /* #500: @81 = 2.8 */
  w81 = 2.7999999999999998e+00;
  /* #501: @76 = (@76/@81) */
  w76 /= w81;
  /* #502: @76 = (@76*@84) */
  w76 *= w84;
  /* #503: @96 = (@96-@76) */
  w96 -= w76;
  /* #504: @94 = (@94+@96) */
  w94 += w96;
  /* #505: @17 = 00 */
  /* #506: @105 = vertcat(@9, @24, @54, @65, @77, @94, @17) */
  rr=w105;
  *rr++ = w9;
  *rr++ = w24;
  *rr++ = w54;
  *rr++ = w65;
  *rr++ = w77;
  *rr++ = w94;
  /* #507: @105 = (-@105) */
  for (i=0, rr=w105, cs=w105; i<6; ++i) *rr++ = (- *cs++ );
  /* #508: @106 = @105[:6] */
  for (rr=w106, ss=w105+0; ss!=w105+6; ss+=1) *rr++ = *ss;
  /* #509: (@0[3, 6, 11, 14, 18, 22] = @106) */
  for (cii=casadi_s8, rr=w0, ss=w106; cii!=casadi_s8+6; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #510: @9 = ones(7x1,1nz) */
  w9 = 1.;
  /* #511: {NULL, NULL, NULL, NULL, @24, NULL, NULL} = vertsplit(@9) */
  w24 = w9;
  /* #512: @25 = (@25*@24) */
  w25 *= w24;
  /* #513: @25 = (@25/@26) */
  w25 /= w26;
  /* #514: @22 = (@22*@25) */
  w22 *= w25;
  /* #515: @22 = (-@22) */
  w22 = (- w22 );
  /* #516: @11 = (@11*@24) */
  w11 *= w24;
  /* #517: @11 = (@11/@12) */
  w11 /= w12;
  /* #518: @6 = (@6*@11) */
  w6 *= w11;
  /* #519: @22 = (@22-@6) */
  w22 -= w6;
  /* #520: @4 = (@4*@24) */
  w4 *= w24;
  /* #521: @52 = (@52*@4) */
  w52 *= w4;
  /* #522: @7 = (@7*@24) */
  w7 *= w24;
  /* #523: @41 = (@41*@7) */
  w41 *= w7;
  /* #524: @52 = (@52+@41) */
  w52 += w41;
  /* #525: @48 = (@48*@24) */
  w48 *= w24;
  /* #526: @53 = (@53*@48) */
  w53 *= w48;
  /* #527: @53 = (@53/@50) */
  w53 /= w50;
  /* #528: @53 = (@34*@53) */
  w53  = (w34*w53);
  /* #529: @37 = (@37*@24) */
  w37 *= w24;
  /* #530: @43 = (@43*@37) */
  w43 *= w37;
  /* #531: @43 = (@43/@40) */
  w43 /= w40;
  /* #532: @43 = (@29*@43) */
  w43  = (w29*w43);
  /* #533: @53 = (@53+@43) */
  w53 += w43;
  /* #534: @43 = (@24/@1) */
  w43  = (w24/w1);
  /* #535: @43 = (@60*@43) */
  w43  = (w60*w43);
  /* #536: @43 = (@59*@43) */
  w43  = (w59*w43);
  /* #537: @43 = (@58*@43) */
  w43  = (w58*w43);
  /* #538: @63 = (@63*@24) */
  w63 *= w24;
  /* #539: @43 = (@43+@63) */
  w43 += w63;
  /* #540: @43 = (@19*@43) */
  w43  = (w19*w43);
  /* #541: @63 = (@24/@1) */
  w63  = (w24/w1);
  /* #542: @63 = (@73*@63) */
  w63  = (w73*w63);
  /* #543: @63 = (@72*@63) */
  w63  = (w72*w63);
  /* #544: @63 = (-@63) */
  w63 = (- w63 );
  /* #545: @40 = (@56*@24) */
  w40  = (w56*w24);
  /* #546: @40 = (@40/@1) */
  w40 /= w1;
  /* #547: @63 = (@63-@40) */
  w63 -= w40;
  /* #548: @63 = (@71*@63) */
  w63  = (w71*w63);
  /* #549: @63 = (@70*@63) */
  w63  = (w70*w63);
  /* #550: @40 = (@13*@24) */
  w40  = (w13*w24);
  /* #551: @40 = (@40/@1) */
  w40 /= w1;
  /* #552: @40 = (@79*@40) */
  w40  = (w79*w40);
  /* #553: @24 = (@24/@1) */
  w24 /= w1;
  /* #554: @24 = (@90*@24) */
  w24  = (w90*w24);
  /* #555: @24 = (@89*@24) */
  w24  = (w89*w24);
  /* #556: @24 = (@88*@24) */
  w24  = (w88*w24);
  /* #557: @40 = (@40-@24) */
  w40 -= w24;
  /* #558: @40 = (@87*@40) */
  w40  = (w87*w40);
  /* #559: @40 = (@86*@40) */
  w40  = (w86*w40);
  /* #560: @17 = 00 */
  /* #561: @106 = vertcat(@22, @52, @53, @43, @63, @40, @17) */
  rr=w106;
  *rr++ = w22;
  *rr++ = w52;
  *rr++ = w53;
  *rr++ = w43;
  *rr++ = w63;
  *rr++ = w40;
  /* #562: @106 = (-@106) */
  for (i=0, rr=w106, cs=w106; i<6; ++i) *rr++ = (- *cs++ );
  /* #563: @105 = @106[:6] */
  for (rr=w105, ss=w106+0; ss!=w106+6; ss+=1) *rr++ = *ss;
  /* #564: (@0[4, 7, 12, 15, 19, 23] = @105) */
  for (cii=casadi_s9, rr=w0, ss=w105; cii!=casadi_s9+6; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #565: @17 = 00 */
  /* #566: @39 = 00 */
  /* #567: @22 = ones(7x1,1nz) */
  w22 = 1.;
  /* #568: {NULL, NULL, NULL, NULL, NULL, @52, NULL} = vertsplit(@22) */
  w52 = w22;
  /* #569: @34 = (@34*@52) */
  w34 *= w52;
  /* #570: @29 = (@29*@52) */
  w29 *= w52;
  /* #571: @34 = (@34+@29) */
  w34 += w29;
  /* #572: @62 = (@62*@52) */
  w62 *= w52;
  /* #573: @62 = (@62/@1) */
  w62 /= w1;
  /* #574: @60 = (@60*@62) */
  w60 *= w62;
  /* #575: @59 = (@59*@60) */
  w59 *= w60;
  /* #576: @58 = (@58*@59) */
  w58 *= w59;
  /* #577: @10 = (@10*@52) */
  w10 *= w52;
  /* #578: @58 = (@58+@10) */
  w58 += w10;
  /* #579: @58 = (@19*@58) */
  w58  = (w19*w58);
  /* #580: @64 = (@64*@52) */
  w64 *= w52;
  /* #581: @56 = (@56*@64) */
  w56 *= w64;
  /* #582: @56 = (@56/@1) */
  w56 /= w1;
  /* #583: @75 = (@75*@52) */
  w75 *= w52;
  /* #584: @75 = (@75/@1) */
  w75 /= w1;
  /* #585: @73 = (@73*@75) */
  w73 *= w75;
  /* #586: @72 = (@72*@73) */
  w72 *= w73;
  /* #587: @56 = (@56-@72) */
  w56 -= w72;
  /* #588: @71 = (@71*@56) */
  w71 *= w56;
  /* #589: @56 = (@1*@52) */
  w56  = (w1*w52);
  /* #590: @71 = (@71-@56) */
  w71 -= w56;
  /* #591: @70 = (@70*@71) */
  w70 *= w71;
  /* #592: @68 = (@68*@52) */
  w68 *= w52;
  /* #593: @13 = (@13*@68) */
  w13 *= w68;
  /* #594: @13 = (@13/@1) */
  w13 /= w1;
  /* #595: @79 = (@79*@13) */
  w79 *= w13;
  /* #596: @79 = (-@79) */
  w79 = (- w79 );
  /* #597: @92 = (@92*@52) */
  w92 *= w52;
  /* #598: @92 = (@92/@1) */
  w92 /= w1;
  /* #599: @90 = (@90*@92) */
  w90 *= w92;
  /* #600: @89 = (@89*@90) */
  w89 *= w90;
  /* #601: @88 = (@88*@89) */
  w88 *= w89;
  /* #602: @79 = (@79-@88) */
  w79 -= w88;
  /* #603: @87 = (@87*@79) */
  w87 *= w79;
  /* #604: @86 = (@86*@87) */
  w86 *= w87;
  /* #605: @99 = 00 */
  /* #606: @107 = vertcat(@17, @39, @34, @58, @70, @86, @99) */
  rr=w107;
  *rr++ = w34;
  *rr++ = w58;
  *rr++ = w70;
  *rr++ = w86;
  /* #607: @107 = (-@107) */
  for (i=0, rr=w107, cs=w107; i<4; ++i) *rr++ = (- *cs++ );
  /* #608: @108 = @107[:4] */
  for (rr=w108, ss=w107+0; ss!=w107+4; ss+=1) *rr++ = *ss;
  /* #609: (@0[13, 16, 20, 24] = @108) */
  for (cii=casadi_s10, rr=w0, ss=w108; cii!=casadi_s10+4; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #610: @109 = @0' */
  casadi_trans(w0,casadi_s12, w109, casadi_s11, iw);
  /* #611: output[0][0] = @109 */
  casadi_copy(w109, 26, res[0]);
  /* #612: @110 = zeros(7x7,7nz) */
  casadi_clear(w110, 7);
  /* #613: @111 = ones(7x1) */
  casadi_fill(w111, 7, 1.);
  /* #614: (@110[:7] = @111) */
  for (rr=w110+0, ss=w111; rr!=w110+7; rr+=1) *rr = *ss++;
  /* #615: @111 = @110' */
  casadi_trans(w110,casadi_s13, w111, casadi_s13, iw);
  /* #616: output[1][0] = @111 */
  casadi_copy(w111, 7, res[1]);
  /* #617: @105 = zeros(2x7,6nz) */
  casadi_clear(w105, 6);
  /* #618: @17 = 00 */
  /* #619: @39 = 00 */
  /* #620: @99 = 00 */
  /* #621: @34 = ones(2x1,1nz) */
  w34 = 1.;
  /* #622: {@58, NULL} = vertsplit(@34) */
  w58 = w34;
  /* #623: @34 = (@19*@58) */
  w34  = (w19*w58);
  /* #624: @70 = 1 */
  w70 = 1.;
  /* #625: @70 = (@70-@19) */
  w70 -= w19;
  /* #626: @70 = (@70*@58) */
  w70 *= w58;
  /* #627: @34 = (@34+@70) */
  w34 += w70;
  /* #628: @70 = 0.357143 */
  w70 = 3.5714285714285715e-01;
  /* #629: @19 = (@57*@58) */
  w19  = (w57*w58);
  /* #630: @19 = (@80*@19) */
  w19  = (w80*w19);
  /* #631: @19 = (@70*@19) */
  w19  = (w70*w19);
  /* #632: @19 = (@78*@19) */
  w19  = (w78*w19);
  /* #633: @86 = 0.357143 */
  w86 = 3.5714285714285715e-01;
  /* #634: @57 = (@57*@58) */
  w57 *= w58;
  /* #635: @57 = (@86*@57) */
  w57  = (w86*w57);
  /* #636: @57 = (@95*@57) */
  w57  = (w95*w57);
  /* #637: @100 = 00 */
  /* #638: @104 = vertcat(@17, @39, @99, @34, @19, @57, @100) */
  rr=w104;
  *rr++ = w34;
  *rr++ = w19;
  *rr++ = w57;
  /* #639: @104 = (-@104) */
  for (i=0, rr=w104, cs=w104; i<3; ++i) *rr++ = (- *cs++ );
  /* #640: @103 = @104[:3] */
  for (rr=w103, ss=w104+0; ss!=w104+3; ss+=1) *rr++ = *ss;
  /* #641: (@105[0, 1, 3] = @103) */
  for (cii=casadi_s14, rr=w105, ss=w103; cii!=casadi_s14+3; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #642: @17 = 00 */
  /* #643: @39 = 00 */
  /* #644: @99 = 00 */
  /* #645: @100 = 00 */
  /* #646: @34 = ones(2x1,1nz) */
  w34 = 1.;
  /* #647: {NULL, @19} = vertsplit(@34) */
  w19 = w34;
  /* #648: @34 = (@1*@19) */
  w34  = (w1*w19);
  /* #649: @80 = (@80*@34) */
  w80 *= w34;
  /* #650: @70 = (@70*@80) */
  w70 *= w80;
  /* #651: @78 = (@78*@70) */
  w78 *= w70;
  /* #652: @1 = (@1*@19) */
  w1 *= w19;
  /* #653: @86 = (@86*@1) */
  w86 *= w1;
  /* #654: @95 = (@95*@86) */
  w95 *= w86;
  /* #655: @103 = vertcat(@17, @39, @99, @100, @78, @95, @19) */
  rr=w103;
  *rr++ = w78;
  *rr++ = w95;
  *rr++ = w19;
  /* #656: @103 = (-@103) */
  for (i=0, rr=w103, cs=w103; i<3; ++i) *rr++ = (- *cs++ );
  /* #657: @104 = @103[:3] */
  for (rr=w104, ss=w103+0; ss!=w103+3; ss+=1) *rr++ = *ss;
  /* #658: (@105[2, 4, 5] = @104) */
  for (cii=casadi_s15, rr=w105, ss=w104; cii!=casadi_s15+3; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #659: @106 = @105' */
  casadi_trans(w105,casadi_s17, w106, casadi_s16, iw);
  /* #660: output[2][0] = @106 */
  casadi_copy(w106, 6, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int sim_car_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int sim_car_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int sim_car_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void sim_car_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int sim_car_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void sim_car_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void sim_car_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void sim_car_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int sim_car_impl_dae_jac_x_xdot_u_z_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int sim_car_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real sim_car_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* sim_car_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* sim_car_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* sim_car_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s18;
    case 1: return casadi_s18;
    case 2: return casadi_s19;
    case 3: return casadi_s20;
    case 4: return casadi_s20;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* sim_car_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s11;
    case 1: return casadi_s13;
    case 2: return casadi_s16;
    case 3: return casadi_s21;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int sim_car_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 211;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
