/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) sim_car_impl_dae_fun_jac_x_xdot_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_low CASADI_PREFIX(low)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[1] = {0};
static const casadi_int casadi_s1[1] = {1};
static const casadi_int casadi_s2[1] = {3};
static const casadi_int casadi_s3[2] = {0, 9};
static const casadi_int casadi_s4[1] = {2};
static const casadi_int casadi_s5[2] = {0, 7};
static const casadi_int casadi_s6[5] = {0, 8, 17, 21, 25};
static const casadi_int casadi_s7[3] = {2, 5, 10};
static const casadi_int casadi_s8[6] = {3, 6, 11, 14, 18, 22};
static const casadi_int casadi_s9[6] = {4, 7, 12, 15, 19, 23};
static const casadi_int casadi_s10[4] = {13, 16, 20, 24};
static const casadi_int casadi_s11[36] = {7, 7, 0, 2, 4, 7, 13, 19, 23, 26, 0, 2, 0, 2, 0, 1, 2, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 2, 3, 4, 5, 3, 4, 5};
static const casadi_int casadi_s12[36] = {7, 7, 0, 5, 8, 14, 18, 22, 26, 26, 0, 1, 2, 3, 4, 2, 3, 4, 0, 1, 2, 3, 4, 5, 3, 4, 5, 6, 3, 4, 5, 6, 3, 4, 5, 6};
static const casadi_int casadi_s13[17] = {7, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s14[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s15[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s16[3] = {0, 0, 0};
static const casadi_int casadi_s17[3] = {7, 0, 0};

static const casadi_real casadi_c0[5] = {1.0000000000000019e-06, 9.9999999999999995e-07, 1.0000000000000002e-06, 1.0000000000000002e-06, 1.0000000000000019e-06};
static const casadi_real casadi_c1[9] = {0., 0., 0., 0., 2., 4., 4., 4., 4.};
static const casadi_real casadi_c2[4] = {-2.7528570785764761e-21, 1.0587911840678754e-22, 0., 2.5410988417629010e-21};
static const casadi_real casadi_c3[7] = {0., 0., 0., 2., 4., 4., 4.};

/* kapparef_s:(x)->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c1,casadi_s3,casadi_s2,casadi_s1,casadi_c0,1,(&w0),casadi_s0, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_kapparef_s:(x,out_f[1x1,0nz],fwd_x)->(fwd_f) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c3,casadi_s5,casadi_s4,casadi_s1,casadi_c2,1,(&w0),casadi_s0, iw, w);
  /* #2: @0 = input[2][0] */
  w0 = arg[2] ? arg[2][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* sim_car_impl_dae_fun_jac_x_xdot_z:(i0[7],i1[7],i2[2],i3[],i4[])->(o0[7],o1[7x7,26nz],o2[7x7,7nz],o3[7x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+4, *rr, *ss;
  const casadi_int *cii;
  const casadi_real **arg1=arg+5, *cs;
  casadi_real *w0=w+12, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35, w36, w37, w38, w39, w40, w41, w42, w43, w44, w45, w46, w47, w48, w49, w50, w51, w52, w53, w54, w55, w56, w57, w58, w59, w60, w61, w62, w63, w64, w65, w66, w67, w68, w69, w70, w71, w72, w73, w74, w75, w76, w77, w78, w79, w80, w81, w82, w83, w84, w85, w86, w87, w88, w89, w90, w91, w92, w93, w94, w95, w96, w97, w98, w99, w100, w101, w102, w103, w104, w105, w106, w107, w108, w109, w110, w111, w112, w113, w114, w115, w116, w117, *w118=w+136, *w119=w+143, *w121=w+169, w123, *w124=w+172, *w125=w+177, *w129=w+182, *w130=w+184, *w131=w+187, *w132=w+190, *w133=w+196, *w134=w+202, *w135=w+206, *w136=w+210;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 7, w0);
  /* #1: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = 3 */
  w2 = 3.;
  /* #3: @2 = (@1-@2) */
  w2  = (w1-w2);
  /* #4: @3 = 2 */
  w3 = 2.;
  /* #5: @2 = (@2/@3) */
  w2 /= w3;
  /* #6: @3 = 0 */
  w3 = 0.;
  /* #7: @4 = fmax(@2,@3) */
  w4  = casadi_fmax(w2,w3);
  /* #8: @5 = 1 */
  w5 = 1.;
  /* #9: @6 = fmin(@4,@5) */
  w6  = casadi_fmin(w4,w5);
  /* #10: @7 = input[0][2] */
  w7 = arg[0] ? arg[0][2] : 0;
  /* #11: @8 = cos(@7) */
  w8 = cos( w7 );
  /* #12: @9 = (@1*@8) */
  w9  = (w1*w8);
  /* #13: @10 = input[0][4] */
  w10 = arg[0] ? arg[0][4] : 0;
  /* #14: @11 = sin(@7) */
  w11 = sin( w7 );
  /* #15: @12 = (@10*@11) */
  w12  = (w10*w11);
  /* #16: @9 = (@9-@12) */
  w9 -= w12;
  /* #17: @12 = 1 */
  w12 = 1.;
  /* #18: @13 = input[0][1] */
  w13 = arg[0] ? arg[0][1] : 0;
  /* #19: @14 = input[0][0] */
  w14 = arg[0] ? arg[0][0] : 0;
  /* #20: @15 = kapparef_s(@14) */
  arg1[0]=(&w14);
  res1[0]=(&w15);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #21: @16 = (@13*@15) */
  w16  = (w13*w15);
  /* #22: @12 = (@12-@16) */
  w12 -= w16;
  /* #23: @9 = (@9/@12) */
  w9 /= w12;
  /* #24: @16 = (@6*@9) */
  w16  = (w6*w9);
  /* #25: @17 = 1 */
  w17 = 1.;
  /* #26: @17 = (@17-@6) */
  w17 -= w6;
  /* #27: @18 = cos(@7) */
  w18 = cos( w7 );
  /* #28: @19 = (@1*@18) */
  w19  = (w1*w18);
  /* #29: @20 = sin(@7) */
  w20 = sin( w7 );
  /* #30: @21 = (@10*@20) */
  w21  = (w10*w20);
  /* #31: @19 = (@19-@21) */
  w19 -= w21;
  /* #32: @21 = 1 */
  w21 = 1.;
  /* #33: @22 = kapparef_s(@14) */
  arg1[0]=(&w14);
  res1[0]=(&w22);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #34: @23 = (@13*@22) */
  w23  = (w13*w22);
  /* #35: @21 = (@21-@23) */
  w21 -= w23;
  /* #36: @19 = (@19/@21) */
  w19 /= w21;
  /* #37: @23 = (@17*@19) */
  w23  = (w17*w19);
  /* #38: @16 = (@16+@23) */
  w16 += w23;
  /* #39: @23 = 3 */
  w23 = 3.;
  /* #40: @23 = (@1-@23) */
  w23  = (w1-w23);
  /* #41: @24 = 2 */
  w24 = 2.;
  /* #42: @23 = (@23/@24) */
  w23 /= w24;
  /* #43: @24 = 0 */
  w24 = 0.;
  /* #44: @25 = fmax(@23,@24) */
  w25  = casadi_fmax(w23,w24);
  /* #45: @26 = 1 */
  w26 = 1.;
  /* #46: @27 = fmin(@25,@26) */
  w27  = casadi_fmin(w25,w26);
  /* #47: @28 = sin(@7) */
  w28 = sin( w7 );
  /* #48: @29 = (@1*@28) */
  w29  = (w1*w28);
  /* #49: @30 = cos(@7) */
  w30 = cos( w7 );
  /* #50: @31 = (@10*@30) */
  w31  = (w10*w30);
  /* #51: @29 = (@29+@31) */
  w29 += w31;
  /* #52: @31 = (@27*@29) */
  w31  = (w27*w29);
  /* #53: @32 = 1 */
  w32 = 1.;
  /* #54: @32 = (@32-@27) */
  w32 -= w27;
  /* #55: @33 = sin(@7) */
  w33 = sin( w7 );
  /* #56: @34 = (@1*@33) */
  w34  = (w1*w33);
  /* #57: @35 = cos(@7) */
  w35 = cos( w7 );
  /* #58: @36 = (@10*@35) */
  w36  = (w10*w35);
  /* #59: @34 = (@34+@36) */
  w34 += w36;
  /* #60: @36 = (@32*@34) */
  w36  = (w32*w34);
  /* #61: @31 = (@31+@36) */
  w31 += w36;
  /* #62: @36 = 3 */
  w36 = 3.;
  /* #63: @36 = (@1-@36) */
  w36  = (w1-w36);
  /* #64: @37 = 2 */
  w37 = 2.;
  /* #65: @36 = (@36/@37) */
  w36 /= w37;
  /* #66: @37 = 0 */
  w37 = 0.;
  /* #67: @38 = fmax(@36,@37) */
  w38  = casadi_fmax(w36,w37);
  /* #68: @39 = 1 */
  w39 = 1.;
  /* #69: @40 = fmin(@38,@39) */
  w40  = casadi_fmin(w38,w39);
  /* #70: @41 = input[0][5] */
  w41 = arg[0] ? arg[0][5] : 0;
  /* #71: @42 = kapparef_s(@14) */
  arg1[0]=(&w14);
  res1[0]=(&w42);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #72: @43 = (@13*@42) */
  w43  = (w13*w42);
  /* #73: @44 = cos(@7) */
  w44 = cos( w7 );
  /* #74: @45 = (@1*@44) */
  w45  = (w1*w44);
  /* #75: @46 = sin(@7) */
  w46 = sin( w7 );
  /* #76: @47 = (@10*@46) */
  w47  = (w10*w46);
  /* #77: @45 = (@45-@47) */
  w45 -= w47;
  /* #78: @47 = (@43*@45) */
  w47  = (w43*w45);
  /* #79: @48 = 1 */
  w48 = 1.;
  /* #80: @49 = kapparef_s(@14) */
  arg1[0]=(&w14);
  res1[0]=(&w49);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #81: @50 = (@13*@49) */
  w50  = (w13*w49);
  /* #82: @48 = (@48-@50) */
  w48 -= w50;
  /* #83: @47 = (@47/@48) */
  w47 /= w48;
  /* #84: @50 = (@41-@47) */
  w50  = (w41-w47);
  /* #85: @51 = (@40*@50) */
  w51  = (w40*w50);
  /* #86: @52 = 1 */
  w52 = 1.;
  /* #87: @52 = (@52-@40) */
  w52 -= w40;
  /* #88: @53 = kapparef_s(@14) */
  arg1[0]=(&w14);
  res1[0]=(&w53);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #89: @54 = (@13*@53) */
  w54  = (w13*w53);
  /* #90: @55 = cos(@7) */
  w55 = cos( w7 );
  /* #91: @56 = (@1*@55) */
  w56  = (w1*w55);
  /* #92: @57 = sin(@7) */
  w57 = sin( w7 );
  /* #93: @58 = (@10*@57) */
  w58  = (w10*w57);
  /* #94: @56 = (@56-@58) */
  w56 -= w58;
  /* #95: @58 = (@54*@56) */
  w58  = (w54*w56);
  /* #96: @59 = 1 */
  w59 = 1.;
  /* #97: @60 = kapparef_s(@14) */
  arg1[0]=(&w14);
  res1[0]=(&w60);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #98: @61 = (@13*@60) */
  w61  = (w13*w60);
  /* #99: @59 = (@59-@61) */
  w59 -= w61;
  /* #100: @58 = (@58/@59) */
  w58 /= w59;
  /* #101: @61 = (@41-@58) */
  w61  = (w41-w58);
  /* #102: @62 = (@52*@61) */
  w62  = (w52*w61);
  /* #103: @51 = (@51+@62) */
  w51 += w62;
  /* #104: @62 = 3 */
  w62 = 3.;
  /* #105: @62 = (@1-@62) */
  w62  = (w1-w62);
  /* #106: @63 = 2 */
  w63 = 2.;
  /* #107: @62 = (@62/@63) */
  w62 /= w63;
  /* #108: @63 = 0 */
  w63 = 0.;
  /* #109: @64 = fmax(@62,@63) */
  w64  = casadi_fmax(w62,w63);
  /* #110: @65 = 1 */
  w65 = 1.;
  /* #111: @66 = fmin(@64,@65) */
  w66  = casadi_fmin(w64,w65);
  /* #112: @67 = input[2][0] */
  w67 = arg[2] ? arg[2][0] : 0;
  /* #113: @68 = 0.0005 */
  w68 = 5.0000000000000001e-04;
  /* #114: @69 = 92731.3 */
  w69 = 9.2731265615302604e+04;
  /* #115: @70 = input[0][6] */
  w70 = arg[0] ? arg[0][6] : 0;
  /* #116: @71 = 1.4 */
  w71 = 1.3999999999999999e+00;
  /* #117: @72 = (@71*@41) */
  w72  = (w71*w41);
  /* #118: @72 = (@10+@72) */
  w72  = (w10+w72);
  /* #119: @72 = (@72/@1) */
  w72 /= w1;
  /* #120: @73 = (@70-@72) */
  w73  = (w70-w72);
  /* #121: @73 = (@69*@73) */
  w73  = (w69*w73);
  /* #122: @73 = (@68*@73) */
  w73  = (w68*w73);
  /* #123: @74 = sin(@70) */
  w74 = sin( w70 );
  /* #124: @75 = (@73*@74) */
  w75  = (w73*w74);
  /* #125: @75 = (@67-@75) */
  w75  = (w67-w75);
  /* #126: @76 = (@10*@41) */
  w76  = (w10*w41);
  /* #127: @75 = (@75+@76) */
  w75 += w76;
  /* #128: @76 = (@66*@75) */
  w76  = (w66*w75);
  /* #129: @77 = 1 */
  w77 = 1.;
  /* #130: @77 = (@77-@66) */
  w77 -= w66;
  /* #131: @77 = (@77*@67) */
  w77 *= w67;
  /* #132: @76 = (@76+@77) */
  w76 += w77;
  /* #133: @77 = 3 */
  w77 = 3.;
  /* #134: @77 = (@1-@77) */
  w77  = (w1-w77);
  /* #135: @78 = 2 */
  w78 = 2.;
  /* #136: @77 = (@77/@78) */
  w77 /= w78;
  /* #137: @78 = 0 */
  w78 = 0.;
  /* #138: @79 = fmax(@77,@78) */
  w79  = casadi_fmax(w77,w78);
  /* #139: @80 = 1 */
  w80 = 1.;
  /* #140: @81 = fmin(@79,@80) */
  w81  = casadi_fmin(w79,w80);
  /* #141: @82 = 0.0005 */
  w82 = 5.0000000000000001e-04;
  /* #142: @83 = 92731.3 */
  w83 = 9.2731265615302604e+04;
  /* #143: @84 = 1.4 */
  w84 = 1.3999999999999999e+00;
  /* #144: @85 = (@84*@41) */
  w85  = (w84*w41);
  /* #145: @85 = (@85-@10) */
  w85 -= w10;
  /* #146: @85 = (@83*@85) */
  w85  = (w83*w85);
  /* #147: @85 = (@85/@1) */
  w85 /= w1;
  /* #148: @86 = 92731.3 */
  w86 = 9.2731265615302604e+04;
  /* #149: @87 = 1.4 */
  w87 = 1.3999999999999999e+00;
  /* #150: @88 = (@87*@41) */
  w88  = (w87*w41);
  /* #151: @88 = (@10+@88) */
  w88  = (w10+w88);
  /* #152: @88 = (@88/@1) */
  w88 /= w1;
  /* #153: @89 = (@70-@88) */
  w89  = (w70-w88);
  /* #154: @89 = (@86*@89) */
  w89  = (w86*w89);
  /* #155: @90 = cos(@70) */
  w90 = cos( w70 );
  /* #156: @91 = (@89*@90) */
  w91  = (w89*w90);
  /* #157: @91 = (@85+@91) */
  w91  = (w85+w91);
  /* #158: @91 = (@82*@91) */
  w91  = (w82*w91);
  /* #159: @92 = (@1*@41) */
  w92  = (w1*w41);
  /* #160: @91 = (@91-@92) */
  w91 -= w92;
  /* #161: @92 = (@81*@91) */
  w92  = (w81*w91);
  /* #162: @93 = 1 */
  w93 = 1.;
  /* #163: @93 = (@93-@81) */
  w93 -= w81;
  /* #164: @94 = 1.4 */
  w94 = 1.3999999999999999e+00;
  /* #165: @95 = input[2][1] */
  w95 = arg[2] ? arg[2][1] : 0;
  /* #166: @96 = (@95*@1) */
  w96  = (w95*w1);
  /* #167: @97 = (@70*@67) */
  w97  = (w70*w67);
  /* #168: @96 = (@96+@97) */
  w96 += w97;
  /* #169: @96 = (@94*@96) */
  w96  = (w94*w96);
  /* #170: @97 = 2.8 */
  w97 = 2.7999999999999998e+00;
  /* #171: @96 = (@96/@97) */
  w96 /= w97;
  /* #172: @97 = (@93*@96) */
  w97  = (w93*w96);
  /* #173: @92 = (@92+@97) */
  w92 += w97;
  /* #174: @97 = 3 */
  w97 = 3.;
  /* #175: @97 = (@1-@97) */
  w97  = (w1-w97);
  /* #176: @98 = 2 */
  w98 = 2.;
  /* #177: @97 = (@97/@98) */
  w97 /= w98;
  /* #178: @98 = 0 */
  w98 = 0.;
  /* #179: @99 = fmax(@97,@98) */
  w99  = casadi_fmax(w97,w98);
  /* #180: @100 = 1 */
  w100 = 1.;
  /* #181: @101 = fmin(@99,@100) */
  w101  = casadi_fmin(w99,w100);
  /* #182: @102 = 0.000255102 */
  w102 = 2.5510204081632655e-04;
  /* #183: @103 = 1.4 */
  w103 = 1.3999999999999999e+00;
  /* #184: @104 = 92731.3 */
  w104 = 9.2731265615302604e+04;
  /* #185: @105 = 1.4 */
  w105 = 1.3999999999999999e+00;
  /* #186: @106 = (@105*@41) */
  w106  = (w105*w41);
  /* #187: @106 = (@10+@106) */
  w106  = (w10+w106);
  /* #188: @106 = (@106/@1) */
  w106 /= w1;
  /* #189: @107 = (@70-@106) */
  w107  = (w70-w106);
  /* #190: @107 = (@104*@107) */
  w107  = (w104*w107);
  /* #191: @107 = (@103*@107) */
  w107  = (w103*w107);
  /* #192: @108 = cos(@70) */
  w108 = cos( w70 );
  /* #193: @109 = (@107*@108) */
  w109  = (w107*w108);
  /* #194: @110 = 1.4 */
  w110 = 1.3999999999999999e+00;
  /* #195: @111 = 92731.3 */
  w111 = 9.2731265615302604e+04;
  /* #196: @112 = 1.4 */
  w112 = 1.3999999999999999e+00;
  /* #197: @113 = (@112*@41) */
  w113  = (w112*w41);
  /* #198: @113 = (@113-@10) */
  w113 -= w10;
  /* #199: @113 = (@111*@113) */
  w113  = (w111*w113);
  /* #200: @113 = (@113/@1) */
  w113 /= w1;
  /* #201: @114 = (@110*@113) */
  w114  = (w110*w113);
  /* #202: @109 = (@109-@114) */
  w109 -= w114;
  /* #203: @109 = (@102*@109) */
  w109  = (w102*w109);
  /* #204: @114 = (@101*@109) */
  w114  = (w101*w109);
  /* #205: @115 = 1 */
  w115 = 1.;
  /* #206: @115 = (@115-@101) */
  w115 -= w101;
  /* #207: @116 = (@95*@1) */
  w116  = (w95*w1);
  /* #208: @117 = (@70*@67) */
  w117  = (w70*w67);
  /* #209: @116 = (@116+@117) */
  w116 += w117;
  /* #210: @117 = 2.8 */
  w117 = 2.7999999999999998e+00;
  /* #211: @116 = (@116/@117) */
  w116 /= w117;
  /* #212: @117 = (@115*@116) */
  w117  = (w115*w116);
  /* #213: @114 = (@114+@117) */
  w114 += w117;
  /* #214: @118 = vertcat(@16, @31, @51, @76, @92, @114, @95) */
  rr=w118;
  *rr++ = w16;
  *rr++ = w31;
  *rr++ = w51;
  *rr++ = w76;
  *rr++ = w92;
  *rr++ = w114;
  *rr++ = w95;
  /* #215: @0 = (@0-@118) */
  for (i=0, rr=w0, cs=w118; i<7; ++i) (*rr++) -= (*cs++);
  /* #216: output[0][0] = @0 */
  casadi_copy(w0, 7, res[0]);
  /* #217: @119 = zeros(7x7,26nz) */
  casadi_clear(w119, 26);
  /* #218: @16 = (@9/@12) */
  w16  = (w9/w12);
  /* #219: @120 = 00 */
  /* #220: @121 = ones(7x1,2nz) */
  casadi_fill(w121, 2, 1.);
  /* #221: {@31, NULL, NULL, NULL, NULL, NULL, @51} = vertsplit(@121) */
  w31 = w121[0];
  w51 = w121[1];
  /* #222: @76 = fwd1_kapparef_s(@14, @120, @31) */
  arg1[0]=(&w14);
  arg1[1]=0;
  arg1[2]=(&w31);
  res1[0]=(&w76);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #223: @76 = (@13*@76) */
  w76  = (w13*w76);
  /* #224: @76 = (@16*@76) */
  w76  = (w16*w76);
  /* #225: @76 = (@6*@76) */
  w76  = (w6*w76);
  /* #226: @92 = (@19/@21) */
  w92  = (w19/w21);
  /* #227: @120 = 00 */
  /* #228: @114 = fwd1_kapparef_s(@14, @120, @31) */
  arg1[0]=(&w14);
  arg1[1]=0;
  arg1[2]=(&w31);
  res1[0]=(&w114);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #229: @114 = (@13*@114) */
  w114  = (w13*w114);
  /* #230: @114 = (@92*@114) */
  w114  = (w92*w114);
  /* #231: @114 = (@17*@114) */
  w114  = (w17*w114);
  /* #232: @76 = (@76+@114) */
  w76 += w114;
  /* #233: @120 = 00 */
  /* #234: @122 = 00 */
  /* #235: @114 = fwd1_kapparef_s(@14, @122, @31) */
  arg1[0]=(&w14);
  arg1[1]=0;
  arg1[2]=(&w31);
  res1[0]=(&w114);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #236: @114 = (@13*@114) */
  w114  = (w13*w114);
  /* #237: @114 = (@56*@114) */
  w114  = (w56*w114);
  /* #238: @114 = (@114/@59) */
  w114 /= w59;
  /* #239: @58 = (@58/@59) */
  w58 /= w59;
  /* #240: @122 = 00 */
  /* #241: @117 = fwd1_kapparef_s(@14, @122, @31) */
  arg1[0]=(&w14);
  arg1[1]=0;
  arg1[2]=(&w31);
  res1[0]=(&w117);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #242: @117 = (@13*@117) */
  w117  = (w13*w117);
  /* #243: @117 = (@58*@117) */
  w117  = (w58*w117);
  /* #244: @114 = (@114+@117) */
  w114 += w117;
  /* #245: @114 = (@52*@114) */
  w114  = (w52*w114);
  /* #246: @114 = (-@114) */
  w114 = (- w114 );
  /* #247: @122 = 00 */
  /* #248: @117 = fwd1_kapparef_s(@14, @122, @31) */
  arg1[0]=(&w14);
  arg1[1]=0;
  arg1[2]=(&w31);
  res1[0]=(&w117);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #249: @117 = (@13*@117) */
  w117  = (w13*w117);
  /* #250: @117 = (@45*@117) */
  w117  = (w45*w117);
  /* #251: @117 = (@117/@48) */
  w117 /= w48;
  /* #252: @47 = (@47/@48) */
  w47 /= w48;
  /* #253: @122 = 00 */
  /* #254: @123 = fwd1_kapparef_s(@14, @122, @31) */
  arg1[0]=(&w14);
  arg1[1]=0;
  arg1[2]=(&w31);
  res1[0]=(&w123);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #255: @13 = (@13*@123) */
  w13 *= w123;
  /* #256: @13 = (@47*@13) */
  w13  = (w47*w13);
  /* #257: @117 = (@117+@13) */
  w117 += w13;
  /* #258: @117 = (@40*@117) */
  w117  = (w40*w117);
  /* #259: @114 = (@114-@117) */
  w114 -= w117;
  /* #260: @117 = (@69*@51) */
  w117  = (w69*w51);
  /* #261: @117 = (@68*@117) */
  w117  = (w68*w117);
  /* #262: @117 = (@74*@117) */
  w117  = (w74*w117);
  /* #263: @13 = cos(@70) */
  w13 = cos( w70 );
  /* #264: @13 = (@13*@51) */
  w13 *= w51;
  /* #265: @73 = (@73*@13) */
  w73 *= w13;
  /* #266: @117 = (@117+@73) */
  w117 += w73;
  /* #267: @117 = (@66*@117) */
  w117  = (w66*w117);
  /* #268: @117 = (-@117) */
  w117 = (- w117 );
  /* #269: @73 = (@86*@51) */
  w73  = (w86*w51);
  /* #270: @73 = (@90*@73) */
  w73  = (w90*w73);
  /* #271: @13 = sin(@70) */
  w13 = sin( w70 );
  /* #272: @13 = (@13*@51) */
  w13 *= w51;
  /* #273: @89 = (@89*@13) */
  w89 *= w13;
  /* #274: @73 = (@73-@89) */
  w73 -= w89;
  /* #275: @73 = (@82*@73) */
  w73  = (w82*w73);
  /* #276: @73 = (@81*@73) */
  w73  = (w81*w73);
  /* #277: @89 = 0.357143 */
  w89 = 3.5714285714285715e-01;
  /* #278: @13 = (@67*@51) */
  w13  = (w67*w51);
  /* #279: @13 = (@94*@13) */
  w13  = (w94*w13);
  /* #280: @13 = (@89*@13) */
  w13  = (w89*w13);
  /* #281: @13 = (@93*@13) */
  w13  = (w93*w13);
  /* #282: @73 = (@73+@13) */
  w73 += w13;
  /* #283: @13 = (@104*@51) */
  w13  = (w104*w51);
  /* #284: @13 = (@103*@13) */
  w13  = (w103*w13);
  /* #285: @13 = (@108*@13) */
  w13  = (w108*w13);
  /* #286: @70 = sin(@70) */
  w70 = sin( w70 );
  /* #287: @70 = (@70*@51) */
  w70 *= w51;
  /* #288: @107 = (@107*@70) */
  w107 *= w70;
  /* #289: @13 = (@13-@107) */
  w13 -= w107;
  /* #290: @13 = (@102*@13) */
  w13  = (w102*w13);
  /* #291: @13 = (@101*@13) */
  w13  = (w101*w13);
  /* #292: @107 = 0.357143 */
  w107 = 3.5714285714285715e-01;
  /* #293: @51 = (@67*@51) */
  w51  = (w67*w51);
  /* #294: @51 = (@107*@51) */
  w51  = (w107*w51);
  /* #295: @51 = (@115*@51) */
  w51  = (w115*w51);
  /* #296: @13 = (@13+@51) */
  w13 += w51;
  /* #297: @122 = 00 */
  /* #298: @124 = vertcat(@76, @120, @114, @117, @73, @13, @122) */
  rr=w124;
  *rr++ = w76;
  *rr++ = w114;
  *rr++ = w117;
  *rr++ = w73;
  *rr++ = w13;
  /* #299: @124 = (-@124) */
  for (i=0, rr=w124, cs=w124; i<5; ++i) *rr++ = (- *cs++ );
  /* #300: @125 = @124[:5] */
  for (rr=w125, ss=w124+0; ss!=w124+5; ss+=1) *rr++ = *ss;
  /* #301: (@119[0, 8, 17, 21, 25] = @125) */
  for (cii=casadi_s6, rr=w119, ss=w125; cii!=casadi_s6+5; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #302: @76 = ones(7x1,1nz) */
  w76 = 1.;
  /* #303: {NULL, @114, NULL, NULL, NULL, NULL, NULL} = vertsplit(@76) */
  w114 = w76;
  /* #304: @15 = (@15*@114) */
  w15 *= w114;
  /* #305: @16 = (@16*@15) */
  w16 *= w15;
  /* #306: @16 = (@6*@16) */
  w16  = (w6*w16);
  /* #307: @22 = (@22*@114) */
  w22 *= w114;
  /* #308: @92 = (@92*@22) */
  w92 *= w22;
  /* #309: @92 = (@17*@92) */
  w92  = (w17*w92);
  /* #310: @16 = (@16+@92) */
  w16 += w92;
  /* #311: @120 = 00 */
  /* #312: @53 = (@53*@114) */
  w53 *= w114;
  /* #313: @56 = (@56*@53) */
  w56 *= w53;
  /* #314: @56 = (@56/@59) */
  w56 /= w59;
  /* #315: @60 = (@60*@114) */
  w60 *= w114;
  /* #316: @58 = (@58*@60) */
  w58 *= w60;
  /* #317: @56 = (@56+@58) */
  w56 += w58;
  /* #318: @56 = (@52*@56) */
  w56  = (w52*w56);
  /* #319: @56 = (-@56) */
  w56 = (- w56 );
  /* #320: @42 = (@42*@114) */
  w42 *= w114;
  /* #321: @45 = (@45*@42) */
  w45 *= w42;
  /* #322: @45 = (@45/@48) */
  w45 /= w48;
  /* #323: @49 = (@49*@114) */
  w49 *= w114;
  /* #324: @47 = (@47*@49) */
  w47 *= w49;
  /* #325: @45 = (@45+@47) */
  w45 += w47;
  /* #326: @45 = (@40*@45) */
  w45  = (w40*w45);
  /* #327: @56 = (@56-@45) */
  w56 -= w45;
  /* #328: @122 = 00 */
  /* #329: @126 = 00 */
  /* #330: @127 = 00 */
  /* #331: @128 = 00 */
  /* #332: @121 = vertcat(@16, @120, @56, @122, @126, @127, @128) */
  rr=w121;
  *rr++ = w16;
  *rr++ = w56;
  /* #333: @121 = (-@121) */
  for (i=0, rr=w121, cs=w121; i<2; ++i) *rr++ = (- *cs++ );
  /* #334: @129 = @121[:2] */
  for (rr=w129, ss=w121+0; ss!=w121+2; ss+=1) *rr++ = *ss;
  /* #335: (@119[1:17:8] = @129) */
  for (rr=w119+1, ss=w129; rr!=w119+17; rr+=8) *rr = *ss++;
  /* #336: @16 = cos(@7) */
  w16 = cos( w7 );
  /* #337: @56 = ones(7x1,1nz) */
  w56 = 1.;
  /* #338: {NULL, NULL, @45, NULL, NULL, NULL, NULL} = vertsplit(@56) */
  w45 = w56;
  /* #339: @16 = (@16*@45) */
  w16 *= w45;
  /* #340: @16 = (@10*@16) */
  w16  = (w10*w16);
  /* #341: @16 = (-@16) */
  w16 = (- w16 );
  /* #342: @56 = sin(@7) */
  w56 = sin( w7 );
  /* #343: @56 = (@56*@45) */
  w56 *= w45;
  /* #344: @56 = (@1*@56) */
  w56  = (w1*w56);
  /* #345: @16 = (@16-@56) */
  w16 -= w56;
  /* #346: @16 = (@16/@12) */
  w16 /= w12;
  /* #347: @16 = (@6*@16) */
  w16  = (w6*w16);
  /* #348: @56 = cos(@7) */
  w56 = cos( w7 );
  /* #349: @56 = (@56*@45) */
  w56 *= w45;
  /* #350: @56 = (@10*@56) */
  w56  = (w10*w56);
  /* #351: @56 = (-@56) */
  w56 = (- w56 );
  /* #352: @47 = sin(@7) */
  w47 = sin( w7 );
  /* #353: @47 = (@47*@45) */
  w47 *= w45;
  /* #354: @47 = (@1*@47) */
  w47  = (w1*w47);
  /* #355: @56 = (@56-@47) */
  w56 -= w47;
  /* #356: @56 = (@56/@21) */
  w56 /= w21;
  /* #357: @56 = (@17*@56) */
  w56  = (w17*w56);
  /* #358: @16 = (@16+@56) */
  w16 += w56;
  /* #359: @56 = cos(@7) */
  w56 = cos( w7 );
  /* #360: @56 = (@56*@45) */
  w56 *= w45;
  /* #361: @56 = (@1*@56) */
  w56  = (w1*w56);
  /* #362: @47 = sin(@7) */
  w47 = sin( w7 );
  /* #363: @47 = (@47*@45) */
  w47 *= w45;
  /* #364: @47 = (@10*@47) */
  w47  = (w10*w47);
  /* #365: @56 = (@56-@47) */
  w56 -= w47;
  /* #366: @56 = (@27*@56) */
  w56  = (w27*w56);
  /* #367: @47 = cos(@7) */
  w47 = cos( w7 );
  /* #368: @47 = (@47*@45) */
  w47 *= w45;
  /* #369: @47 = (@1*@47) */
  w47  = (w1*w47);
  /* #370: @49 = sin(@7) */
  w49 = sin( w7 );
  /* #371: @49 = (@49*@45) */
  w49 *= w45;
  /* #372: @49 = (@10*@49) */
  w49  = (w10*w49);
  /* #373: @47 = (@47-@49) */
  w47 -= w49;
  /* #374: @47 = (@32*@47) */
  w47  = (w32*w47);
  /* #375: @56 = (@56+@47) */
  w56 += w47;
  /* #376: @47 = cos(@7) */
  w47 = cos( w7 );
  /* #377: @47 = (@47*@45) */
  w47 *= w45;
  /* #378: @47 = (@10*@47) */
  w47  = (w10*w47);
  /* #379: @47 = (-@47) */
  w47 = (- w47 );
  /* #380: @49 = sin(@7) */
  w49 = sin( w7 );
  /* #381: @49 = (@49*@45) */
  w49 *= w45;
  /* #382: @49 = (@1*@49) */
  w49  = (w1*w49);
  /* #383: @47 = (@47-@49) */
  w47 -= w49;
  /* #384: @47 = (@54*@47) */
  w47  = (w54*w47);
  /* #385: @47 = (@47/@59) */
  w47 /= w59;
  /* #386: @47 = (@52*@47) */
  w47  = (w52*w47);
  /* #387: @47 = (-@47) */
  w47 = (- w47 );
  /* #388: @49 = cos(@7) */
  w49 = cos( w7 );
  /* #389: @49 = (@49*@45) */
  w49 *= w45;
  /* #390: @49 = (@10*@49) */
  w49  = (w10*w49);
  /* #391: @49 = (-@49) */
  w49 = (- w49 );
  /* #392: @7 = sin(@7) */
  w7 = sin( w7 );
  /* #393: @7 = (@7*@45) */
  w7 *= w45;
  /* #394: @7 = (@1*@7) */
  w7  = (w1*w7);
  /* #395: @49 = (@49-@7) */
  w49 -= w7;
  /* #396: @49 = (@43*@49) */
  w49  = (w43*w49);
  /* #397: @49 = (@49/@48) */
  w49 /= w48;
  /* #398: @49 = (@40*@49) */
  w49  = (w40*w49);
  /* #399: @47 = (@47-@49) */
  w47 -= w49;
  /* #400: @120 = 00 */
  /* #401: @122 = 00 */
  /* #402: @126 = 00 */
  /* #403: @127 = 00 */
  /* #404: @130 = vertcat(@16, @56, @47, @120, @122, @126, @127) */
  rr=w130;
  *rr++ = w16;
  *rr++ = w56;
  *rr++ = w47;
  /* #405: @130 = (-@130) */
  for (i=0, rr=w130, cs=w130; i<3; ++i) *rr++ = (- *cs++ );
  /* #406: @131 = @130[:3] */
  for (rr=w131, ss=w130+0; ss!=w130+3; ss+=1) *rr++ = *ss;
  /* #407: (@119[2, 5, 10] = @131) */
  for (cii=casadi_s7, rr=w119, ss=w131; cii!=casadi_s7+3; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #408: @4 = (@4<=@5) */
  w4  = (w4<=w5);
  /* #409: @3 = (@3<=@2) */
  w3  = (w3<=w2);
  /* #410: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #411: @5 = ones(7x1,1nz) */
  w5 = 1.;
  /* #412: {NULL, NULL, NULL, @16, NULL, NULL, NULL} = vertsplit(@5) */
  w16 = w5;
  /* #413: @2 = (@2*@16) */
  w2 *= w16;
  /* #414: @3 = (@3*@2) */
  w3 *= w2;
  /* #415: @4 = (@4*@3) */
  w4 *= w3;
  /* #416: @9 = (@9*@4) */
  w9 *= w4;
  /* #417: @8 = (@8*@16) */
  w8 *= w16;
  /* #418: @8 = (@8/@12) */
  w8 /= w12;
  /* #419: @8 = (@6*@8) */
  w8  = (w6*w8);
  /* #420: @9 = (@9+@8) */
  w9 += w8;
  /* #421: @18 = (@18*@16) */
  w18 *= w16;
  /* #422: @18 = (@18/@21) */
  w18 /= w21;
  /* #423: @18 = (@17*@18) */
  w18  = (w17*w18);
  /* #424: @19 = (@19*@4) */
  w19 *= w4;
  /* #425: @18 = (@18-@19) */
  w18 -= w19;
  /* #426: @9 = (@9+@18) */
  w9 += w18;
  /* #427: @25 = (@25<=@26) */
  w25  = (w25<=w26);
  /* #428: @24 = (@24<=@23) */
  w24  = (w24<=w23);
  /* #429: @23 = 0.5 */
  w23 = 5.0000000000000000e-01;
  /* #430: @23 = (@23*@16) */
  w23 *= w16;
  /* #431: @24 = (@24*@23) */
  w24 *= w23;
  /* #432: @25 = (@25*@24) */
  w25 *= w24;
  /* #433: @29 = (@29*@25) */
  w29 *= w25;
  /* #434: @28 = (@28*@16) */
  w28 *= w16;
  /* #435: @28 = (@27*@28) */
  w28  = (w27*w28);
  /* #436: @29 = (@29+@28) */
  w29 += w28;
  /* #437: @33 = (@33*@16) */
  w33 *= w16;
  /* #438: @33 = (@32*@33) */
  w33  = (w32*w33);
  /* #439: @34 = (@34*@25) */
  w34 *= w25;
  /* #440: @33 = (@33-@34) */
  w33 -= w34;
  /* #441: @29 = (@29+@33) */
  w29 += w33;
  /* #442: @38 = (@38<=@39) */
  w38  = (w38<=w39);
  /* #443: @37 = (@37<=@36) */
  w37  = (w37<=w36);
  /* #444: @36 = 0.5 */
  w36 = 5.0000000000000000e-01;
  /* #445: @36 = (@36*@16) */
  w36 *= w16;
  /* #446: @37 = (@37*@36) */
  w37 *= w36;
  /* #447: @38 = (@38*@37) */
  w38 *= w37;
  /* #448: @50 = (@50*@38) */
  w50 *= w38;
  /* #449: @44 = (@44*@16) */
  w44 *= w16;
  /* #450: @44 = (@43*@44) */
  w44  = (w43*w44);
  /* #451: @44 = (@44/@48) */
  w44 /= w48;
  /* #452: @44 = (@40*@44) */
  w44  = (w40*w44);
  /* #453: @50 = (@50-@44) */
  w50 -= w44;
  /* #454: @55 = (@55*@16) */
  w55 *= w16;
  /* #455: @55 = (@54*@55) */
  w55  = (w54*w55);
  /* #456: @55 = (@55/@59) */
  w55 /= w59;
  /* #457: @55 = (@52*@55) */
  w55  = (w52*w55);
  /* #458: @55 = (-@55) */
  w55 = (- w55 );
  /* #459: @61 = (@61*@38) */
  w61 *= w38;
  /* #460: @55 = (@55-@61) */
  w55 -= w61;
  /* #461: @50 = (@50+@55) */
  w50 += w55;
  /* #462: @64 = (@64<=@65) */
  w64  = (w64<=w65);
  /* #463: @63 = (@63<=@62) */
  w63  = (w63<=w62);
  /* #464: @62 = 0.5 */
  w62 = 5.0000000000000000e-01;
  /* #465: @62 = (@62*@16) */
  w62 *= w16;
  /* #466: @63 = (@63*@62) */
  w63 *= w62;
  /* #467: @64 = (@64*@63) */
  w64 *= w63;
  /* #468: @75 = (@75*@64) */
  w75 *= w64;
  /* #469: @72 = (@72/@1) */
  w72 /= w1;
  /* #470: @72 = (@72*@16) */
  w72 *= w16;
  /* #471: @72 = (@69*@72) */
  w72  = (w69*w72);
  /* #472: @72 = (@68*@72) */
  w72  = (w68*w72);
  /* #473: @72 = (@74*@72) */
  w72  = (w74*w72);
  /* #474: @72 = (@66*@72) */
  w72  = (w66*w72);
  /* #475: @75 = (@75-@72) */
  w75 -= w72;
  /* #476: @67 = (@67*@64) */
  w67 *= w64;
  /* #477: @75 = (@75-@67) */
  w75 -= w67;
  /* #478: @79 = (@79<=@80) */
  w79  = (w79<=w80);
  /* #479: @78 = (@78<=@77) */
  w78  = (w78<=w77);
  /* #480: @77 = 0.5 */
  w77 = 5.0000000000000000e-01;
  /* #481: @77 = (@77*@16) */
  w77 *= w16;
  /* #482: @78 = (@78*@77) */
  w78 *= w77;
  /* #483: @79 = (@79*@78) */
  w79 *= w78;
  /* #484: @91 = (@91*@79) */
  w91 *= w79;
  /* #485: @88 = (@88/@1) */
  w88 /= w1;
  /* #486: @88 = (@88*@16) */
  w88 *= w16;
  /* #487: @88 = (@86*@88) */
  w88  = (w86*w88);
  /* #488: @88 = (@90*@88) */
  w88  = (w90*w88);
  /* #489: @85 = (@85/@1) */
  w85 /= w1;
  /* #490: @85 = (@85*@16) */
  w85 *= w16;
  /* #491: @88 = (@88-@85) */
  w88 -= w85;
  /* #492: @88 = (@82*@88) */
  w88  = (w82*w88);
  /* #493: @85 = (@41*@16) */
  w85  = (w41*w16);
  /* #494: @88 = (@88-@85) */
  w88 -= w85;
  /* #495: @88 = (@81*@88) */
  w88  = (w81*w88);
  /* #496: @91 = (@91+@88) */
  w91 += w88;
  /* #497: @88 = (@95*@16) */
  w88  = (w95*w16);
  /* #498: @94 = (@94*@88) */
  w94 *= w88;
  /* #499: @89 = (@89*@94) */
  w89 *= w94;
  /* #500: @93 = (@93*@89) */
  w93 *= w89;
  /* #501: @96 = (@96*@79) */
  w96 *= w79;
  /* #502: @93 = (@93-@96) */
  w93 -= w96;
  /* #503: @91 = (@91+@93) */
  w91 += w93;
  /* #504: @99 = (@99<=@100) */
  w99  = (w99<=w100);
  /* #505: @98 = (@98<=@97) */
  w98  = (w98<=w97);
  /* #506: @97 = 0.5 */
  w97 = 5.0000000000000000e-01;
  /* #507: @97 = (@97*@16) */
  w97 *= w16;
  /* #508: @98 = (@98*@97) */
  w98 *= w97;
  /* #509: @99 = (@99*@98) */
  w99 *= w98;
  /* #510: @109 = (@109*@99) */
  w109 *= w99;
  /* #511: @106 = (@106/@1) */
  w106 /= w1;
  /* #512: @106 = (@106*@16) */
  w106 *= w16;
  /* #513: @106 = (@104*@106) */
  w106  = (w104*w106);
  /* #514: @106 = (@103*@106) */
  w106  = (w103*w106);
  /* #515: @106 = (@108*@106) */
  w106  = (w108*w106);
  /* #516: @113 = (@113/@1) */
  w113 /= w1;
  /* #517: @113 = (@113*@16) */
  w113 *= w16;
  /* #518: @113 = (@110*@113) */
  w113  = (w110*w113);
  /* #519: @106 = (@106+@113) */
  w106 += w113;
  /* #520: @106 = (@102*@106) */
  w106  = (w102*w106);
  /* #521: @106 = (@101*@106) */
  w106  = (w101*w106);
  /* #522: @109 = (@109+@106) */
  w109 += w106;
  /* #523: @95 = (@95*@16) */
  w95 *= w16;
  /* #524: @107 = (@107*@95) */
  w107 *= w95;
  /* #525: @115 = (@115*@107) */
  w115 *= w107;
  /* #526: @116 = (@116*@99) */
  w116 *= w99;
  /* #527: @115 = (@115-@116) */
  w115 -= w116;
  /* #528: @109 = (@109+@115) */
  w109 += w115;
  /* #529: @120 = 00 */
  /* #530: @132 = vertcat(@9, @29, @50, @75, @91, @109, @120) */
  rr=w132;
  *rr++ = w9;
  *rr++ = w29;
  *rr++ = w50;
  *rr++ = w75;
  *rr++ = w91;
  *rr++ = w109;
  /* #531: @132 = (-@132) */
  for (i=0, rr=w132, cs=w132; i<6; ++i) *rr++ = (- *cs++ );
  /* #532: @133 = @132[:6] */
  for (rr=w133, ss=w132+0; ss!=w132+6; ss+=1) *rr++ = *ss;
  /* #533: (@119[3, 6, 11, 14, 18, 22] = @133) */
  for (cii=casadi_s8, rr=w119, ss=w133; cii!=casadi_s8+6; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #534: @9 = ones(7x1,1nz) */
  w9 = 1.;
  /* #535: {NULL, NULL, NULL, NULL, @29, NULL, NULL} = vertsplit(@9) */
  w29 = w9;
  /* #536: @20 = (@20*@29) */
  w20 *= w29;
  /* #537: @20 = (@20/@21) */
  w20 /= w21;
  /* #538: @17 = (@17*@20) */
  w17 *= w20;
  /* #539: @17 = (-@17) */
  w17 = (- w17 );
  /* #540: @11 = (@11*@29) */
  w11 *= w29;
  /* #541: @11 = (@11/@12) */
  w11 /= w12;
  /* #542: @6 = (@6*@11) */
  w6 *= w11;
  /* #543: @17 = (@17-@6) */
  w17 -= w6;
  /* #544: @30 = (@30*@29) */
  w30 *= w29;
  /* #545: @27 = (@27*@30) */
  w27 *= w30;
  /* #546: @35 = (@35*@29) */
  w35 *= w29;
  /* #547: @32 = (@32*@35) */
  w32 *= w35;
  /* #548: @27 = (@27+@32) */
  w27 += w32;
  /* #549: @46 = (@46*@29) */
  w46 *= w29;
  /* #550: @43 = (@43*@46) */
  w43 *= w46;
  /* #551: @43 = (@43/@48) */
  w43 /= w48;
  /* #552: @43 = (@40*@43) */
  w43  = (w40*w43);
  /* #553: @57 = (@57*@29) */
  w57 *= w29;
  /* #554: @54 = (@54*@57) */
  w54 *= w57;
  /* #555: @54 = (@54/@59) */
  w54 /= w59;
  /* #556: @54 = (@52*@54) */
  w54  = (w52*w54);
  /* #557: @43 = (@43+@54) */
  w43 += w54;
  /* #558: @54 = (@29/@1) */
  w54  = (w29/w1);
  /* #559: @54 = (@69*@54) */
  w54  = (w69*w54);
  /* #560: @54 = (@68*@54) */
  w54  = (w68*w54);
  /* #561: @54 = (@74*@54) */
  w54  = (w74*w54);
  /* #562: @41 = (@41*@29) */
  w41 *= w29;
  /* #563: @54 = (@54+@41) */
  w54 += w41;
  /* #564: @54 = (@66*@54) */
  w54  = (w66*w54);
  /* #565: @41 = (@29/@1) */
  w41  = (w29/w1);
  /* #566: @41 = (@86*@41) */
  w41  = (w86*w41);
  /* #567: @41 = (@90*@41) */
  w41  = (w90*w41);
  /* #568: @41 = (-@41) */
  w41 = (- w41 );
  /* #569: @59 = (@83*@29) */
  w59  = (w83*w29);
  /* #570: @59 = (@59/@1) */
  w59 /= w1;
  /* #571: @41 = (@41-@59) */
  w41 -= w59;
  /* #572: @41 = (@82*@41) */
  w41  = (w82*w41);
  /* #573: @41 = (@81*@41) */
  w41  = (w81*w41);
  /* #574: @59 = (@111*@29) */
  w59  = (w111*w29);
  /* #575: @59 = (@59/@1) */
  w59 /= w1;
  /* #576: @59 = (@110*@59) */
  w59  = (w110*w59);
  /* #577: @29 = (@29/@1) */
  w29 /= w1;
  /* #578: @29 = (@104*@29) */
  w29  = (w104*w29);
  /* #579: @29 = (@103*@29) */
  w29  = (w103*w29);
  /* #580: @29 = (@108*@29) */
  w29  = (w108*w29);
  /* #581: @59 = (@59-@29) */
  w59 -= w29;
  /* #582: @59 = (@102*@59) */
  w59  = (w102*w59);
  /* #583: @59 = (@101*@59) */
  w59  = (w101*w59);
  /* #584: @120 = 00 */
  /* #585: @133 = vertcat(@17, @27, @43, @54, @41, @59, @120) */
  rr=w133;
  *rr++ = w17;
  *rr++ = w27;
  *rr++ = w43;
  *rr++ = w54;
  *rr++ = w41;
  *rr++ = w59;
  /* #586: @133 = (-@133) */
  for (i=0, rr=w133, cs=w133; i<6; ++i) *rr++ = (- *cs++ );
  /* #587: @132 = @133[:6] */
  for (rr=w132, ss=w133+0; ss!=w133+6; ss+=1) *rr++ = *ss;
  /* #588: (@119[4, 7, 12, 15, 19, 23] = @132) */
  for (cii=casadi_s9, rr=w119, ss=w132; cii!=casadi_s9+6; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #589: @120 = 00 */
  /* #590: @122 = 00 */
  /* #591: @17 = ones(7x1,1nz) */
  w17 = 1.;
  /* #592: {NULL, NULL, NULL, NULL, NULL, @27, NULL} = vertsplit(@17) */
  w27 = w17;
  /* #593: @40 = (@40*@27) */
  w40 *= w27;
  /* #594: @52 = (@52*@27) */
  w52 *= w27;
  /* #595: @40 = (@40+@52) */
  w40 += w52;
  /* #596: @71 = (@71*@27) */
  w71 *= w27;
  /* #597: @71 = (@71/@1) */
  w71 /= w1;
  /* #598: @69 = (@69*@71) */
  w69 *= w71;
  /* #599: @68 = (@68*@69) */
  w68 *= w69;
  /* #600: @74 = (@74*@68) */
  w74 *= w68;
  /* #601: @10 = (@10*@27) */
  w10 *= w27;
  /* #602: @74 = (@74+@10) */
  w74 += w10;
  /* #603: @66 = (@66*@74) */
  w66 *= w74;
  /* #604: @84 = (@84*@27) */
  w84 *= w27;
  /* #605: @83 = (@83*@84) */
  w83 *= w84;
  /* #606: @83 = (@83/@1) */
  w83 /= w1;
  /* #607: @87 = (@87*@27) */
  w87 *= w27;
  /* #608: @87 = (@87/@1) */
  w87 /= w1;
  /* #609: @86 = (@86*@87) */
  w86 *= w87;
  /* #610: @90 = (@90*@86) */
  w90 *= w86;
  /* #611: @83 = (@83-@90) */
  w83 -= w90;
  /* #612: @82 = (@82*@83) */
  w82 *= w83;
  /* #613: @83 = (@1*@27) */
  w83  = (w1*w27);
  /* #614: @82 = (@82-@83) */
  w82 -= w83;
  /* #615: @81 = (@81*@82) */
  w81 *= w82;
  /* #616: @112 = (@112*@27) */
  w112 *= w27;
  /* #617: @111 = (@111*@112) */
  w111 *= w112;
  /* #618: @111 = (@111/@1) */
  w111 /= w1;
  /* #619: @110 = (@110*@111) */
  w110 *= w111;
  /* #620: @110 = (-@110) */
  w110 = (- w110 );
  /* #621: @105 = (@105*@27) */
  w105 *= w27;
  /* #622: @105 = (@105/@1) */
  w105 /= w1;
  /* #623: @104 = (@104*@105) */
  w104 *= w105;
  /* #624: @103 = (@103*@104) */
  w103 *= w104;
  /* #625: @108 = (@108*@103) */
  w108 *= w103;
  /* #626: @110 = (@110-@108) */
  w110 -= w108;
  /* #627: @102 = (@102*@110) */
  w102 *= w110;
  /* #628: @101 = (@101*@102) */
  w101 *= w102;
  /* #629: @126 = 00 */
  /* #630: @134 = vertcat(@120, @122, @40, @66, @81, @101, @126) */
  rr=w134;
  *rr++ = w40;
  *rr++ = w66;
  *rr++ = w81;
  *rr++ = w101;
  /* #631: @134 = (-@134) */
  for (i=0, rr=w134, cs=w134; i<4; ++i) *rr++ = (- *cs++ );
  /* #632: @135 = @134[:4] */
  for (rr=w135, ss=w134+0; ss!=w134+4; ss+=1) *rr++ = *ss;
  /* #633: (@119[13, 16, 20, 24] = @135) */
  for (cii=casadi_s10, rr=w119, ss=w135; cii!=casadi_s10+4; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #634: @136 = @119' */
  casadi_trans(w119,casadi_s12, w136, casadi_s11, iw);
  /* #635: output[1][0] = @136 */
  casadi_copy(w136, 26, res[1]);
  /* #636: @0 = zeros(7x7,7nz) */
  casadi_clear(w0, 7);
  /* #637: @118 = ones(7x1) */
  casadi_fill(w118, 7, 1.);
  /* #638: (@0[:7] = @118) */
  for (rr=w0+0, ss=w118; rr!=w0+7; rr+=1) *rr = *ss++;
  /* #639: @118 = @0' */
  casadi_trans(w0,casadi_s13, w118, casadi_s13, iw);
  /* #640: output[2][0] = @118 */
  casadi_copy(w118, 7, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int sim_car_impl_dae_fun_jac_x_xdot_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int sim_car_impl_dae_fun_jac_x_xdot_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int sim_car_impl_dae_fun_jac_x_xdot_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void sim_car_impl_dae_fun_jac_x_xdot_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int sim_car_impl_dae_fun_jac_x_xdot_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void sim_car_impl_dae_fun_jac_x_xdot_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void sim_car_impl_dae_fun_jac_x_xdot_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void sim_car_impl_dae_fun_jac_x_xdot_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int sim_car_impl_dae_fun_jac_x_xdot_z_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int sim_car_impl_dae_fun_jac_x_xdot_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real sim_car_impl_dae_fun_jac_x_xdot_z_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* sim_car_impl_dae_fun_jac_x_xdot_z_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* sim_car_impl_dae_fun_jac_x_xdot_z_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* sim_car_impl_dae_fun_jac_x_xdot_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s14;
    case 1: return casadi_s14;
    case 2: return casadi_s15;
    case 3: return casadi_s16;
    case 4: return casadi_s16;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* sim_car_impl_dae_fun_jac_x_xdot_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s14;
    case 1: return casadi_s11;
    case 2: return casadi_s13;
    case 3: return casadi_s17;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int sim_car_impl_dae_fun_jac_x_xdot_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 236;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
