/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) sim_car_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_low CASADI_PREFIX(low)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[1] = {0};
static const casadi_int casadi_s1[1] = {1};
static const casadi_int casadi_s2[1] = {3};
static const casadi_int casadi_s3[2] = {0, 9};
static const casadi_int casadi_s4[1] = {2};
static const casadi_int casadi_s5[2] = {0, 7};
static const casadi_int casadi_s6[7] = {5, 2, 0, 1, 2, 3, 4};
static const casadi_int casadi_s7[10] = {2, 5, 0, 0, 0, 0, 1, 2, 0, 1};
static const casadi_int casadi_s8[13] = {5, 2, 0, 4, 8, 0, 1, 2, 3, 0, 1, 2, 4};
static const casadi_int casadi_s9[11] = {5, 2, 0, 3, 6, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s10[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s11[33] = {5, 5, 0, 5, 10, 15, 20, 25, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const casadi_int casadi_s12[15] = {5, 2, 0, 5, 10, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const casadi_int casadi_s13[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s14[3] = {0, 0, 0};
static const casadi_int casadi_s15[23] = {5, 5, 0, 3, 6, 9, 12, 15, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};

static const casadi_real casadi_c0[5] = {1.0000000000000019e-06, 9.9999999999999995e-07, 1.0000000000000002e-06, 1.0000000000000002e-06, 1.0000000000000019e-06};
static const casadi_real casadi_c1[9] = {0., 0., 0., 0., 2., 4., 4., 4., 4.};
static const casadi_real casadi_c2[4] = {-2.7528570785764761e-21, 1.0587911840678754e-22, 0., 2.5410988417629010e-21};
static const casadi_real casadi_c3[7] = {0., 0., 0., 2., 4., 4., 4.};

/* kapparef_s:(x)->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c1,casadi_s3,casadi_s2,casadi_s1,casadi_c0,1,(&w0),casadi_s0, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* jac_kapparef_s:(x,out_f[1x1,0nz])->(jac) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c3,casadi_s5,casadi_s4,casadi_s1,casadi_c2,1,(&w0),casadi_s0, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd2_kapparef_s:(x,out_f[1x1,0nz],fwd_x[1x2])->(fwd_f[1x2]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c3,casadi_s5,casadi_s4,casadi_s1,casadi_c2,1,(&w0),casadi_s0, iw, w);
  /* #2: @0 = input[2][0] */
  w0 = arg[2] ? arg[2][0] : 0;
  /* #3: @0 = (@1*@0) */
  w0  = (w1*w0);
  /* #4: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #5: @0 = input[2][1] */
  w0 = arg[2] ? arg[2][1] : 0;
  /* #6: @1 = (@1*@0) */
  w1 *= w0;
  /* #7: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  return 0;
}

/* sim_car_expl_vde_forw:(i0[5],i1[5x5],i2[5x2],i3[2],i4[])->(o0[5],o1[5x5,15nz],o2[5x2,8nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+3, *rr, *ss;
  const casadi_real **arg1=arg+5, *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, *w28=w+40, *w29=w+65, *w30=w+70, *w31=w+75, *w32=w+80, *w33=w+85, w34, w35, w36, w37, w38, w39, w40, w41, w42, w44, w45, w46, w47, w48, w49, w50, w51, w52, w53, w54, w55, w56, w57, w58, w59, w60, w61, w62, w63, w64, w65, w66, w67, w68, w69, w70, w71, w72, w73, w74, w75, w76, w77, w78, *w79=w+134, *w82=w+136, *w83=w+138, *w84=w+140, *w85=w+148, *w86=w+158, *w87=w+161, *w88=w+164, *w89=w+170;
  /* #0: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #1: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #3: @3 = input[0][4] */
  w3 = arg[0] ? arg[0][4] : 0;
  /* #4: @4 = tan(@3) */
  w4 = tan( w3 );
  /* #5: @4 = (@2*@4) */
  w4  = (w2*w4);
  /* #6: @5 = atan(@4) */
  w5 = atan( w4 );
  /* #7: @5 = (@1+@5) */
  w5  = (w1+w5);
  /* #8: @6 = cos(@5) */
  w6 = cos( w5 );
  /* #9: @7 = (@0*@6) */
  w7  = (w0*w6);
  /* #10: @8 = 1 */
  w8 = 1.;
  /* #11: @9 = input[0][1] */
  w9 = arg[0] ? arg[0][1] : 0;
  /* #12: @10 = input[0][0] */
  w10 = arg[0] ? arg[0][0] : 0;
  /* #13: @11 = kapparef_s(@10) */
  arg1[0]=(&w10);
  res1[0]=(&w11);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #14: @12 = (@9*@11) */
  w12  = (w9*w11);
  /* #15: @8 = (@8-@12) */
  w8 -= w12;
  /* #16: @7 = (@7/@8) */
  w7 /= w8;
  /* #17: output[0][0] = @7 */
  if (res[0]) res[0][0] = w7;
  /* #18: @12 = 0.5 */
  w12 = 5.0000000000000000e-01;
  /* #19: @13 = tan(@3) */
  w13 = tan( w3 );
  /* #20: @13 = (@12*@13) */
  w13  = (w12*w13);
  /* #21: @14 = atan(@13) */
  w14 = atan( w13 );
  /* #22: @14 = (@1+@14) */
  w14  = (w1+w14);
  /* #23: @15 = sin(@14) */
  w15 = sin( w14 );
  /* #24: @16 = (@0*@15) */
  w16  = (w0*w15);
  /* #25: output[0][1] = @16 */
  if (res[0]) res[0][1] = w16;
  /* #26: @16 = 1.4 */
  w16 = 1.3999999999999999e+00;
  /* #27: @16 = (@0/@16) */
  w16  = (w0/w16);
  /* #28: @17 = 0.5 */
  w17 = 5.0000000000000000e-01;
  /* #29: @18 = tan(@3) */
  w18 = tan( w3 );
  /* #30: @18 = (@17*@18) */
  w18  = (w17*w18);
  /* #31: @19 = atan(@18) */
  w19 = atan( w18 );
  /* #32: @20 = sin(@19) */
  w20 = sin( w19 );
  /* #33: @21 = (@16*@20) */
  w21  = (w16*w20);
  /* #34: @1 = (@1+@19) */
  w1 += w19;
  /* #35: @22 = cos(@1) */
  w22 = cos( w1 );
  /* #36: @23 = (@0*@22) */
  w23  = (w0*w22);
  /* #37: @24 = 1 */
  w24 = 1.;
  /* #38: @25 = kapparef_s(@10) */
  arg1[0]=(&w10);
  res1[0]=(&w25);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #39: @26 = (@9*@25) */
  w26  = (w9*w25);
  /* #40: @24 = (@24-@26) */
  w24 -= w26;
  /* #41: @23 = (@23/@24) */
  w23 /= w24;
  /* #42: @26 = kapparef_s(@10) */
  arg1[0]=(&w10);
  res1[0]=(&w26);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #43: @27 = (@23*@26) */
  w27  = (w23*w26);
  /* #44: @21 = (@21-@27) */
  w21 -= w27;
  /* #45: output[0][2] = @21 */
  if (res[0]) res[0][2] = w21;
  /* #46: @21 = input[3][0] */
  w21 = arg[3] ? arg[3][0] : 0;
  /* #47: output[0][3] = @21 */
  if (res[0]) res[0][3] = w21;
  /* #48: @21 = input[3][1] */
  w21 = arg[3] ? arg[3][1] : 0;
  /* #49: output[0][4] = @21 */
  if (res[0]) res[0][4] = w21;
  /* #50: @28 = input[1][0] */
  casadi_copy(arg[1], 25, w28);
  /* #51: {@29, @30, @31, @32, @33} = horzsplit(@28) */
  casadi_copy(w28, 5, w29);
  casadi_copy(w28+5, 5, w30);
  casadi_copy(w28+10, 5, w31);
  casadi_copy(w28+15, 5, w32);
  casadi_copy(w28+20, 5, w33);
  /* #52: {@21, @27, @34, @35, @36} = vertsplit(@29) */
  w21 = w29[0];
  w27 = w29[1];
  w34 = w29[2];
  w35 = w29[3];
  w36 = w29[4];
  /* #53: @37 = (@6*@35) */
  w37  = (w6*w35);
  /* #54: @38 = sin(@5) */
  w38 = sin( w5 );
  /* #55: @39 = cos(@3) */
  w39 = cos( w3 );
  /* #56: @39 = sq(@39) */
  w39 = casadi_sq( w39 );
  /* #57: @40 = (@36/@39) */
  w40  = (w36/w39);
  /* #58: @40 = (@2*@40) */
  w40  = (w2*w40);
  /* #59: @41 = 1 */
  w41 = 1.;
  /* #60: @42 = sq(@4) */
  w42 = casadi_sq( w4 );
  /* #61: @41 = (@41+@42) */
  w41 += w42;
  /* #62: @40 = (@40/@41) */
  w40 /= w41;
  /* #63: @40 = (@34+@40) */
  w40  = (w34+w40);
  /* #64: @40 = (@38*@40) */
  w40  = (w38*w40);
  /* #65: @40 = (@0*@40) */
  w40  = (w0*w40);
  /* #66: @37 = (@37-@40) */
  w37 -= w40;
  /* #67: @37 = (@37/@8) */
  w37 /= w8;
  /* #68: @40 = (@7/@8) */
  w40  = (w7/w8);
  /* #69: @42 = (@11*@27) */
  w42  = (w11*w27);
  /* #70: @43 = 00 */
  /* #71: @44 = jac_kapparef_s(@10, @43) */
  arg1[0]=(&w10);
  arg1[1]=0;
  res1[0]=(&w44);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #72: {@45, @46, @47, @48, @49} = vertsplit(@30) */
  w45 = w30[0];
  w46 = w30[1];
  w47 = w30[2];
  w48 = w30[3];
  w49 = w30[4];
  /* #73: {@50, @51, @52, @53, @54} = vertsplit(@31) */
  w50 = w31[0];
  w51 = w31[1];
  w52 = w31[2];
  w53 = w31[3];
  w54 = w31[4];
  /* #74: {@55, @56, @57, @58, @59} = vertsplit(@32) */
  w55 = w32[0];
  w56 = w32[1];
  w57 = w32[2];
  w58 = w32[3];
  w59 = w32[4];
  /* #75: {@60, @61, @62, @63, @64} = vertsplit(@33) */
  w60 = w33[0];
  w61 = w33[1];
  w62 = w33[2];
  w63 = w33[3];
  w64 = w33[4];
  /* #76: @33 = horzcat(@21, @45, @50, @55, @60) */
  rr=w33;
  *rr++ = w21;
  *rr++ = w45;
  *rr++ = w50;
  *rr++ = w55;
  *rr++ = w60;
  /* #77: @33 = (@44*@33) */
  for (i=0, rr=w33, cs=w33; i<5; ++i) (*rr++)  = (w44*(*cs++));
  /* #78: {@44, @65, @66, @67, @68} = horzsplit(@33) */
  w44 = w33[0];
  w65 = w33[1];
  w66 = w33[2];
  w67 = w33[3];
  w68 = w33[4];
  /* #79: @44 = (@9*@44) */
  w44  = (w9*w44);
  /* #80: @42 = (@42+@44) */
  w42 += w44;
  /* #81: @42 = (@40*@42) */
  w42  = (w40*w42);
  /* #82: @37 = (@37+@42) */
  w37 += w42;
  /* #83: output[1][0] = @37 */
  if (res[1]) res[1][0] = w37;
  /* #84: @37 = (@15*@35) */
  w37  = (w15*w35);
  /* #85: @42 = cos(@14) */
  w42 = cos( w14 );
  /* #86: @44 = cos(@3) */
  w44 = cos( w3 );
  /* #87: @44 = sq(@44) */
  w44 = casadi_sq( w44 );
  /* #88: @69 = (@36/@44) */
  w69  = (w36/w44);
  /* #89: @69 = (@12*@69) */
  w69  = (w12*w69);
  /* #90: @70 = 1 */
  w70 = 1.;
  /* #91: @71 = sq(@13) */
  w71 = casadi_sq( w13 );
  /* #92: @70 = (@70+@71) */
  w70 += w71;
  /* #93: @69 = (@69/@70) */
  w69 /= w70;
  /* #94: @69 = (@34+@69) */
  w69  = (w34+w69);
  /* #95: @69 = (@42*@69) */
  w69  = (w42*w69);
  /* #96: @69 = (@0*@69) */
  w69  = (w0*w69);
  /* #97: @37 = (@37+@69) */
  w37 += w69;
  /* #98: output[1][1] = @37 */
  if (res[1]) res[1][1] = w37;
  /* #99: @37 = 0.714286 */
  w37 = 7.1428571428571430e-01;
  /* #100: @69 = (@37*@35) */
  w69  = (w37*w35);
  /* #101: @69 = (@20*@69) */
  w69  = (w20*w69);
  /* #102: @71 = cos(@19) */
  w71 = cos( w19 );
  /* #103: @72 = cos(@3) */
  w72 = cos( w3 );
  /* #104: @72 = sq(@72) */
  w72 = casadi_sq( w72 );
  /* #105: @36 = (@36/@72) */
  w36 /= w72;
  /* #106: @36 = (@17*@36) */
  w36  = (w17*w36);
  /* #107: @73 = 1 */
  w73 = 1.;
  /* #108: @74 = sq(@18) */
  w74 = casadi_sq( w18 );
  /* #109: @73 = (@73+@74) */
  w73 += w74;
  /* #110: @36 = (@36/@73) */
  w36 /= w73;
  /* #111: @74 = (@71*@36) */
  w74  = (w71*w36);
  /* #112: @74 = (@16*@74) */
  w74  = (w16*w74);
  /* #113: @69 = (@69+@74) */
  w69 += w74;
  /* #114: @35 = (@22*@35) */
  w35  = (w22*w35);
  /* #115: @74 = sin(@1) */
  w74 = sin( w1 );
  /* #116: @34 = (@34+@36) */
  w34 += w36;
  /* #117: @34 = (@74*@34) */
  w34  = (w74*w34);
  /* #118: @34 = (@0*@34) */
  w34  = (w0*w34);
  /* #119: @35 = (@35-@34) */
  w35 -= w34;
  /* #120: @35 = (@35/@24) */
  w35 /= w24;
  /* #121: @34 = (@23/@24) */
  w34  = (w23/w24);
  /* #122: @27 = (@25*@27) */
  w27  = (w25*w27);
  /* #123: @43 = 00 */
  /* #124: @36 = jac_kapparef_s(@10, @43) */
  arg1[0]=(&w10);
  arg1[1]=0;
  res1[0]=(&w36);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #125: @33 = horzcat(@21, @45, @50, @55, @60) */
  rr=w33;
  *rr++ = w21;
  *rr++ = w45;
  *rr++ = w50;
  *rr++ = w55;
  *rr++ = w60;
  /* #126: @33 = (@36*@33) */
  for (i=0, rr=w33, cs=w33; i<5; ++i) (*rr++)  = (w36*(*cs++));
  /* #127: {@36, @75, @76, @77, @78} = horzsplit(@33) */
  w36 = w33[0];
  w75 = w33[1];
  w76 = w33[2];
  w77 = w33[3];
  w78 = w33[4];
  /* #128: @36 = (@9*@36) */
  w36  = (w9*w36);
  /* #129: @27 = (@27+@36) */
  w27 += w36;
  /* #130: @27 = (@34*@27) */
  w27  = (w34*w27);
  /* #131: @35 = (@35+@27) */
  w35 += w27;
  /* #132: @35 = (@26*@35) */
  w35  = (w26*w35);
  /* #133: @43 = 00 */
  /* #134: @27 = jac_kapparef_s(@10, @43) */
  arg1[0]=(&w10);
  arg1[1]=0;
  res1[0]=(&w27);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #135: @33 = horzcat(@21, @45, @50, @55, @60) */
  rr=w33;
  *rr++ = w21;
  *rr++ = w45;
  *rr++ = w50;
  *rr++ = w55;
  *rr++ = w60;
  /* #136: @33 = (@27*@33) */
  for (i=0, rr=w33, cs=w33; i<5; ++i) (*rr++)  = (w27*(*cs++));
  /* #137: {@27, @21, @45, @50, @55} = horzsplit(@33) */
  w27 = w33[0];
  w21 = w33[1];
  w45 = w33[2];
  w50 = w33[3];
  w55 = w33[4];
  /* #138: @27 = (@23*@27) */
  w27  = (w23*w27);
  /* #139: @35 = (@35+@27) */
  w35 += w27;
  /* #140: @69 = (@69-@35) */
  w69 -= w35;
  /* #141: output[1][2] = @69 */
  if (res[1]) res[1][2] = w69;
  /* #142: @69 = (@6*@48) */
  w69  = (w6*w48);
  /* #143: @35 = (@49/@39) */
  w35  = (w49/w39);
  /* #144: @35 = (@2*@35) */
  w35  = (w2*w35);
  /* #145: @35 = (@35/@41) */
  w35 /= w41;
  /* #146: @35 = (@47+@35) */
  w35  = (w47+w35);
  /* #147: @35 = (@38*@35) */
  w35  = (w38*w35);
  /* #148: @35 = (@0*@35) */
  w35  = (w0*w35);
  /* #149: @69 = (@69-@35) */
  w69 -= w35;
  /* #150: @69 = (@69/@8) */
  w69 /= w8;
  /* #151: @35 = (@11*@46) */
  w35  = (w11*w46);
  /* #152: @65 = (@9*@65) */
  w65  = (w9*w65);
  /* #153: @35 = (@35+@65) */
  w35 += w65;
  /* #154: @35 = (@40*@35) */
  w35  = (w40*w35);
  /* #155: @69 = (@69+@35) */
  w69 += w35;
  /* #156: output[1][3] = @69 */
  if (res[1]) res[1][3] = w69;
  /* #157: @69 = (@15*@48) */
  w69  = (w15*w48);
  /* #158: @35 = (@49/@44) */
  w35  = (w49/w44);
  /* #159: @35 = (@12*@35) */
  w35  = (w12*w35);
  /* #160: @35 = (@35/@70) */
  w35 /= w70;
  /* #161: @35 = (@47+@35) */
  w35  = (w47+w35);
  /* #162: @35 = (@42*@35) */
  w35  = (w42*w35);
  /* #163: @35 = (@0*@35) */
  w35  = (w0*w35);
  /* #164: @69 = (@69+@35) */
  w69 += w35;
  /* #165: output[1][4] = @69 */
  if (res[1]) res[1][4] = w69;
  /* #166: @69 = (@37*@48) */
  w69  = (w37*w48);
  /* #167: @69 = (@20*@69) */
  w69  = (w20*w69);
  /* #168: @49 = (@49/@72) */
  w49 /= w72;
  /* #169: @49 = (@17*@49) */
  w49  = (w17*w49);
  /* #170: @49 = (@49/@73) */
  w49 /= w73;
  /* #171: @35 = (@71*@49) */
  w35  = (w71*w49);
  /* #172: @35 = (@16*@35) */
  w35  = (w16*w35);
  /* #173: @69 = (@69+@35) */
  w69 += w35;
  /* #174: @48 = (@22*@48) */
  w48  = (w22*w48);
  /* #175: @47 = (@47+@49) */
  w47 += w49;
  /* #176: @47 = (@74*@47) */
  w47  = (w74*w47);
  /* #177: @47 = (@0*@47) */
  w47  = (w0*w47);
  /* #178: @48 = (@48-@47) */
  w48 -= w47;
  /* #179: @48 = (@48/@24) */
  w48 /= w24;
  /* #180: @46 = (@25*@46) */
  w46  = (w25*w46);
  /* #181: @75 = (@9*@75) */
  w75  = (w9*w75);
  /* #182: @46 = (@46+@75) */
  w46 += w75;
  /* #183: @46 = (@34*@46) */
  w46  = (w34*w46);
  /* #184: @48 = (@48+@46) */
  w48 += w46;
  /* #185: @48 = (@26*@48) */
  w48  = (w26*w48);
  /* #186: @21 = (@23*@21) */
  w21  = (w23*w21);
  /* #187: @48 = (@48+@21) */
  w48 += w21;
  /* #188: @69 = (@69-@48) */
  w69 -= w48;
  /* #189: output[1][5] = @69 */
  if (res[1]) res[1][5] = w69;
  /* #190: @69 = (@6*@53) */
  w69  = (w6*w53);
  /* #191: @48 = (@54/@39) */
  w48  = (w54/w39);
  /* #192: @48 = (@2*@48) */
  w48  = (w2*w48);
  /* #193: @48 = (@48/@41) */
  w48 /= w41;
  /* #194: @48 = (@52+@48) */
  w48  = (w52+w48);
  /* #195: @48 = (@38*@48) */
  w48  = (w38*w48);
  /* #196: @48 = (@0*@48) */
  w48  = (w0*w48);
  /* #197: @69 = (@69-@48) */
  w69 -= w48;
  /* #198: @69 = (@69/@8) */
  w69 /= w8;
  /* #199: @48 = (@11*@51) */
  w48  = (w11*w51);
  /* #200: @66 = (@9*@66) */
  w66  = (w9*w66);
  /* #201: @48 = (@48+@66) */
  w48 += w66;
  /* #202: @48 = (@40*@48) */
  w48  = (w40*w48);
  /* #203: @69 = (@69+@48) */
  w69 += w48;
  /* #204: output[1][6] = @69 */
  if (res[1]) res[1][6] = w69;
  /* #205: @69 = (@15*@53) */
  w69  = (w15*w53);
  /* #206: @48 = (@54/@44) */
  w48  = (w54/w44);
  /* #207: @48 = (@12*@48) */
  w48  = (w12*w48);
  /* #208: @48 = (@48/@70) */
  w48 /= w70;
  /* #209: @48 = (@52+@48) */
  w48  = (w52+w48);
  /* #210: @48 = (@42*@48) */
  w48  = (w42*w48);
  /* #211: @48 = (@0*@48) */
  w48  = (w0*w48);
  /* #212: @69 = (@69+@48) */
  w69 += w48;
  /* #213: output[1][7] = @69 */
  if (res[1]) res[1][7] = w69;
  /* #214: @69 = (@37*@53) */
  w69  = (w37*w53);
  /* #215: @69 = (@20*@69) */
  w69  = (w20*w69);
  /* #216: @54 = (@54/@72) */
  w54 /= w72;
  /* #217: @54 = (@17*@54) */
  w54  = (w17*w54);
  /* #218: @54 = (@54/@73) */
  w54 /= w73;
  /* #219: @48 = (@71*@54) */
  w48  = (w71*w54);
  /* #220: @48 = (@16*@48) */
  w48  = (w16*w48);
  /* #221: @69 = (@69+@48) */
  w69 += w48;
  /* #222: @53 = (@22*@53) */
  w53  = (w22*w53);
  /* #223: @52 = (@52+@54) */
  w52 += w54;
  /* #224: @52 = (@74*@52) */
  w52  = (w74*w52);
  /* #225: @52 = (@0*@52) */
  w52  = (w0*w52);
  /* #226: @53 = (@53-@52) */
  w53 -= w52;
  /* #227: @53 = (@53/@24) */
  w53 /= w24;
  /* #228: @51 = (@25*@51) */
  w51  = (w25*w51);
  /* #229: @76 = (@9*@76) */
  w76  = (w9*w76);
  /* #230: @51 = (@51+@76) */
  w51 += w76;
  /* #231: @51 = (@34*@51) */
  w51  = (w34*w51);
  /* #232: @53 = (@53+@51) */
  w53 += w51;
  /* #233: @53 = (@26*@53) */
  w53  = (w26*w53);
  /* #234: @45 = (@23*@45) */
  w45  = (w23*w45);
  /* #235: @53 = (@53+@45) */
  w53 += w45;
  /* #236: @69 = (@69-@53) */
  w69 -= w53;
  /* #237: output[1][8] = @69 */
  if (res[1]) res[1][8] = w69;
  /* #238: @69 = (@6*@58) */
  w69  = (w6*w58);
  /* #239: @53 = (@59/@39) */
  w53  = (w59/w39);
  /* #240: @53 = (@2*@53) */
  w53  = (w2*w53);
  /* #241: @53 = (@53/@41) */
  w53 /= w41;
  /* #242: @53 = (@57+@53) */
  w53  = (w57+w53);
  /* #243: @53 = (@38*@53) */
  w53  = (w38*w53);
  /* #244: @53 = (@0*@53) */
  w53  = (w0*w53);
  /* #245: @69 = (@69-@53) */
  w69 -= w53;
  /* #246: @69 = (@69/@8) */
  w69 /= w8;
  /* #247: @53 = (@11*@56) */
  w53  = (w11*w56);
  /* #248: @67 = (@9*@67) */
  w67  = (w9*w67);
  /* #249: @53 = (@53+@67) */
  w53 += w67;
  /* #250: @53 = (@40*@53) */
  w53  = (w40*w53);
  /* #251: @69 = (@69+@53) */
  w69 += w53;
  /* #252: output[1][9] = @69 */
  if (res[1]) res[1][9] = w69;
  /* #253: @69 = (@15*@58) */
  w69  = (w15*w58);
  /* #254: @53 = (@59/@44) */
  w53  = (w59/w44);
  /* #255: @53 = (@12*@53) */
  w53  = (w12*w53);
  /* #256: @53 = (@53/@70) */
  w53 /= w70;
  /* #257: @53 = (@57+@53) */
  w53  = (w57+w53);
  /* #258: @53 = (@42*@53) */
  w53  = (w42*w53);
  /* #259: @53 = (@0*@53) */
  w53  = (w0*w53);
  /* #260: @69 = (@69+@53) */
  w69 += w53;
  /* #261: output[1][10] = @69 */
  if (res[1]) res[1][10] = w69;
  /* #262: @69 = (@37*@58) */
  w69  = (w37*w58);
  /* #263: @69 = (@20*@69) */
  w69  = (w20*w69);
  /* #264: @59 = (@59/@72) */
  w59 /= w72;
  /* #265: @59 = (@17*@59) */
  w59  = (w17*w59);
  /* #266: @59 = (@59/@73) */
  w59 /= w73;
  /* #267: @53 = (@71*@59) */
  w53  = (w71*w59);
  /* #268: @53 = (@16*@53) */
  w53  = (w16*w53);
  /* #269: @69 = (@69+@53) */
  w69 += w53;
  /* #270: @58 = (@22*@58) */
  w58  = (w22*w58);
  /* #271: @57 = (@57+@59) */
  w57 += w59;
  /* #272: @57 = (@74*@57) */
  w57  = (w74*w57);
  /* #273: @57 = (@0*@57) */
  w57  = (w0*w57);
  /* #274: @58 = (@58-@57) */
  w58 -= w57;
  /* #275: @58 = (@58/@24) */
  w58 /= w24;
  /* #276: @56 = (@25*@56) */
  w56  = (w25*w56);
  /* #277: @77 = (@9*@77) */
  w77  = (w9*w77);
  /* #278: @56 = (@56+@77) */
  w56 += w77;
  /* #279: @56 = (@34*@56) */
  w56  = (w34*w56);
  /* #280: @58 = (@58+@56) */
  w58 += w56;
  /* #281: @58 = (@26*@58) */
  w58  = (w26*w58);
  /* #282: @50 = (@23*@50) */
  w50  = (w23*w50);
  /* #283: @58 = (@58+@50) */
  w58 += w50;
  /* #284: @69 = (@69-@58) */
  w69 -= w58;
  /* #285: output[1][11] = @69 */
  if (res[1]) res[1][11] = w69;
  /* #286: @69 = (@6*@63) */
  w69  = (w6*w63);
  /* #287: @39 = (@64/@39) */
  w39  = (w64/w39);
  /* #288: @39 = (@2*@39) */
  w39  = (w2*w39);
  /* #289: @39 = (@39/@41) */
  w39 /= w41;
  /* #290: @39 = (@62+@39) */
  w39  = (w62+w39);
  /* #291: @38 = (@38*@39) */
  w38 *= w39;
  /* #292: @38 = (@0*@38) */
  w38  = (w0*w38);
  /* #293: @69 = (@69-@38) */
  w69 -= w38;
  /* #294: @69 = (@69/@8) */
  w69 /= w8;
  /* #295: @38 = (@11*@61) */
  w38  = (w11*w61);
  /* #296: @68 = (@9*@68) */
  w68  = (w9*w68);
  /* #297: @38 = (@38+@68) */
  w38 += w68;
  /* #298: @40 = (@40*@38) */
  w40 *= w38;
  /* #299: @69 = (@69+@40) */
  w69 += w40;
  /* #300: output[1][12] = @69 */
  if (res[1]) res[1][12] = w69;
  /* #301: @69 = (@15*@63) */
  w69  = (w15*w63);
  /* #302: @44 = (@64/@44) */
  w44  = (w64/w44);
  /* #303: @44 = (@12*@44) */
  w44  = (w12*w44);
  /* #304: @44 = (@44/@70) */
  w44 /= w70;
  /* #305: @44 = (@62+@44) */
  w44  = (w62+w44);
  /* #306: @42 = (@42*@44) */
  w42 *= w44;
  /* #307: @42 = (@0*@42) */
  w42  = (w0*w42);
  /* #308: @69 = (@69+@42) */
  w69 += w42;
  /* #309: output[1][13] = @69 */
  if (res[1]) res[1][13] = w69;
  /* #310: @37 = (@37*@63) */
  w37 *= w63;
  /* #311: @37 = (@20*@37) */
  w37  = (w20*w37);
  /* #312: @64 = (@64/@72) */
  w64 /= w72;
  /* #313: @64 = (@17*@64) */
  w64  = (w17*w64);
  /* #314: @64 = (@64/@73) */
  w64 /= w73;
  /* #315: @71 = (@71*@64) */
  w71 *= w64;
  /* #316: @71 = (@16*@71) */
  w71  = (w16*w71);
  /* #317: @37 = (@37+@71) */
  w37 += w71;
  /* #318: @63 = (@22*@63) */
  w63  = (w22*w63);
  /* #319: @62 = (@62+@64) */
  w62 += w64;
  /* #320: @74 = (@74*@62) */
  w74 *= w62;
  /* #321: @74 = (@0*@74) */
  w74  = (w0*w74);
  /* #322: @63 = (@63-@74) */
  w63 -= w74;
  /* #323: @63 = (@63/@24) */
  w63 /= w24;
  /* #324: @61 = (@25*@61) */
  w61  = (w25*w61);
  /* #325: @78 = (@9*@78) */
  w78  = (w9*w78);
  /* #326: @61 = (@61+@78) */
  w61 += w78;
  /* #327: @34 = (@34*@61) */
  w34 *= w61;
  /* #328: @63 = (@63+@34) */
  w63 += w34;
  /* #329: @63 = (@26*@63) */
  w63  = (w26*w63);
  /* #330: @55 = (@23*@55) */
  w55  = (w23*w55);
  /* #331: @63 = (@63+@55) */
  w63 += w55;
  /* #332: @37 = (@37-@63) */
  w37 -= w63;
  /* #333: output[1][14] = @37 */
  if (res[1]) res[1][14] = w37;
  /* #334: @79 = zeros(2x5,2nz) */
  casadi_clear(w79, 2);
  /* #335: @43 = 00 */
  /* #336: @80 = 00 */
  /* #337: @81 = 00 */
  /* #338: @82 = ones(2x1) */
  casadi_fill(w82, 2, 1.);
  /* #339: {@37, @63} = vertsplit(@82) */
  w37 = w82[0];
  w63 = w82[1];
  /* #340: @82 = vertcat(@43, @80, @81, @37, @63) */
  rr=w82;
  *rr++ = w37;
  *rr++ = w63;
  /* #341: @83 = @82[:2] */
  for (rr=w83, ss=w82+0; ss!=w82+2; ss+=1) *rr++ = *ss;
  /* #342: (@79[:2] = @83) */
  for (rr=w79+0, ss=w83; rr!=w79+2; rr+=1) *rr = *ss++;
  /* #343: @83 = @79' */
  casadi_trans(w79,casadi_s7, w83, casadi_s6, iw);
  /* #344: @84 = project(@83) */
  casadi_project(w83, casadi_s6, w84, casadi_s8, w);
  /* #345: @85 = input[2][0] */
  casadi_copy(arg[2], 10, w85);
  /* #346: {@33, @32} = horzsplit(@85) */
  casadi_copy(w85, 5, w33);
  casadi_copy(w85+5, 5, w32);
  /* #347: {@37, @63, @55, @34, @61} = vertsplit(@33) */
  w37 = w33[0];
  w63 = w33[1];
  w55 = w33[2];
  w34 = w33[3];
  w61 = w33[4];
  /* #348: @78 = (@6*@34) */
  w78  = (w6*w34);
  /* #349: @5 = sin(@5) */
  w5 = sin( w5 );
  /* #350: @74 = cos(@3) */
  w74 = cos( w3 );
  /* #351: @74 = sq(@74) */
  w74 = casadi_sq( w74 );
  /* #352: @62 = (@61/@74) */
  w62  = (w61/w74);
  /* #353: @62 = (@2*@62) */
  w62  = (w2*w62);
  /* #354: @64 = 1 */
  w64 = 1.;
  /* #355: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #356: @64 = (@64+@4) */
  w64 += w4;
  /* #357: @62 = (@62/@64) */
  w62 /= w64;
  /* #358: @62 = (@55+@62) */
  w62  = (w55+w62);
  /* #359: @62 = (@5*@62) */
  w62  = (w5*w62);
  /* #360: @62 = (@0*@62) */
  w62  = (w0*w62);
  /* #361: @78 = (@78-@62) */
  w78 -= w62;
  /* #362: @78 = (@78/@8) */
  w78 /= w8;
  /* #363: @7 = (@7/@8) */
  w7 /= w8;
  /* #364: @62 = (@11*@63) */
  w62  = (w11*w63);
  /* #365: @43 = 00 */
  /* #366: {@4, @71, @73, @72, @69} = vertsplit(@32) */
  w4 = w32[0];
  w71 = w32[1];
  w73 = w32[2];
  w72 = w32[3];
  w69 = w32[4];
  /* #367: @83 = horzcat(@37, @4) */
  rr=w83;
  *rr++ = w37;
  *rr++ = w4;
  /* #368: @79 = fwd2_kapparef_s(@10, @43, @83) */
  arg1[0]=(&w10);
  arg1[1]=0;
  arg1[2]=w83;
  res1[0]=w79;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #369: {@42, @44} = horzsplit(@79) */
  w42 = w79[0];
  w44 = w79[1];
  /* #370: @42 = (@9*@42) */
  w42  = (w9*w42);
  /* #371: @62 = (@62+@42) */
  w62 += w42;
  /* #372: @62 = (@7*@62) */
  w62  = (w7*w62);
  /* #373: @78 = (@78+@62) */
  w78 += w62;
  /* #374: @62 = (@15*@34) */
  w62  = (w15*w34);
  /* #375: @14 = cos(@14) */
  w14 = cos( w14 );
  /* #376: @42 = cos(@3) */
  w42 = cos( w3 );
  /* #377: @42 = sq(@42) */
  w42 = casadi_sq( w42 );
  /* #378: @70 = (@61/@42) */
  w70  = (w61/w42);
  /* #379: @70 = (@12*@70) */
  w70  = (w12*w70);
  /* #380: @40 = 1 */
  w40 = 1.;
  /* #381: @13 = sq(@13) */
  w13 = casadi_sq( w13 );
  /* #382: @40 = (@40+@13) */
  w40 += w13;
  /* #383: @70 = (@70/@40) */
  w70 /= w40;
  /* #384: @70 = (@55+@70) */
  w70  = (w55+w70);
  /* #385: @70 = (@14*@70) */
  w70  = (w14*w70);
  /* #386: @70 = (@0*@70) */
  w70  = (w0*w70);
  /* #387: @62 = (@62+@70) */
  w62 += w70;
  /* #388: @70 = 0.714286 */
  w70 = 7.1428571428571430e-01;
  /* #389: @13 = (@70*@34) */
  w13  = (w70*w34);
  /* #390: @13 = (@20*@13) */
  w13  = (w20*w13);
  /* #391: @19 = cos(@19) */
  w19 = cos( w19 );
  /* #392: @3 = cos(@3) */
  w3 = cos( w3 );
  /* #393: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #394: @61 = (@61/@3) */
  w61 /= w3;
  /* #395: @61 = (@17*@61) */
  w61  = (w17*w61);
  /* #396: @38 = 1 */
  w38 = 1.;
  /* #397: @18 = sq(@18) */
  w18 = casadi_sq( w18 );
  /* #398: @38 = (@38+@18) */
  w38 += w18;
  /* #399: @61 = (@61/@38) */
  w61 /= w38;
  /* #400: @18 = (@19*@61) */
  w18  = (w19*w61);
  /* #401: @18 = (@16*@18) */
  w18  = (w16*w18);
  /* #402: @13 = (@13+@18) */
  w13 += w18;
  /* #403: @34 = (@22*@34) */
  w34  = (w22*w34);
  /* #404: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #405: @55 = (@55+@61) */
  w55 += w61;
  /* #406: @55 = (@1*@55) */
  w55  = (w1*w55);
  /* #407: @55 = (@0*@55) */
  w55  = (w0*w55);
  /* #408: @34 = (@34-@55) */
  w34 -= w55;
  /* #409: @34 = (@34/@24) */
  w34 /= w24;
  /* #410: @55 = (@23/@24) */
  w55  = (w23/w24);
  /* #411: @63 = (@25*@63) */
  w63  = (w25*w63);
  /* #412: @43 = 00 */
  /* #413: @79 = horzcat(@37, @4) */
  rr=w79;
  *rr++ = w37;
  *rr++ = w4;
  /* #414: @83 = fwd2_kapparef_s(@10, @43, @79) */
  arg1[0]=(&w10);
  arg1[1]=0;
  arg1[2]=w79;
  res1[0]=w83;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #415: {@61, @18} = horzsplit(@83) */
  w61 = w83[0];
  w18 = w83[1];
  /* #416: @61 = (@9*@61) */
  w61  = (w9*w61);
  /* #417: @63 = (@63+@61) */
  w63 += w61;
  /* #418: @63 = (@55*@63) */
  w63  = (w55*w63);
  /* #419: @34 = (@34+@63) */
  w34 += w63;
  /* #420: @34 = (@26*@34) */
  w34  = (w26*w34);
  /* #421: @43 = 00 */
  /* #422: @83 = horzcat(@37, @4) */
  rr=w83;
  *rr++ = w37;
  *rr++ = w4;
  /* #423: @79 = fwd2_kapparef_s(@10, @43, @83) */
  arg1[0]=(&w10);
  arg1[1]=0;
  arg1[2]=w83;
  res1[0]=w79;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #424: {@10, @37} = horzsplit(@79) */
  w10 = w79[0];
  w37 = w79[1];
  /* #425: @10 = (@23*@10) */
  w10  = (w23*w10);
  /* #426: @34 = (@34+@10) */
  w34 += w10;
  /* #427: @13 = (@13-@34) */
  w13 -= w34;
  /* #428: @43 = 00 */
  /* #429: @80 = 00 */
  /* #430: @86 = vertcat(@78, @62, @13, @43, @80) */
  rr=w86;
  *rr++ = w78;
  *rr++ = w62;
  *rr++ = w13;
  /* #431: @6 = (@6*@72) */
  w6 *= w72;
  /* #432: @74 = (@69/@74) */
  w74  = (w69/w74);
  /* #433: @2 = (@2*@74) */
  w2 *= w74;
  /* #434: @2 = (@2/@64) */
  w2 /= w64;
  /* #435: @2 = (@73+@2) */
  w2  = (w73+w2);
  /* #436: @5 = (@5*@2) */
  w5 *= w2;
  /* #437: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #438: @6 = (@6-@5) */
  w6 -= w5;
  /* #439: @6 = (@6/@8) */
  w6 /= w8;
  /* #440: @11 = (@11*@71) */
  w11 *= w71;
  /* #441: @44 = (@9*@44) */
  w44  = (w9*w44);
  /* #442: @11 = (@11+@44) */
  w11 += w44;
  /* #443: @7 = (@7*@11) */
  w7 *= w11;
  /* #444: @6 = (@6+@7) */
  w6 += w7;
  /* #445: @15 = (@15*@72) */
  w15 *= w72;
  /* #446: @42 = (@69/@42) */
  w42  = (w69/w42);
  /* #447: @12 = (@12*@42) */
  w12 *= w42;
  /* #448: @12 = (@12/@40) */
  w12 /= w40;
  /* #449: @12 = (@73+@12) */
  w12  = (w73+w12);
  /* #450: @14 = (@14*@12) */
  w14 *= w12;
  /* #451: @14 = (@0*@14) */
  w14  = (w0*w14);
  /* #452: @15 = (@15+@14) */
  w15 += w14;
  /* #453: @70 = (@70*@72) */
  w70 *= w72;
  /* #454: @20 = (@20*@70) */
  w20 *= w70;
  /* #455: @69 = (@69/@3) */
  w69 /= w3;
  /* #456: @17 = (@17*@69) */
  w17 *= w69;
  /* #457: @17 = (@17/@38) */
  w17 /= w38;
  /* #458: @19 = (@19*@17) */
  w19 *= w17;
  /* #459: @16 = (@16*@19) */
  w16 *= w19;
  /* #460: @20 = (@20+@16) */
  w20 += w16;
  /* #461: @22 = (@22*@72) */
  w22 *= w72;
  /* #462: @73 = (@73+@17) */
  w73 += w17;
  /* #463: @1 = (@1*@73) */
  w1 *= w73;
  /* #464: @0 = (@0*@1) */
  w0 *= w1;
  /* #465: @22 = (@22-@0) */
  w22 -= w0;
  /* #466: @22 = (@22/@24) */
  w22 /= w24;
  /* #467: @25 = (@25*@71) */
  w25 *= w71;
  /* #468: @9 = (@9*@18) */
  w9 *= w18;
  /* #469: @25 = (@25+@9) */
  w25 += w9;
  /* #470: @55 = (@55*@25) */
  w55 *= w25;
  /* #471: @22 = (@22+@55) */
  w22 += w55;
  /* #472: @26 = (@26*@22) */
  w26 *= w22;
  /* #473: @23 = (@23*@37) */
  w23 *= w37;
  /* #474: @26 = (@26+@23) */
  w26 += w23;
  /* #475: @20 = (@20-@26) */
  w20 -= w26;
  /* #476: @43 = 00 */
  /* #477: @80 = 00 */
  /* #478: @87 = vertcat(@6, @15, @20, @43, @80) */
  rr=w87;
  *rr++ = w6;
  *rr++ = w15;
  *rr++ = w20;
  /* #479: @88 = horzcat(@86, @87) */
  rr=w88;
  for (i=0, cs=w86; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w87; i<3; ++i) *rr++ = *cs++;
  /* #480: @89 = project(@88) */
  casadi_project(w88, casadi_s9, w89, casadi_s8, w);
  /* #481: @84 = (@84+@89) */
  for (i=0, rr=w84, cs=w89; i<8; ++i) (*rr++) += (*cs++);
  /* #482: output[2][0] = @84 */
  casadi_copy(w84, 8, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int sim_car_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int sim_car_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int sim_car_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void sim_car_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int sim_car_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void sim_car_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void sim_car_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void sim_car_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int sim_car_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int sim_car_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real sim_car_expl_vde_forw_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* sim_car_expl_vde_forw_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* sim_car_expl_vde_forw_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* sim_car_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    case 1: return casadi_s11;
    case 2: return casadi_s12;
    case 3: return casadi_s13;
    case 4: return casadi_s14;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* sim_car_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    case 1: return casadi_s15;
    case 2: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int sim_car_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 178;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
