/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) sim_car_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[8] = {6, 1, 0, 4, 2, 3, 4, 5};

/* sim_car_expl_vde_adj:(i0[4],i1[4],i2[2],i3[])->(o0[6x1,4nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, *w8=w+8, w9, w10, w11, w12, w13, w14, w15, w16, w17;
  /* #0: @0 = input[0][1] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #1: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #2: @2 = input[2][1] */
  w2 = arg[2] ? arg[2][1] : 0;
  /* #3: @3 = tan(@2) */
  w3 = tan( w2 );
  /* #4: @3 = (@1*@3) */
  w3  = (w1*w3);
  /* #5: @4 = atan(@3) */
  w4 = atan( w3 );
  /* #6: @5 = (@0+@4) */
  w5  = (w0+w4);
  /* #7: @6 = cos(@5) */
  w6 = cos( w5 );
  /* #8: @7 = input[0][2] */
  w7 = arg[0] ? arg[0][3] : 0;
  /* #9: @8 = input[1][0] */
  casadi_copy(arg[1], 4, w8);
  /* #10: {@9, @10, @11, @12} = vertsplit(@8) */
  w9 = w8[0];
  w10 = w8[1];
  w11 = w8[2];
  w12 = w8[3];
  /* #11: @13 = (@7*@10) */
  w13  = (w7*w10);
  /* #12: @6 = (@6*@13) */
  w6 *= w13;
  /* #13: @0 = (@0+@4) */
  w0 += w4;
  /* #14: @4 = sin(@0) */
  w4 = sin( w0 );
  /* #15: @13 = (@7*@9) */
  w13  = (w7*w9);
  /* #16: @4 = (@4*@13) */
  w4 *= w13;
  /* #17: @13 = (@6-@4) */
  w13  = (w6-w4);
  /* #18: output[0][0] = @13 */
  if (res[0]) res[0][0] = w13;
  /* #19: @13 = 0.689655 */
  w13 = 6.8965517241379315e-01;
  /* #20: @14 = 0.5 */
  w14 = 5.0000000000000000e-01;
  /* #21: @15 = tan(@2) */
  w15 = tan( w2 );
  /* #22: @15 = (@14*@15) */
  w15  = (w14*w15);
  /* #23: @16 = atan(@15) */
  w16 = atan( w15 );
  /* #24: @17 = sin(@16) */
  w17 = sin( w16 );
  /* #25: @17 = (@17*@11) */
  w17 *= w11;
  /* #26: @13 = (@13*@17) */
  w13 *= w17;
  /* #27: @5 = sin(@5) */
  w5 = sin( w5 );
  /* #28: @5 = (@5*@10) */
  w5 *= w10;
  /* #29: @13 = (@13+@5) */
  w13 += w5;
  /* #30: @0 = cos(@0) */
  w0 = cos( w0 );
  /* #31: @0 = (@0*@9) */
  w0 *= w9;
  /* #32: @13 = (@13+@0) */
  w13 += w0;
  /* #33: output[0][1] = @13 */
  if (res[0]) res[0][1] = w13;
  /* #34: output[0][2] = @12 */
  if (res[0]) res[0][2] = w12;
  /* #35: @16 = cos(@16) */
  w16 = cos( w16 );
  /* #36: @12 = 1.45 */
  w12 = 1.4500000000000000e+00;
  /* #37: @7 = (@7/@12) */
  w7 /= w12;
  /* #38: @7 = (@7*@11) */
  w7 *= w11;
  /* #39: @16 = (@16*@7) */
  w16 *= w7;
  /* #40: @7 = 1 */
  w7 = 1.;
  /* #41: @15 = sq(@15) */
  w15 = casadi_sq( w15 );
  /* #42: @7 = (@7+@15) */
  w7 += w15;
  /* #43: @16 = (@16/@7) */
  w16 /= w7;
  /* #44: @14 = (@14*@16) */
  w14 *= w16;
  /* #45: @16 = cos(@2) */
  w16 = cos( w2 );
  /* #46: @16 = sq(@16) */
  w16 = casadi_sq( w16 );
  /* #47: @14 = (@14/@16) */
  w14 /= w16;
  /* #48: @6 = (@6-@4) */
  w6 -= w4;
  /* #49: @4 = 1 */
  w4 = 1.;
  /* #50: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #51: @4 = (@4+@3) */
  w4 += w3;
  /* #52: @6 = (@6/@4) */
  w6 /= w4;
  /* #53: @1 = (@1*@6) */
  w1 *= w6;
  /* #54: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #55: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #56: @1 = (@1/@2) */
  w1 /= w2;
  /* #57: @14 = (@14+@1) */
  w14 += w1;
  /* #58: output[0][3] = @14 */
  if (res[0]) res[0][3] = w14;
  return 0;
}

CASADI_SYMBOL_EXPORT int sim_car_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int sim_car_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int sim_car_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void sim_car_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int sim_car_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void sim_car_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void sim_car_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void sim_car_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int sim_car_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int sim_car_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real sim_car_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* sim_car_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* sim_car_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* sim_car_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* sim_car_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int sim_car_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 21;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
