/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) sim_car_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};

/* sim_car_expl_ode_fun:(i0[4],i1[2],i2[])->(o0[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4;
  /* #0: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #1: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #3: @3 = input[1][1] */
  w3 = arg[1] ? arg[1][1] : 0;
  /* #4: @4 = tan(@3) */
  w4 = tan( w3 );
  /* #5: @2 = (@2*@4) */
  w2 *= w4;
  /* #6: @2 = atan(@2) */
  w2 = atan( w2 );
  /* #7: @4 = (@1+@2) */
  w4  = (w1+w2);
  /* #8: @4 = cos(@4) */
  w4 = cos( w4 );
  /* #9: @4 = (@0*@4) */
  w4  = (w0*w4);
  /* #10: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  /* #11: @1 = (@1+@2) */
  w1 += w2;
  /* #12: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #13: @1 = (@0*@1) */
  w1  = (w0*w1);
  /* #14: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #15: @1 = 1.45 */
  w1 = 1.4500000000000000e+00;
  /* #16: @0 = (@0/@1) */
  w0 /= w1;
  /* #17: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #18: @3 = tan(@3) */
  w3 = tan( w3 );
  /* #19: @1 = (@1*@3) */
  w1 *= w3;
  /* #20: @1 = atan(@1) */
  w1 = atan( w1 );
  /* #21: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #22: @0 = (@0*@1) */
  w0 *= w1;
  /* #23: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #24: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #25: output[0][3] = @0 */
  if (res[0]) res[0][3] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int sim_car_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int sim_car_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int sim_car_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void sim_car_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int sim_car_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void sim_car_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void sim_car_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void sim_car_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int sim_car_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int sim_car_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real sim_car_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* sim_car_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* sim_car_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* sim_car_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* sim_car_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int sim_car_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 5;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
