/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) sim_car_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[9] = {4, 2, 0, 1, 4, 3, 0, 1, 2};
static const casadi_int casadi_s1[11] = {2, 4, 0, 1, 2, 3, 4, 1, 1, 1, 0};
static const casadi_int casadi_s2[12] = {4, 2, 0, 4, 7, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s3[11] = {4, 2, 0, 3, 6, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s4[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s5[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s6[13] = {4, 2, 0, 4, 8, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s7[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s8[3] = {0, 0, 0};
static const casadi_int casadi_s9[19] = {4, 4, 0, 3, 6, 9, 12, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};

/* sim_car_expl_vde_forw:(i0[4],i1[4x4],i2[4x2],i3[2],i4[])->(o0[4],o1[4x4,12nz],o2[4x2,7nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, *w14=w+18, *w15=w+34, *w16=w+38, *w17=w+42, *w18=w+46, w19, w20, w21, w22, w23, w24, *w25=w+56, *w26=w+58, *w27=w+65, *w29=w+73, *w30=w+76, *w31=w+79, *w32=w+85;
  /* #0: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #1: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = 0.501597 */
  w2 = 5.0159744408945695e-01;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = tan(@3) */
  w4 = tan( w3 );
  /* #5: @4 = (@2*@4) */
  w4  = (w2*w4);
  /* #6: @5 = atan(@4) */
  w5 = atan( w4 );
  /* #7: @6 = (@1+@5) */
  w6  = (w1+w5);
  /* #8: @7 = cos(@6) */
  w7 = cos( w6 );
  /* #9: @8 = (@0*@7) */
  w8  = (w0*w7);
  /* #10: output[0][0] = @8 */
  if (res[0]) res[0][0] = w8;
  /* #11: @1 = (@1+@5) */
  w1 += w5;
  /* #12: @5 = sin(@1) */
  w5 = sin( w1 );
  /* #13: @8 = (@0*@5) */
  w8  = (w0*w5);
  /* #14: output[0][1] = @8 */
  if (res[0]) res[0][1] = w8;
  /* #15: @8 = 1.57 */
  w8 = 1.5700000000000001e+00;
  /* #16: @8 = (@0/@8) */
  w8  = (w0/w8);
  /* #17: @9 = 0.501597 */
  w9 = 5.0159744408945695e-01;
  /* #18: @10 = tan(@3) */
  w10 = tan( w3 );
  /* #19: @10 = (@9*@10) */
  w10  = (w9*w10);
  /* #20: @11 = atan(@10) */
  w11 = atan( w10 );
  /* #21: @12 = sin(@11) */
  w12 = sin( w11 );
  /* #22: @13 = (@8*@12) */
  w13  = (w8*w12);
  /* #23: output[0][2] = @13 */
  if (res[0]) res[0][2] = w13;
  /* #24: @13 = input[3][0] */
  w13 = arg[3] ? arg[3][0] : 0;
  /* #25: output[0][3] = @13 */
  if (res[0]) res[0][3] = w13;
  /* #26: @14 = input[1][0] */
  casadi_copy(arg[1], 16, w14);
  /* #27: {@15, @16, @17, @18} = horzsplit(@14) */
  casadi_copy(w14, 4, w15);
  casadi_copy(w14+4, 4, w16);
  casadi_copy(w14+8, 4, w17);
  casadi_copy(w14+12, 4, w18);
  /* #28: {NULL, @13, @19} = vertsplit(@15) */
  w13 = w15[2];
  w19 = w15[3];
  /* #29: @20 = (@7*@19) */
  w20  = (w7*w19);
  /* #30: @21 = sin(@6) */
  w21 = sin( w6 );
  /* #31: @22 = (@21*@13) */
  w22  = (w21*w13);
  /* #32: @22 = (@0*@22) */
  w22  = (w0*w22);
  /* #33: @20 = (@20-@22) */
  w20 -= w22;
  /* #34: output[1][0] = @20 */
  if (res[1]) res[1][0] = w20;
  /* #35: @20 = (@5*@19) */
  w20  = (w5*w19);
  /* #36: @22 = cos(@1) */
  w22 = cos( w1 );
  /* #37: @13 = (@22*@13) */
  w13  = (w22*w13);
  /* #38: @13 = (@0*@13) */
  w13  = (w0*w13);
  /* #39: @20 = (@20+@13) */
  w20 += w13;
  /* #40: output[1][1] = @20 */
  if (res[1]) res[1][1] = w20;
  /* #41: @20 = 0.636943 */
  w20 = 6.3694267515923564e-01;
  /* #42: @19 = (@20*@19) */
  w19  = (w20*w19);
  /* #43: @19 = (@12*@19) */
  w19  = (w12*w19);
  /* #44: output[1][2] = @19 */
  if (res[1]) res[1][2] = w19;
  /* #45: {NULL, @19, @13} = vertsplit(@16) */
  w19 = w16[2];
  w13 = w16[3];
  /* #46: @23 = (@7*@13) */
  w23  = (w7*w13);
  /* #47: @24 = (@21*@19) */
  w24  = (w21*w19);
  /* #48: @24 = (@0*@24) */
  w24  = (w0*w24);
  /* #49: @23 = (@23-@24) */
  w23 -= w24;
  /* #50: output[1][3] = @23 */
  if (res[1]) res[1][3] = w23;
  /* #51: @23 = (@5*@13) */
  w23  = (w5*w13);
  /* #52: @19 = (@22*@19) */
  w19  = (w22*w19);
  /* #53: @19 = (@0*@19) */
  w19  = (w0*w19);
  /* #54: @23 = (@23+@19) */
  w23 += w19;
  /* #55: output[1][4] = @23 */
  if (res[1]) res[1][4] = w23;
  /* #56: @13 = (@20*@13) */
  w13  = (w20*w13);
  /* #57: @13 = (@12*@13) */
  w13  = (w12*w13);
  /* #58: output[1][5] = @13 */
  if (res[1]) res[1][5] = w13;
  /* #59: {NULL, @13, @23} = vertsplit(@17) */
  w13 = w17[2];
  w23 = w17[3];
  /* #60: @19 = (@7*@23) */
  w19  = (w7*w23);
  /* #61: @24 = (@21*@13) */
  w24  = (w21*w13);
  /* #62: @24 = (@0*@24) */
  w24  = (w0*w24);
  /* #63: @19 = (@19-@24) */
  w19 -= w24;
  /* #64: output[1][6] = @19 */
  if (res[1]) res[1][6] = w19;
  /* #65: @19 = (@5*@23) */
  w19  = (w5*w23);
  /* #66: @13 = (@22*@13) */
  w13  = (w22*w13);
  /* #67: @13 = (@0*@13) */
  w13  = (w0*w13);
  /* #68: @19 = (@19+@13) */
  w19 += w13;
  /* #69: output[1][7] = @19 */
  if (res[1]) res[1][7] = w19;
  /* #70: @23 = (@20*@23) */
  w23  = (w20*w23);
  /* #71: @23 = (@12*@23) */
  w23  = (w12*w23);
  /* #72: output[1][8] = @23 */
  if (res[1]) res[1][8] = w23;
  /* #73: {NULL, @23, @19} = vertsplit(@18) */
  w23 = w18[2];
  w19 = w18[3];
  /* #74: @13 = (@7*@19) */
  w13  = (w7*w19);
  /* #75: @21 = (@21*@23) */
  w21 *= w23;
  /* #76: @21 = (@0*@21) */
  w21  = (w0*w21);
  /* #77: @13 = (@13-@21) */
  w13 -= w21;
  /* #78: output[1][9] = @13 */
  if (res[1]) res[1][9] = w13;
  /* #79: @13 = (@5*@19) */
  w13  = (w5*w19);
  /* #80: @22 = (@22*@23) */
  w22 *= w23;
  /* #81: @22 = (@0*@22) */
  w22  = (w0*w22);
  /* #82: @13 = (@13+@22) */
  w13 += w22;
  /* #83: output[1][10] = @13 */
  if (res[1]) res[1][10] = w13;
  /* #84: @20 = (@20*@19) */
  w20 *= w19;
  /* #85: @20 = (@12*@20) */
  w20  = (w12*w20);
  /* #86: output[1][11] = @20 */
  if (res[1]) res[1][11] = w20;
  /* #87: @18 = zeros(2x4,4nz) */
  casadi_clear(w18, 4);
  /* #88: @20 = sin(@6) */
  w20 = sin( w6 );
  /* #89: @25 = ones(2x1) */
  casadi_fill(w25, 2, 1.);
  /* #90: {@19, @13} = vertsplit(@25) */
  w19 = w25[0];
  w13 = w25[1];
  /* #91: @22 = cos(@3) */
  w22 = cos( w3 );
  /* #92: @22 = sq(@22) */
  w22 = casadi_sq( w22 );
  /* #93: @22 = (@13/@22) */
  w22  = (w13/w22);
  /* #94: @2 = (@2*@22) */
  w2 *= w22;
  /* #95: @22 = 1 */
  w22 = 1.;
  /* #96: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #97: @22 = (@22+@4) */
  w22 += w4;
  /* #98: @2 = (@2/@22) */
  w2 /= w22;
  /* #99: @20 = (@20*@2) */
  w20 *= w2;
  /* #100: @20 = (@0*@20) */
  w20  = (w0*w20);
  /* #101: @20 = (-@20) */
  w20 = (- w20 );
  /* #102: @22 = cos(@1) */
  w22 = cos( w1 );
  /* #103: @22 = (@22*@2) */
  w22 *= w2;
  /* #104: @22 = (@0*@22) */
  w22  = (w0*w22);
  /* #105: @11 = cos(@11) */
  w11 = cos( w11 );
  /* #106: @3 = cos(@3) */
  w3 = cos( w3 );
  /* #107: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #108: @13 = (@13/@3) */
  w13 /= w3;
  /* #109: @9 = (@9*@13) */
  w9 *= w13;
  /* #110: @13 = 1 */
  w13 = 1.;
  /* #111: @10 = sq(@10) */
  w10 = casadi_sq( w10 );
  /* #112: @13 = (@13+@10) */
  w13 += w10;
  /* #113: @9 = (@9/@13) */
  w9 /= w13;
  /* #114: @11 = (@11*@9) */
  w11 *= w9;
  /* #115: @8 = (@8*@11) */
  w8 *= w11;
  /* #116: @17 = vertcat(@20, @22, @8, @19) */
  rr=w17;
  *rr++ = w20;
  *rr++ = w22;
  *rr++ = w8;
  *rr++ = w19;
  /* #117: (@18[:4] = @17) */
  for (rr=w18+0, ss=w17; rr!=w18+4; rr+=1) *rr = *ss++;
  /* #118: @17 = @18' */
  casadi_trans(w18,casadi_s1, w17, casadi_s0, iw);
  /* #119: @26 = project(@17) */
  casadi_project(w17, casadi_s0, w26, casadi_s2, w);
  /* #120: @27 = input[2][0] */
  casadi_copy(arg[2], 8, w27);
  /* #121: {@17, @18} = horzsplit(@27) */
  casadi_copy(w27, 4, w17);
  casadi_copy(w27+4, 4, w18);
  /* #122: {NULL, @20, @22} = vertsplit(@17) */
  w20 = w17[2];
  w22 = w17[3];
  /* #123: @8 = (@7*@22) */
  w8  = (w7*w22);
  /* #124: @6 = sin(@6) */
  w6 = sin( w6 );
  /* #125: @19 = (@6*@20) */
  w19  = (w6*w20);
  /* #126: @19 = (@0*@19) */
  w19  = (w0*w19);
  /* #127: @8 = (@8-@19) */
  w8 -= w19;
  /* #128: @19 = (@5*@22) */
  w19  = (w5*w22);
  /* #129: @1 = cos(@1) */
  w1 = cos( w1 );
  /* #130: @20 = (@1*@20) */
  w20  = (w1*w20);
  /* #131: @20 = (@0*@20) */
  w20  = (w0*w20);
  /* #132: @19 = (@19+@20) */
  w19 += w20;
  /* #133: @20 = 0.636943 */
  w20 = 6.3694267515923564e-01;
  /* #134: @22 = (@20*@22) */
  w22  = (w20*w22);
  /* #135: @22 = (@12*@22) */
  w22  = (w12*w22);
  /* #136: @28 = 00 */
  /* #137: @29 = vertcat(@8, @19, @22, @28) */
  rr=w29;
  *rr++ = w8;
  *rr++ = w19;
  *rr++ = w22;
  /* #138: {NULL, @8, @19} = vertsplit(@18) */
  w8 = w18[2];
  w19 = w18[3];
  /* #139: @7 = (@7*@19) */
  w7 *= w19;
  /* #140: @6 = (@6*@8) */
  w6 *= w8;
  /* #141: @6 = (@0*@6) */
  w6  = (w0*w6);
  /* #142: @7 = (@7-@6) */
  w7 -= w6;
  /* #143: @5 = (@5*@19) */
  w5 *= w19;
  /* #144: @1 = (@1*@8) */
  w1 *= w8;
  /* #145: @0 = (@0*@1) */
  w0 *= w1;
  /* #146: @5 = (@5+@0) */
  w5 += w0;
  /* #147: @20 = (@20*@19) */
  w20 *= w19;
  /* #148: @12 = (@12*@20) */
  w12 *= w20;
  /* #149: @28 = 00 */
  /* #150: @30 = vertcat(@7, @5, @12, @28) */
  rr=w30;
  *rr++ = w7;
  *rr++ = w5;
  *rr++ = w12;
  /* #151: @31 = horzcat(@29, @30) */
  rr=w31;
  for (i=0, cs=w29; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<3; ++i) *rr++ = *cs++;
  /* #152: @32 = project(@31) */
  casadi_project(w31, casadi_s3, w32, casadi_s2, w);
  /* #153: @26 = (@26+@32) */
  for (i=0, rr=w26, cs=w32; i<7; ++i) (*rr++) += (*cs++);
  /* #154: output[2][0] = @26 */
  casadi_copy(w26, 7, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int sim_car_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int sim_car_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int sim_car_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void sim_car_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int sim_car_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void sim_car_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void sim_car_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void sim_car_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int sim_car_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int sim_car_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real sim_car_expl_vde_forw_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* sim_car_expl_vde_forw_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* sim_car_expl_vde_forw_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* sim_car_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* sim_car_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s9;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int sim_car_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 92;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
