/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) sim_car_impl_dae_fun_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_low CASADI_PREFIX(low)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[1] = {0};
static const casadi_int casadi_s1[1] = {1};
static const casadi_int casadi_s2[1] = {3};
static const casadi_int casadi_s3[2] = {0, 9};
static const casadi_int casadi_s4[1] = {2};
static const casadi_int casadi_s5[2] = {0, 7};
static const casadi_int casadi_s6[5] = {0, 8, 17, 21, 25};
static const casadi_int casadi_s7[3] = {2, 5, 10};
static const casadi_int casadi_s8[6] = {3, 6, 11, 14, 18, 22};
static const casadi_int casadi_s9[6] = {4, 7, 12, 15, 19, 23};
static const casadi_int casadi_s10[4] = {13, 16, 20, 24};
static const casadi_int casadi_s11[36] = {7, 7, 0, 2, 4, 7, 13, 19, 23, 26, 0, 2, 0, 2, 0, 1, 2, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 2, 3, 4, 5, 3, 4, 5};
static const casadi_int casadi_s12[36] = {7, 7, 0, 5, 8, 14, 18, 22, 26, 26, 0, 1, 2, 3, 4, 2, 3, 4, 0, 1, 2, 3, 4, 5, 3, 4, 5, 6, 3, 4, 5, 6, 3, 4, 5, 6};
static const casadi_int casadi_s13[17] = {7, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s14[3] = {0, 1, 3};
static const casadi_int casadi_s15[3] = {2, 4, 5};
static const casadi_int casadi_s16[11] = {7, 2, 0, 3, 6, 3, 4, 5, 4, 5, 6};
static const casadi_int casadi_s17[16] = {2, 7, 0, 0, 0, 0, 1, 3, 5, 6, 0, 0, 1, 0, 1, 1};
static const casadi_int casadi_s18[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s19[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s20[3] = {0, 0, 0};
static const casadi_int casadi_s21[3] = {7, 0, 0};

static const casadi_real casadi_c0[5] = {1.0000000000000019e-06, 9.9999999999999995e-07, 1.0000000000000002e-06, 1.0000000000000002e-06, 1.0000000000000019e-06};
static const casadi_real casadi_c1[9] = {0., 0., 0., 0., 2., 4., 4., 4., 4.};
static const casadi_real casadi_c2[4] = {-2.7528570785764761e-21, 1.0587911840678754e-22, 0., 2.5410988417629010e-21};
static const casadi_real casadi_c3[7] = {0., 0., 0., 2., 4., 4., 4.};

/* kapparef_s:(x)->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c1,casadi_s3,casadi_s2,casadi_s1,casadi_c0,1,(&w0),casadi_s0, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_kapparef_s:(x,out_f[1x1,0nz],fwd_x)->(fwd_f) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c3,casadi_s5,casadi_s4,casadi_s1,casadi_c2,1,(&w0),casadi_s0, iw, w);
  /* #2: @0 = input[2][0] */
  w0 = arg[2] ? arg[2][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* sim_car_impl_dae_fun_jac_x_xdot_u_z:(i0[7],i1[7],i2[2],i3[],i4[])->(o0[7],o1[7x7,26nz],o2[7x7,7nz],o3[7x2,6nz],o4[7x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+5, *rr, *ss;
  const casadi_int *cii;
  const casadi_real **arg1=arg+5, *cs;
  casadi_real *w0=w+12, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35, w36, w37, w38, w39, w40, w41, w42, w43, w44, w45, w46, w47, w48, w49, w50, w51, w52, w53, w54, w55, w56, w57, w58, w59, w60, w61, w62, w63, w64, w65, w66, w67, w68, w69, w70, w71, w72, w73, w74, w75, w76, w77, w78, w79, w80, w81, w82, w83, w84, w85, w86, w87, w88, w89, w90, w91, w92, w93, w94, w95, w96, w97, w98, w99, w100, w101, w102, w103, w104, w105, w106, w107, w108, w109, w110, w111, w112, w113, w114, w115, w116, w117, w118, *w119=w+137, *w120=w+144, *w122=w+170, w124, *w125=w+173, *w126=w+178, *w130=w+183, *w131=w+185, *w132=w+188, *w133=w+191, *w134=w+197, *w135=w+203, *w136=w+207, *w137=w+211;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 7, w0);
  /* #1: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = 3 */
  w2 = 3.;
  /* #3: @2 = (@1-@2) */
  w2  = (w1-w2);
  /* #4: @3 = 2 */
  w3 = 2.;
  /* #5: @2 = (@2/@3) */
  w2 /= w3;
  /* #6: @3 = 0 */
  w3 = 0.;
  /* #7: @4 = fmax(@2,@3) */
  w4  = casadi_fmax(w2,w3);
  /* #8: @5 = 1 */
  w5 = 1.;
  /* #9: @6 = fmin(@4,@5) */
  w6  = casadi_fmin(w4,w5);
  /* #10: @7 = input[0][2] */
  w7 = arg[0] ? arg[0][2] : 0;
  /* #11: @8 = cos(@7) */
  w8 = cos( w7 );
  /* #12: @9 = (@1*@8) */
  w9  = (w1*w8);
  /* #13: @10 = input[0][4] */
  w10 = arg[0] ? arg[0][4] : 0;
  /* #14: @11 = sin(@7) */
  w11 = sin( w7 );
  /* #15: @12 = (@10*@11) */
  w12  = (w10*w11);
  /* #16: @9 = (@9-@12) */
  w9 -= w12;
  /* #17: @12 = 1 */
  w12 = 1.;
  /* #18: @13 = input[0][1] */
  w13 = arg[0] ? arg[0][1] : 0;
  /* #19: @14 = input[0][0] */
  w14 = arg[0] ? arg[0][0] : 0;
  /* #20: @15 = kapparef_s(@14) */
  arg1[0]=(&w14);
  res1[0]=(&w15);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #21: @16 = (@13*@15) */
  w16  = (w13*w15);
  /* #22: @12 = (@12-@16) */
  w12 -= w16;
  /* #23: @9 = (@9/@12) */
  w9 /= w12;
  /* #24: @16 = (@6*@9) */
  w16  = (w6*w9);
  /* #25: @17 = 1 */
  w17 = 1.;
  /* #26: @17 = (@17-@6) */
  w17 -= w6;
  /* #27: @18 = cos(@7) */
  w18 = cos( w7 );
  /* #28: @19 = (@1*@18) */
  w19  = (w1*w18);
  /* #29: @20 = sin(@7) */
  w20 = sin( w7 );
  /* #30: @21 = (@10*@20) */
  w21  = (w10*w20);
  /* #31: @19 = (@19-@21) */
  w19 -= w21;
  /* #32: @21 = 1 */
  w21 = 1.;
  /* #33: @22 = kapparef_s(@14) */
  arg1[0]=(&w14);
  res1[0]=(&w22);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #34: @23 = (@13*@22) */
  w23  = (w13*w22);
  /* #35: @21 = (@21-@23) */
  w21 -= w23;
  /* #36: @19 = (@19/@21) */
  w19 /= w21;
  /* #37: @23 = (@17*@19) */
  w23  = (w17*w19);
  /* #38: @16 = (@16+@23) */
  w16 += w23;
  /* #39: @23 = 3 */
  w23 = 3.;
  /* #40: @23 = (@1-@23) */
  w23  = (w1-w23);
  /* #41: @24 = 2 */
  w24 = 2.;
  /* #42: @23 = (@23/@24) */
  w23 /= w24;
  /* #43: @24 = 0 */
  w24 = 0.;
  /* #44: @25 = fmax(@23,@24) */
  w25  = casadi_fmax(w23,w24);
  /* #45: @26 = 1 */
  w26 = 1.;
  /* #46: @27 = fmin(@25,@26) */
  w27  = casadi_fmin(w25,w26);
  /* #47: @28 = sin(@7) */
  w28 = sin( w7 );
  /* #48: @29 = (@1*@28) */
  w29  = (w1*w28);
  /* #49: @30 = cos(@7) */
  w30 = cos( w7 );
  /* #50: @31 = (@10*@30) */
  w31  = (w10*w30);
  /* #51: @29 = (@29+@31) */
  w29 += w31;
  /* #52: @31 = (@27*@29) */
  w31  = (w27*w29);
  /* #53: @32 = 1 */
  w32 = 1.;
  /* #54: @32 = (@32-@27) */
  w32 -= w27;
  /* #55: @33 = sin(@7) */
  w33 = sin( w7 );
  /* #56: @34 = (@1*@33) */
  w34  = (w1*w33);
  /* #57: @35 = cos(@7) */
  w35 = cos( w7 );
  /* #58: @36 = (@10*@35) */
  w36  = (w10*w35);
  /* #59: @34 = (@34+@36) */
  w34 += w36;
  /* #60: @36 = (@32*@34) */
  w36  = (w32*w34);
  /* #61: @31 = (@31+@36) */
  w31 += w36;
  /* #62: @36 = 3 */
  w36 = 3.;
  /* #63: @36 = (@1-@36) */
  w36  = (w1-w36);
  /* #64: @37 = 2 */
  w37 = 2.;
  /* #65: @36 = (@36/@37) */
  w36 /= w37;
  /* #66: @37 = 0 */
  w37 = 0.;
  /* #67: @38 = fmax(@36,@37) */
  w38  = casadi_fmax(w36,w37);
  /* #68: @39 = 1 */
  w39 = 1.;
  /* #69: @40 = fmin(@38,@39) */
  w40  = casadi_fmin(w38,w39);
  /* #70: @41 = input[0][5] */
  w41 = arg[0] ? arg[0][5] : 0;
  /* #71: @42 = kapparef_s(@14) */
  arg1[0]=(&w14);
  res1[0]=(&w42);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #72: @43 = (@13*@42) */
  w43  = (w13*w42);
  /* #73: @44 = cos(@7) */
  w44 = cos( w7 );
  /* #74: @45 = (@1*@44) */
  w45  = (w1*w44);
  /* #75: @46 = sin(@7) */
  w46 = sin( w7 );
  /* #76: @47 = (@10*@46) */
  w47  = (w10*w46);
  /* #77: @45 = (@45-@47) */
  w45 -= w47;
  /* #78: @47 = (@43*@45) */
  w47  = (w43*w45);
  /* #79: @48 = 1 */
  w48 = 1.;
  /* #80: @49 = kapparef_s(@14) */
  arg1[0]=(&w14);
  res1[0]=(&w49);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #81: @50 = (@13*@49) */
  w50  = (w13*w49);
  /* #82: @48 = (@48-@50) */
  w48 -= w50;
  /* #83: @47 = (@47/@48) */
  w47 /= w48;
  /* #84: @50 = (@41-@47) */
  w50  = (w41-w47);
  /* #85: @51 = (@40*@50) */
  w51  = (w40*w50);
  /* #86: @52 = 1 */
  w52 = 1.;
  /* #87: @52 = (@52-@40) */
  w52 -= w40;
  /* #88: @53 = kapparef_s(@14) */
  arg1[0]=(&w14);
  res1[0]=(&w53);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #89: @54 = (@13*@53) */
  w54  = (w13*w53);
  /* #90: @55 = cos(@7) */
  w55 = cos( w7 );
  /* #91: @56 = (@1*@55) */
  w56  = (w1*w55);
  /* #92: @57 = sin(@7) */
  w57 = sin( w7 );
  /* #93: @58 = (@10*@57) */
  w58  = (w10*w57);
  /* #94: @56 = (@56-@58) */
  w56 -= w58;
  /* #95: @58 = (@54*@56) */
  w58  = (w54*w56);
  /* #96: @59 = 1 */
  w59 = 1.;
  /* #97: @60 = kapparef_s(@14) */
  arg1[0]=(&w14);
  res1[0]=(&w60);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #98: @61 = (@13*@60) */
  w61  = (w13*w60);
  /* #99: @59 = (@59-@61) */
  w59 -= w61;
  /* #100: @58 = (@58/@59) */
  w58 /= w59;
  /* #101: @61 = (@41-@58) */
  w61  = (w41-w58);
  /* #102: @62 = (@52*@61) */
  w62  = (w52*w61);
  /* #103: @51 = (@51+@62) */
  w51 += w62;
  /* #104: @62 = 3 */
  w62 = 3.;
  /* #105: @62 = (@1-@62) */
  w62  = (w1-w62);
  /* #106: @63 = 2 */
  w63 = 2.;
  /* #107: @62 = (@62/@63) */
  w62 /= w63;
  /* #108: @63 = 0 */
  w63 = 0.;
  /* #109: @64 = fmax(@62,@63) */
  w64  = casadi_fmax(w62,w63);
  /* #110: @65 = 1 */
  w65 = 1.;
  /* #111: @66 = fmin(@64,@65) */
  w66  = casadi_fmin(w64,w65);
  /* #112: @67 = input[2][0] */
  w67 = arg[2] ? arg[2][0] : 0;
  /* #113: @68 = 0.0005 */
  w68 = 5.0000000000000001e-04;
  /* #114: @69 = 92731.3 */
  w69 = 9.2731265615302604e+04;
  /* #115: @70 = input[0][6] */
  w70 = arg[0] ? arg[0][6] : 0;
  /* #116: @71 = 1.4 */
  w71 = 1.3999999999999999e+00;
  /* #117: @72 = (@71*@41) */
  w72  = (w71*w41);
  /* #118: @72 = (@10+@72) */
  w72  = (w10+w72);
  /* #119: @72 = (@72/@1) */
  w72 /= w1;
  /* #120: @73 = (@70-@72) */
  w73  = (w70-w72);
  /* #121: @73 = (@69*@73) */
  w73  = (w69*w73);
  /* #122: @73 = (@68*@73) */
  w73  = (w68*w73);
  /* #123: @74 = sin(@70) */
  w74 = sin( w70 );
  /* #124: @75 = (@73*@74) */
  w75  = (w73*w74);
  /* #125: @75 = (@67-@75) */
  w75  = (w67-w75);
  /* #126: @76 = (@10*@41) */
  w76  = (w10*w41);
  /* #127: @75 = (@75+@76) */
  w75 += w76;
  /* #128: @76 = (@66*@75) */
  w76  = (w66*w75);
  /* #129: @77 = 1 */
  w77 = 1.;
  /* #130: @77 = (@77-@66) */
  w77 -= w66;
  /* #131: @78 = (@77*@67) */
  w78  = (w77*w67);
  /* #132: @76 = (@76+@78) */
  w76 += w78;
  /* #133: @78 = 3 */
  w78 = 3.;
  /* #134: @78 = (@1-@78) */
  w78  = (w1-w78);
  /* #135: @79 = 2 */
  w79 = 2.;
  /* #136: @78 = (@78/@79) */
  w78 /= w79;
  /* #137: @79 = 0 */
  w79 = 0.;
  /* #138: @80 = fmax(@78,@79) */
  w80  = casadi_fmax(w78,w79);
  /* #139: @81 = 1 */
  w81 = 1.;
  /* #140: @82 = fmin(@80,@81) */
  w82  = casadi_fmin(w80,w81);
  /* #141: @83 = 0.0005 */
  w83 = 5.0000000000000001e-04;
  /* #142: @84 = 92731.3 */
  w84 = 9.2731265615302604e+04;
  /* #143: @85 = 1.4 */
  w85 = 1.3999999999999999e+00;
  /* #144: @86 = (@85*@41) */
  w86  = (w85*w41);
  /* #145: @86 = (@86-@10) */
  w86 -= w10;
  /* #146: @86 = (@84*@86) */
  w86  = (w84*w86);
  /* #147: @86 = (@86/@1) */
  w86 /= w1;
  /* #148: @87 = 92731.3 */
  w87 = 9.2731265615302604e+04;
  /* #149: @88 = 1.4 */
  w88 = 1.3999999999999999e+00;
  /* #150: @89 = (@88*@41) */
  w89  = (w88*w41);
  /* #151: @89 = (@10+@89) */
  w89  = (w10+w89);
  /* #152: @89 = (@89/@1) */
  w89 /= w1;
  /* #153: @90 = (@70-@89) */
  w90  = (w70-w89);
  /* #154: @90 = (@87*@90) */
  w90  = (w87*w90);
  /* #155: @91 = cos(@70) */
  w91 = cos( w70 );
  /* #156: @92 = (@90*@91) */
  w92  = (w90*w91);
  /* #157: @92 = (@86+@92) */
  w92  = (w86+w92);
  /* #158: @92 = (@83*@92) */
  w92  = (w83*w92);
  /* #159: @93 = (@1*@41) */
  w93  = (w1*w41);
  /* #160: @92 = (@92-@93) */
  w92 -= w93;
  /* #161: @93 = (@82*@92) */
  w93  = (w82*w92);
  /* #162: @94 = 1 */
  w94 = 1.;
  /* #163: @94 = (@94-@82) */
  w94 -= w82;
  /* #164: @95 = 1.4 */
  w95 = 1.3999999999999999e+00;
  /* #165: @96 = input[2][1] */
  w96 = arg[2] ? arg[2][1] : 0;
  /* #166: @97 = (@96*@1) */
  w97  = (w96*w1);
  /* #167: @98 = (@70*@67) */
  w98  = (w70*w67);
  /* #168: @97 = (@97+@98) */
  w97 += w98;
  /* #169: @97 = (@95*@97) */
  w97  = (w95*w97);
  /* #170: @98 = 2.8 */
  w98 = 2.7999999999999998e+00;
  /* #171: @97 = (@97/@98) */
  w97 /= w98;
  /* #172: @98 = (@94*@97) */
  w98  = (w94*w97);
  /* #173: @93 = (@93+@98) */
  w93 += w98;
  /* #174: @98 = 3 */
  w98 = 3.;
  /* #175: @98 = (@1-@98) */
  w98  = (w1-w98);
  /* #176: @99 = 2 */
  w99 = 2.;
  /* #177: @98 = (@98/@99) */
  w98 /= w99;
  /* #178: @99 = 0 */
  w99 = 0.;
  /* #179: @100 = fmax(@98,@99) */
  w100  = casadi_fmax(w98,w99);
  /* #180: @101 = 1 */
  w101 = 1.;
  /* #181: @102 = fmin(@100,@101) */
  w102  = casadi_fmin(w100,w101);
  /* #182: @103 = 0.000255102 */
  w103 = 2.5510204081632655e-04;
  /* #183: @104 = 1.4 */
  w104 = 1.3999999999999999e+00;
  /* #184: @105 = 92731.3 */
  w105 = 9.2731265615302604e+04;
  /* #185: @106 = 1.4 */
  w106 = 1.3999999999999999e+00;
  /* #186: @107 = (@106*@41) */
  w107  = (w106*w41);
  /* #187: @107 = (@10+@107) */
  w107  = (w10+w107);
  /* #188: @107 = (@107/@1) */
  w107 /= w1;
  /* #189: @108 = (@70-@107) */
  w108  = (w70-w107);
  /* #190: @108 = (@105*@108) */
  w108  = (w105*w108);
  /* #191: @108 = (@104*@108) */
  w108  = (w104*w108);
  /* #192: @109 = cos(@70) */
  w109 = cos( w70 );
  /* #193: @110 = (@108*@109) */
  w110  = (w108*w109);
  /* #194: @111 = 1.4 */
  w111 = 1.3999999999999999e+00;
  /* #195: @112 = 92731.3 */
  w112 = 9.2731265615302604e+04;
  /* #196: @113 = 1.4 */
  w113 = 1.3999999999999999e+00;
  /* #197: @114 = (@113*@41) */
  w114  = (w113*w41);
  /* #198: @114 = (@114-@10) */
  w114 -= w10;
  /* #199: @114 = (@112*@114) */
  w114  = (w112*w114);
  /* #200: @114 = (@114/@1) */
  w114 /= w1;
  /* #201: @115 = (@111*@114) */
  w115  = (w111*w114);
  /* #202: @110 = (@110-@115) */
  w110 -= w115;
  /* #203: @110 = (@103*@110) */
  w110  = (w103*w110);
  /* #204: @115 = (@102*@110) */
  w115  = (w102*w110);
  /* #205: @116 = 1 */
  w116 = 1.;
  /* #206: @116 = (@116-@102) */
  w116 -= w102;
  /* #207: @117 = (@96*@1) */
  w117  = (w96*w1);
  /* #208: @118 = (@70*@67) */
  w118  = (w70*w67);
  /* #209: @117 = (@117+@118) */
  w117 += w118;
  /* #210: @118 = 2.8 */
  w118 = 2.7999999999999998e+00;
  /* #211: @117 = (@117/@118) */
  w117 /= w118;
  /* #212: @118 = (@116*@117) */
  w118  = (w116*w117);
  /* #213: @115 = (@115+@118) */
  w115 += w118;
  /* #214: @119 = vertcat(@16, @31, @51, @76, @93, @115, @96) */
  rr=w119;
  *rr++ = w16;
  *rr++ = w31;
  *rr++ = w51;
  *rr++ = w76;
  *rr++ = w93;
  *rr++ = w115;
  *rr++ = w96;
  /* #215: @0 = (@0-@119) */
  for (i=0, rr=w0, cs=w119; i<7; ++i) (*rr++) -= (*cs++);
  /* #216: output[0][0] = @0 */
  casadi_copy(w0, 7, res[0]);
  /* #217: @120 = zeros(7x7,26nz) */
  casadi_clear(w120, 26);
  /* #218: @16 = (@9/@12) */
  w16  = (w9/w12);
  /* #219: @121 = 00 */
  /* #220: @122 = ones(7x1,2nz) */
  casadi_fill(w122, 2, 1.);
  /* #221: {@31, NULL, NULL, NULL, NULL, NULL, @51} = vertsplit(@122) */
  w31 = w122[0];
  w51 = w122[1];
  /* #222: @76 = fwd1_kapparef_s(@14, @121, @31) */
  arg1[0]=(&w14);
  arg1[1]=0;
  arg1[2]=(&w31);
  res1[0]=(&w76);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #223: @76 = (@13*@76) */
  w76  = (w13*w76);
  /* #224: @76 = (@16*@76) */
  w76  = (w16*w76);
  /* #225: @76 = (@6*@76) */
  w76  = (w6*w76);
  /* #226: @93 = (@19/@21) */
  w93  = (w19/w21);
  /* #227: @121 = 00 */
  /* #228: @115 = fwd1_kapparef_s(@14, @121, @31) */
  arg1[0]=(&w14);
  arg1[1]=0;
  arg1[2]=(&w31);
  res1[0]=(&w115);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #229: @115 = (@13*@115) */
  w115  = (w13*w115);
  /* #230: @115 = (@93*@115) */
  w115  = (w93*w115);
  /* #231: @115 = (@17*@115) */
  w115  = (w17*w115);
  /* #232: @76 = (@76+@115) */
  w76 += w115;
  /* #233: @121 = 00 */
  /* #234: @123 = 00 */
  /* #235: @115 = fwd1_kapparef_s(@14, @123, @31) */
  arg1[0]=(&w14);
  arg1[1]=0;
  arg1[2]=(&w31);
  res1[0]=(&w115);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #236: @115 = (@13*@115) */
  w115  = (w13*w115);
  /* #237: @115 = (@56*@115) */
  w115  = (w56*w115);
  /* #238: @115 = (@115/@59) */
  w115 /= w59;
  /* #239: @58 = (@58/@59) */
  w58 /= w59;
  /* #240: @123 = 00 */
  /* #241: @118 = fwd1_kapparef_s(@14, @123, @31) */
  arg1[0]=(&w14);
  arg1[1]=0;
  arg1[2]=(&w31);
  res1[0]=(&w118);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #242: @118 = (@13*@118) */
  w118  = (w13*w118);
  /* #243: @118 = (@58*@118) */
  w118  = (w58*w118);
  /* #244: @115 = (@115+@118) */
  w115 += w118;
  /* #245: @115 = (@52*@115) */
  w115  = (w52*w115);
  /* #246: @115 = (-@115) */
  w115 = (- w115 );
  /* #247: @123 = 00 */
  /* #248: @118 = fwd1_kapparef_s(@14, @123, @31) */
  arg1[0]=(&w14);
  arg1[1]=0;
  arg1[2]=(&w31);
  res1[0]=(&w118);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #249: @118 = (@13*@118) */
  w118  = (w13*w118);
  /* #250: @118 = (@45*@118) */
  w118  = (w45*w118);
  /* #251: @118 = (@118/@48) */
  w118 /= w48;
  /* #252: @47 = (@47/@48) */
  w47 /= w48;
  /* #253: @123 = 00 */
  /* #254: @124 = fwd1_kapparef_s(@14, @123, @31) */
  arg1[0]=(&w14);
  arg1[1]=0;
  arg1[2]=(&w31);
  res1[0]=(&w124);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #255: @13 = (@13*@124) */
  w13 *= w124;
  /* #256: @13 = (@47*@13) */
  w13  = (w47*w13);
  /* #257: @118 = (@118+@13) */
  w118 += w13;
  /* #258: @118 = (@40*@118) */
  w118  = (w40*w118);
  /* #259: @115 = (@115-@118) */
  w115 -= w118;
  /* #260: @118 = (@69*@51) */
  w118  = (w69*w51);
  /* #261: @118 = (@68*@118) */
  w118  = (w68*w118);
  /* #262: @118 = (@74*@118) */
  w118  = (w74*w118);
  /* #263: @13 = cos(@70) */
  w13 = cos( w70 );
  /* #264: @13 = (@13*@51) */
  w13 *= w51;
  /* #265: @73 = (@73*@13) */
  w73 *= w13;
  /* #266: @118 = (@118+@73) */
  w118 += w73;
  /* #267: @118 = (@66*@118) */
  w118  = (w66*w118);
  /* #268: @118 = (-@118) */
  w118 = (- w118 );
  /* #269: @73 = (@87*@51) */
  w73  = (w87*w51);
  /* #270: @73 = (@91*@73) */
  w73  = (w91*w73);
  /* #271: @13 = sin(@70) */
  w13 = sin( w70 );
  /* #272: @13 = (@13*@51) */
  w13 *= w51;
  /* #273: @90 = (@90*@13) */
  w90 *= w13;
  /* #274: @73 = (@73-@90) */
  w73 -= w90;
  /* #275: @73 = (@83*@73) */
  w73  = (w83*w73);
  /* #276: @73 = (@82*@73) */
  w73  = (w82*w73);
  /* #277: @90 = 0.357143 */
  w90 = 3.5714285714285715e-01;
  /* #278: @13 = (@67*@51) */
  w13  = (w67*w51);
  /* #279: @13 = (@95*@13) */
  w13  = (w95*w13);
  /* #280: @13 = (@90*@13) */
  w13  = (w90*w13);
  /* #281: @13 = (@94*@13) */
  w13  = (w94*w13);
  /* #282: @73 = (@73+@13) */
  w73 += w13;
  /* #283: @13 = (@105*@51) */
  w13  = (w105*w51);
  /* #284: @13 = (@104*@13) */
  w13  = (w104*w13);
  /* #285: @13 = (@109*@13) */
  w13  = (w109*w13);
  /* #286: @124 = sin(@70) */
  w124 = sin( w70 );
  /* #287: @124 = (@124*@51) */
  w124 *= w51;
  /* #288: @108 = (@108*@124) */
  w108 *= w124;
  /* #289: @13 = (@13-@108) */
  w13 -= w108;
  /* #290: @13 = (@103*@13) */
  w13  = (w103*w13);
  /* #291: @13 = (@102*@13) */
  w13  = (w102*w13);
  /* #292: @108 = 0.357143 */
  w108 = 3.5714285714285715e-01;
  /* #293: @51 = (@67*@51) */
  w51  = (w67*w51);
  /* #294: @51 = (@108*@51) */
  w51  = (w108*w51);
  /* #295: @51 = (@116*@51) */
  w51  = (w116*w51);
  /* #296: @13 = (@13+@51) */
  w13 += w51;
  /* #297: @123 = 00 */
  /* #298: @125 = vertcat(@76, @121, @115, @118, @73, @13, @123) */
  rr=w125;
  *rr++ = w76;
  *rr++ = w115;
  *rr++ = w118;
  *rr++ = w73;
  *rr++ = w13;
  /* #299: @125 = (-@125) */
  for (i=0, rr=w125, cs=w125; i<5; ++i) *rr++ = (- *cs++ );
  /* #300: @126 = @125[:5] */
  for (rr=w126, ss=w125+0; ss!=w125+5; ss+=1) *rr++ = *ss;
  /* #301: (@120[0, 8, 17, 21, 25] = @126) */
  for (cii=casadi_s6, rr=w120, ss=w126; cii!=casadi_s6+5; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #302: @76 = ones(7x1,1nz) */
  w76 = 1.;
  /* #303: {NULL, @115, NULL, NULL, NULL, NULL, NULL} = vertsplit(@76) */
  w115 = w76;
  /* #304: @15 = (@15*@115) */
  w15 *= w115;
  /* #305: @16 = (@16*@15) */
  w16 *= w15;
  /* #306: @16 = (@6*@16) */
  w16  = (w6*w16);
  /* #307: @22 = (@22*@115) */
  w22 *= w115;
  /* #308: @93 = (@93*@22) */
  w93 *= w22;
  /* #309: @93 = (@17*@93) */
  w93  = (w17*w93);
  /* #310: @16 = (@16+@93) */
  w16 += w93;
  /* #311: @121 = 00 */
  /* #312: @53 = (@53*@115) */
  w53 *= w115;
  /* #313: @56 = (@56*@53) */
  w56 *= w53;
  /* #314: @56 = (@56/@59) */
  w56 /= w59;
  /* #315: @60 = (@60*@115) */
  w60 *= w115;
  /* #316: @58 = (@58*@60) */
  w58 *= w60;
  /* #317: @56 = (@56+@58) */
  w56 += w58;
  /* #318: @56 = (@52*@56) */
  w56  = (w52*w56);
  /* #319: @56 = (-@56) */
  w56 = (- w56 );
  /* #320: @42 = (@42*@115) */
  w42 *= w115;
  /* #321: @45 = (@45*@42) */
  w45 *= w42;
  /* #322: @45 = (@45/@48) */
  w45 /= w48;
  /* #323: @49 = (@49*@115) */
  w49 *= w115;
  /* #324: @47 = (@47*@49) */
  w47 *= w49;
  /* #325: @45 = (@45+@47) */
  w45 += w47;
  /* #326: @45 = (@40*@45) */
  w45  = (w40*w45);
  /* #327: @56 = (@56-@45) */
  w56 -= w45;
  /* #328: @123 = 00 */
  /* #329: @127 = 00 */
  /* #330: @128 = 00 */
  /* #331: @129 = 00 */
  /* #332: @122 = vertcat(@16, @121, @56, @123, @127, @128, @129) */
  rr=w122;
  *rr++ = w16;
  *rr++ = w56;
  /* #333: @122 = (-@122) */
  for (i=0, rr=w122, cs=w122; i<2; ++i) *rr++ = (- *cs++ );
  /* #334: @130 = @122[:2] */
  for (rr=w130, ss=w122+0; ss!=w122+2; ss+=1) *rr++ = *ss;
  /* #335: (@120[1:17:8] = @130) */
  for (rr=w120+1, ss=w130; rr!=w120+17; rr+=8) *rr = *ss++;
  /* #336: @16 = cos(@7) */
  w16 = cos( w7 );
  /* #337: @56 = ones(7x1,1nz) */
  w56 = 1.;
  /* #338: {NULL, NULL, @45, NULL, NULL, NULL, NULL} = vertsplit(@56) */
  w45 = w56;
  /* #339: @16 = (@16*@45) */
  w16 *= w45;
  /* #340: @16 = (@10*@16) */
  w16  = (w10*w16);
  /* #341: @16 = (-@16) */
  w16 = (- w16 );
  /* #342: @56 = sin(@7) */
  w56 = sin( w7 );
  /* #343: @56 = (@56*@45) */
  w56 *= w45;
  /* #344: @56 = (@1*@56) */
  w56  = (w1*w56);
  /* #345: @16 = (@16-@56) */
  w16 -= w56;
  /* #346: @16 = (@16/@12) */
  w16 /= w12;
  /* #347: @16 = (@6*@16) */
  w16  = (w6*w16);
  /* #348: @56 = cos(@7) */
  w56 = cos( w7 );
  /* #349: @56 = (@56*@45) */
  w56 *= w45;
  /* #350: @56 = (@10*@56) */
  w56  = (w10*w56);
  /* #351: @56 = (-@56) */
  w56 = (- w56 );
  /* #352: @47 = sin(@7) */
  w47 = sin( w7 );
  /* #353: @47 = (@47*@45) */
  w47 *= w45;
  /* #354: @47 = (@1*@47) */
  w47  = (w1*w47);
  /* #355: @56 = (@56-@47) */
  w56 -= w47;
  /* #356: @56 = (@56/@21) */
  w56 /= w21;
  /* #357: @56 = (@17*@56) */
  w56  = (w17*w56);
  /* #358: @16 = (@16+@56) */
  w16 += w56;
  /* #359: @56 = cos(@7) */
  w56 = cos( w7 );
  /* #360: @56 = (@56*@45) */
  w56 *= w45;
  /* #361: @56 = (@1*@56) */
  w56  = (w1*w56);
  /* #362: @47 = sin(@7) */
  w47 = sin( w7 );
  /* #363: @47 = (@47*@45) */
  w47 *= w45;
  /* #364: @47 = (@10*@47) */
  w47  = (w10*w47);
  /* #365: @56 = (@56-@47) */
  w56 -= w47;
  /* #366: @56 = (@27*@56) */
  w56  = (w27*w56);
  /* #367: @47 = cos(@7) */
  w47 = cos( w7 );
  /* #368: @47 = (@47*@45) */
  w47 *= w45;
  /* #369: @47 = (@1*@47) */
  w47  = (w1*w47);
  /* #370: @49 = sin(@7) */
  w49 = sin( w7 );
  /* #371: @49 = (@49*@45) */
  w49 *= w45;
  /* #372: @49 = (@10*@49) */
  w49  = (w10*w49);
  /* #373: @47 = (@47-@49) */
  w47 -= w49;
  /* #374: @47 = (@32*@47) */
  w47  = (w32*w47);
  /* #375: @56 = (@56+@47) */
  w56 += w47;
  /* #376: @47 = cos(@7) */
  w47 = cos( w7 );
  /* #377: @47 = (@47*@45) */
  w47 *= w45;
  /* #378: @47 = (@10*@47) */
  w47  = (w10*w47);
  /* #379: @47 = (-@47) */
  w47 = (- w47 );
  /* #380: @49 = sin(@7) */
  w49 = sin( w7 );
  /* #381: @49 = (@49*@45) */
  w49 *= w45;
  /* #382: @49 = (@1*@49) */
  w49  = (w1*w49);
  /* #383: @47 = (@47-@49) */
  w47 -= w49;
  /* #384: @47 = (@54*@47) */
  w47  = (w54*w47);
  /* #385: @47 = (@47/@59) */
  w47 /= w59;
  /* #386: @47 = (@52*@47) */
  w47  = (w52*w47);
  /* #387: @47 = (-@47) */
  w47 = (- w47 );
  /* #388: @49 = cos(@7) */
  w49 = cos( w7 );
  /* #389: @49 = (@49*@45) */
  w49 *= w45;
  /* #390: @49 = (@10*@49) */
  w49  = (w10*w49);
  /* #391: @49 = (-@49) */
  w49 = (- w49 );
  /* #392: @7 = sin(@7) */
  w7 = sin( w7 );
  /* #393: @7 = (@7*@45) */
  w7 *= w45;
  /* #394: @7 = (@1*@7) */
  w7  = (w1*w7);
  /* #395: @49 = (@49-@7) */
  w49 -= w7;
  /* #396: @49 = (@43*@49) */
  w49  = (w43*w49);
  /* #397: @49 = (@49/@48) */
  w49 /= w48;
  /* #398: @49 = (@40*@49) */
  w49  = (w40*w49);
  /* #399: @47 = (@47-@49) */
  w47 -= w49;
  /* #400: @121 = 00 */
  /* #401: @123 = 00 */
  /* #402: @127 = 00 */
  /* #403: @128 = 00 */
  /* #404: @131 = vertcat(@16, @56, @47, @121, @123, @127, @128) */
  rr=w131;
  *rr++ = w16;
  *rr++ = w56;
  *rr++ = w47;
  /* #405: @131 = (-@131) */
  for (i=0, rr=w131, cs=w131; i<3; ++i) *rr++ = (- *cs++ );
  /* #406: @132 = @131[:3] */
  for (rr=w132, ss=w131+0; ss!=w131+3; ss+=1) *rr++ = *ss;
  /* #407: (@120[2, 5, 10] = @132) */
  for (cii=casadi_s7, rr=w120, ss=w132; cii!=casadi_s7+3; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #408: @4 = (@4<=@5) */
  w4  = (w4<=w5);
  /* #409: @3 = (@3<=@2) */
  w3  = (w3<=w2);
  /* #410: @2 = 0.5 */
  w2 = 5.0000000000000000e-01;
  /* #411: @5 = ones(7x1,1nz) */
  w5 = 1.;
  /* #412: {NULL, NULL, NULL, @16, NULL, NULL, NULL} = vertsplit(@5) */
  w16 = w5;
  /* #413: @2 = (@2*@16) */
  w2 *= w16;
  /* #414: @3 = (@3*@2) */
  w3 *= w2;
  /* #415: @4 = (@4*@3) */
  w4 *= w3;
  /* #416: @9 = (@9*@4) */
  w9 *= w4;
  /* #417: @8 = (@8*@16) */
  w8 *= w16;
  /* #418: @8 = (@8/@12) */
  w8 /= w12;
  /* #419: @8 = (@6*@8) */
  w8  = (w6*w8);
  /* #420: @9 = (@9+@8) */
  w9 += w8;
  /* #421: @18 = (@18*@16) */
  w18 *= w16;
  /* #422: @18 = (@18/@21) */
  w18 /= w21;
  /* #423: @18 = (@17*@18) */
  w18  = (w17*w18);
  /* #424: @19 = (@19*@4) */
  w19 *= w4;
  /* #425: @18 = (@18-@19) */
  w18 -= w19;
  /* #426: @9 = (@9+@18) */
  w9 += w18;
  /* #427: @25 = (@25<=@26) */
  w25  = (w25<=w26);
  /* #428: @24 = (@24<=@23) */
  w24  = (w24<=w23);
  /* #429: @23 = 0.5 */
  w23 = 5.0000000000000000e-01;
  /* #430: @23 = (@23*@16) */
  w23 *= w16;
  /* #431: @24 = (@24*@23) */
  w24 *= w23;
  /* #432: @25 = (@25*@24) */
  w25 *= w24;
  /* #433: @29 = (@29*@25) */
  w29 *= w25;
  /* #434: @28 = (@28*@16) */
  w28 *= w16;
  /* #435: @28 = (@27*@28) */
  w28  = (w27*w28);
  /* #436: @29 = (@29+@28) */
  w29 += w28;
  /* #437: @33 = (@33*@16) */
  w33 *= w16;
  /* #438: @33 = (@32*@33) */
  w33  = (w32*w33);
  /* #439: @34 = (@34*@25) */
  w34 *= w25;
  /* #440: @33 = (@33-@34) */
  w33 -= w34;
  /* #441: @29 = (@29+@33) */
  w29 += w33;
  /* #442: @38 = (@38<=@39) */
  w38  = (w38<=w39);
  /* #443: @37 = (@37<=@36) */
  w37  = (w37<=w36);
  /* #444: @36 = 0.5 */
  w36 = 5.0000000000000000e-01;
  /* #445: @36 = (@36*@16) */
  w36 *= w16;
  /* #446: @37 = (@37*@36) */
  w37 *= w36;
  /* #447: @38 = (@38*@37) */
  w38 *= w37;
  /* #448: @50 = (@50*@38) */
  w50 *= w38;
  /* #449: @44 = (@44*@16) */
  w44 *= w16;
  /* #450: @44 = (@43*@44) */
  w44  = (w43*w44);
  /* #451: @44 = (@44/@48) */
  w44 /= w48;
  /* #452: @44 = (@40*@44) */
  w44  = (w40*w44);
  /* #453: @50 = (@50-@44) */
  w50 -= w44;
  /* #454: @55 = (@55*@16) */
  w55 *= w16;
  /* #455: @55 = (@54*@55) */
  w55  = (w54*w55);
  /* #456: @55 = (@55/@59) */
  w55 /= w59;
  /* #457: @55 = (@52*@55) */
  w55  = (w52*w55);
  /* #458: @55 = (-@55) */
  w55 = (- w55 );
  /* #459: @61 = (@61*@38) */
  w61 *= w38;
  /* #460: @55 = (@55-@61) */
  w55 -= w61;
  /* #461: @50 = (@50+@55) */
  w50 += w55;
  /* #462: @64 = (@64<=@65) */
  w64  = (w64<=w65);
  /* #463: @63 = (@63<=@62) */
  w63  = (w63<=w62);
  /* #464: @62 = 0.5 */
  w62 = 5.0000000000000000e-01;
  /* #465: @62 = (@62*@16) */
  w62 *= w16;
  /* #466: @63 = (@63*@62) */
  w63 *= w62;
  /* #467: @64 = (@64*@63) */
  w64 *= w63;
  /* #468: @75 = (@75*@64) */
  w75 *= w64;
  /* #469: @72 = (@72/@1) */
  w72 /= w1;
  /* #470: @72 = (@72*@16) */
  w72 *= w16;
  /* #471: @72 = (@69*@72) */
  w72  = (w69*w72);
  /* #472: @72 = (@68*@72) */
  w72  = (w68*w72);
  /* #473: @72 = (@74*@72) */
  w72  = (w74*w72);
  /* #474: @72 = (@66*@72) */
  w72  = (w66*w72);
  /* #475: @75 = (@75-@72) */
  w75 -= w72;
  /* #476: @67 = (@67*@64) */
  w67 *= w64;
  /* #477: @75 = (@75-@67) */
  w75 -= w67;
  /* #478: @80 = (@80<=@81) */
  w80  = (w80<=w81);
  /* #479: @79 = (@79<=@78) */
  w79  = (w79<=w78);
  /* #480: @78 = 0.5 */
  w78 = 5.0000000000000000e-01;
  /* #481: @78 = (@78*@16) */
  w78 *= w16;
  /* #482: @79 = (@79*@78) */
  w79 *= w78;
  /* #483: @80 = (@80*@79) */
  w80 *= w79;
  /* #484: @92 = (@92*@80) */
  w92 *= w80;
  /* #485: @89 = (@89/@1) */
  w89 /= w1;
  /* #486: @89 = (@89*@16) */
  w89 *= w16;
  /* #487: @89 = (@87*@89) */
  w89  = (w87*w89);
  /* #488: @89 = (@91*@89) */
  w89  = (w91*w89);
  /* #489: @86 = (@86/@1) */
  w86 /= w1;
  /* #490: @86 = (@86*@16) */
  w86 *= w16;
  /* #491: @89 = (@89-@86) */
  w89 -= w86;
  /* #492: @89 = (@83*@89) */
  w89  = (w83*w89);
  /* #493: @86 = (@41*@16) */
  w86  = (w41*w16);
  /* #494: @89 = (@89-@86) */
  w89 -= w86;
  /* #495: @89 = (@82*@89) */
  w89  = (w82*w89);
  /* #496: @92 = (@92+@89) */
  w92 += w89;
  /* #497: @89 = (@96*@16) */
  w89  = (w96*w16);
  /* #498: @89 = (@95*@89) */
  w89  = (w95*w89);
  /* #499: @90 = (@90*@89) */
  w90 *= w89;
  /* #500: @90 = (@94*@90) */
  w90  = (w94*w90);
  /* #501: @97 = (@97*@80) */
  w97 *= w80;
  /* #502: @90 = (@90-@97) */
  w90 -= w97;
  /* #503: @92 = (@92+@90) */
  w92 += w90;
  /* #504: @100 = (@100<=@101) */
  w100  = (w100<=w101);
  /* #505: @99 = (@99<=@98) */
  w99  = (w99<=w98);
  /* #506: @98 = 0.5 */
  w98 = 5.0000000000000000e-01;
  /* #507: @98 = (@98*@16) */
  w98 *= w16;
  /* #508: @99 = (@99*@98) */
  w99 *= w98;
  /* #509: @100 = (@100*@99) */
  w100 *= w99;
  /* #510: @110 = (@110*@100) */
  w110 *= w100;
  /* #511: @107 = (@107/@1) */
  w107 /= w1;
  /* #512: @107 = (@107*@16) */
  w107 *= w16;
  /* #513: @107 = (@105*@107) */
  w107  = (w105*w107);
  /* #514: @107 = (@104*@107) */
  w107  = (w104*w107);
  /* #515: @107 = (@109*@107) */
  w107  = (w109*w107);
  /* #516: @114 = (@114/@1) */
  w114 /= w1;
  /* #517: @114 = (@114*@16) */
  w114 *= w16;
  /* #518: @114 = (@111*@114) */
  w114  = (w111*w114);
  /* #519: @107 = (@107+@114) */
  w107 += w114;
  /* #520: @107 = (@103*@107) */
  w107  = (w103*w107);
  /* #521: @107 = (@102*@107) */
  w107  = (w102*w107);
  /* #522: @110 = (@110+@107) */
  w110 += w107;
  /* #523: @96 = (@96*@16) */
  w96 *= w16;
  /* #524: @108 = (@108*@96) */
  w108 *= w96;
  /* #525: @108 = (@116*@108) */
  w108  = (w116*w108);
  /* #526: @117 = (@117*@100) */
  w117 *= w100;
  /* #527: @108 = (@108-@117) */
  w108 -= w117;
  /* #528: @110 = (@110+@108) */
  w110 += w108;
  /* #529: @121 = 00 */
  /* #530: @133 = vertcat(@9, @29, @50, @75, @92, @110, @121) */
  rr=w133;
  *rr++ = w9;
  *rr++ = w29;
  *rr++ = w50;
  *rr++ = w75;
  *rr++ = w92;
  *rr++ = w110;
  /* #531: @133 = (-@133) */
  for (i=0, rr=w133, cs=w133; i<6; ++i) *rr++ = (- *cs++ );
  /* #532: @134 = @133[:6] */
  for (rr=w134, ss=w133+0; ss!=w133+6; ss+=1) *rr++ = *ss;
  /* #533: (@120[3, 6, 11, 14, 18, 22] = @134) */
  for (cii=casadi_s8, rr=w120, ss=w134; cii!=casadi_s8+6; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #534: @9 = ones(7x1,1nz) */
  w9 = 1.;
  /* #535: {NULL, NULL, NULL, NULL, @29, NULL, NULL} = vertsplit(@9) */
  w29 = w9;
  /* #536: @20 = (@20*@29) */
  w20 *= w29;
  /* #537: @20 = (@20/@21) */
  w20 /= w21;
  /* #538: @17 = (@17*@20) */
  w17 *= w20;
  /* #539: @17 = (-@17) */
  w17 = (- w17 );
  /* #540: @11 = (@11*@29) */
  w11 *= w29;
  /* #541: @11 = (@11/@12) */
  w11 /= w12;
  /* #542: @6 = (@6*@11) */
  w6 *= w11;
  /* #543: @17 = (@17-@6) */
  w17 -= w6;
  /* #544: @30 = (@30*@29) */
  w30 *= w29;
  /* #545: @27 = (@27*@30) */
  w27 *= w30;
  /* #546: @35 = (@35*@29) */
  w35 *= w29;
  /* #547: @32 = (@32*@35) */
  w32 *= w35;
  /* #548: @27 = (@27+@32) */
  w27 += w32;
  /* #549: @46 = (@46*@29) */
  w46 *= w29;
  /* #550: @43 = (@43*@46) */
  w43 *= w46;
  /* #551: @43 = (@43/@48) */
  w43 /= w48;
  /* #552: @43 = (@40*@43) */
  w43  = (w40*w43);
  /* #553: @57 = (@57*@29) */
  w57 *= w29;
  /* #554: @54 = (@54*@57) */
  w54 *= w57;
  /* #555: @54 = (@54/@59) */
  w54 /= w59;
  /* #556: @54 = (@52*@54) */
  w54  = (w52*w54);
  /* #557: @43 = (@43+@54) */
  w43 += w54;
  /* #558: @54 = (@29/@1) */
  w54  = (w29/w1);
  /* #559: @54 = (@69*@54) */
  w54  = (w69*w54);
  /* #560: @54 = (@68*@54) */
  w54  = (w68*w54);
  /* #561: @54 = (@74*@54) */
  w54  = (w74*w54);
  /* #562: @41 = (@41*@29) */
  w41 *= w29;
  /* #563: @54 = (@54+@41) */
  w54 += w41;
  /* #564: @54 = (@66*@54) */
  w54  = (w66*w54);
  /* #565: @41 = (@29/@1) */
  w41  = (w29/w1);
  /* #566: @41 = (@87*@41) */
  w41  = (w87*w41);
  /* #567: @41 = (@91*@41) */
  w41  = (w91*w41);
  /* #568: @41 = (-@41) */
  w41 = (- w41 );
  /* #569: @59 = (@84*@29) */
  w59  = (w84*w29);
  /* #570: @59 = (@59/@1) */
  w59 /= w1;
  /* #571: @41 = (@41-@59) */
  w41 -= w59;
  /* #572: @41 = (@83*@41) */
  w41  = (w83*w41);
  /* #573: @41 = (@82*@41) */
  w41  = (w82*w41);
  /* #574: @59 = (@112*@29) */
  w59  = (w112*w29);
  /* #575: @59 = (@59/@1) */
  w59 /= w1;
  /* #576: @59 = (@111*@59) */
  w59  = (w111*w59);
  /* #577: @29 = (@29/@1) */
  w29 /= w1;
  /* #578: @29 = (@105*@29) */
  w29  = (w105*w29);
  /* #579: @29 = (@104*@29) */
  w29  = (w104*w29);
  /* #580: @29 = (@109*@29) */
  w29  = (w109*w29);
  /* #581: @59 = (@59-@29) */
  w59 -= w29;
  /* #582: @59 = (@103*@59) */
  w59  = (w103*w59);
  /* #583: @59 = (@102*@59) */
  w59  = (w102*w59);
  /* #584: @121 = 00 */
  /* #585: @134 = vertcat(@17, @27, @43, @54, @41, @59, @121) */
  rr=w134;
  *rr++ = w17;
  *rr++ = w27;
  *rr++ = w43;
  *rr++ = w54;
  *rr++ = w41;
  *rr++ = w59;
  /* #586: @134 = (-@134) */
  for (i=0, rr=w134, cs=w134; i<6; ++i) *rr++ = (- *cs++ );
  /* #587: @133 = @134[:6] */
  for (rr=w133, ss=w134+0; ss!=w134+6; ss+=1) *rr++ = *ss;
  /* #588: (@120[4, 7, 12, 15, 19, 23] = @133) */
  for (cii=casadi_s9, rr=w120, ss=w133; cii!=casadi_s9+6; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #589: @121 = 00 */
  /* #590: @123 = 00 */
  /* #591: @17 = ones(7x1,1nz) */
  w17 = 1.;
  /* #592: {NULL, NULL, NULL, NULL, NULL, @27, NULL} = vertsplit(@17) */
  w27 = w17;
  /* #593: @40 = (@40*@27) */
  w40 *= w27;
  /* #594: @52 = (@52*@27) */
  w52 *= w27;
  /* #595: @40 = (@40+@52) */
  w40 += w52;
  /* #596: @71 = (@71*@27) */
  w71 *= w27;
  /* #597: @71 = (@71/@1) */
  w71 /= w1;
  /* #598: @69 = (@69*@71) */
  w69 *= w71;
  /* #599: @68 = (@68*@69) */
  w68 *= w69;
  /* #600: @74 = (@74*@68) */
  w74 *= w68;
  /* #601: @10 = (@10*@27) */
  w10 *= w27;
  /* #602: @74 = (@74+@10) */
  w74 += w10;
  /* #603: @74 = (@66*@74) */
  w74  = (w66*w74);
  /* #604: @85 = (@85*@27) */
  w85 *= w27;
  /* #605: @84 = (@84*@85) */
  w84 *= w85;
  /* #606: @84 = (@84/@1) */
  w84 /= w1;
  /* #607: @88 = (@88*@27) */
  w88 *= w27;
  /* #608: @88 = (@88/@1) */
  w88 /= w1;
  /* #609: @87 = (@87*@88) */
  w87 *= w88;
  /* #610: @91 = (@91*@87) */
  w91 *= w87;
  /* #611: @84 = (@84-@91) */
  w84 -= w91;
  /* #612: @83 = (@83*@84) */
  w83 *= w84;
  /* #613: @84 = (@1*@27) */
  w84  = (w1*w27);
  /* #614: @83 = (@83-@84) */
  w83 -= w84;
  /* #615: @82 = (@82*@83) */
  w82 *= w83;
  /* #616: @113 = (@113*@27) */
  w113 *= w27;
  /* #617: @112 = (@112*@113) */
  w112 *= w113;
  /* #618: @112 = (@112/@1) */
  w112 /= w1;
  /* #619: @111 = (@111*@112) */
  w111 *= w112;
  /* #620: @111 = (-@111) */
  w111 = (- w111 );
  /* #621: @106 = (@106*@27) */
  w106 *= w27;
  /* #622: @106 = (@106/@1) */
  w106 /= w1;
  /* #623: @105 = (@105*@106) */
  w105 *= w106;
  /* #624: @104 = (@104*@105) */
  w104 *= w105;
  /* #625: @109 = (@109*@104) */
  w109 *= w104;
  /* #626: @111 = (@111-@109) */
  w111 -= w109;
  /* #627: @103 = (@103*@111) */
  w103 *= w111;
  /* #628: @102 = (@102*@103) */
  w102 *= w103;
  /* #629: @127 = 00 */
  /* #630: @135 = vertcat(@121, @123, @40, @74, @82, @102, @127) */
  rr=w135;
  *rr++ = w40;
  *rr++ = w74;
  *rr++ = w82;
  *rr++ = w102;
  /* #631: @135 = (-@135) */
  for (i=0, rr=w135, cs=w135; i<4; ++i) *rr++ = (- *cs++ );
  /* #632: @136 = @135[:4] */
  for (rr=w136, ss=w135+0; ss!=w135+4; ss+=1) *rr++ = *ss;
  /* #633: (@120[13, 16, 20, 24] = @136) */
  for (cii=casadi_s10, rr=w120, ss=w136; cii!=casadi_s10+4; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #634: @137 = @120' */
  casadi_trans(w120,casadi_s12, w137, casadi_s11, iw);
  /* #635: output[1][0] = @137 */
  casadi_copy(w137, 26, res[1]);
  /* #636: @0 = zeros(7x7,7nz) */
  casadi_clear(w0, 7);
  /* #637: @119 = ones(7x1) */
  casadi_fill(w119, 7, 1.);
  /* #638: (@0[:7] = @119) */
  for (rr=w0+0, ss=w119; rr!=w0+7; rr+=1) *rr = *ss++;
  /* #639: @119 = @0' */
  casadi_trans(w0,casadi_s13, w119, casadi_s13, iw);
  /* #640: output[2][0] = @119 */
  casadi_copy(w119, 7, res[2]);
  /* #641: @133 = zeros(2x7,6nz) */
  casadi_clear(w133, 6);
  /* #642: @121 = 00 */
  /* #643: @123 = 00 */
  /* #644: @127 = 00 */
  /* #645: @40 = ones(2x1,1nz) */
  w40 = 1.;
  /* #646: {@74, NULL} = vertsplit(@40) */
  w74 = w40;
  /* #647: @66 = (@66*@74) */
  w66 *= w74;
  /* #648: @77 = (@77*@74) */
  w77 *= w74;
  /* #649: @66 = (@66+@77) */
  w66 += w77;
  /* #650: @77 = 0.357143 */
  w77 = 3.5714285714285715e-01;
  /* #651: @40 = (@70*@74) */
  w40  = (w70*w74);
  /* #652: @40 = (@95*@40) */
  w40  = (w95*w40);
  /* #653: @40 = (@77*@40) */
  w40  = (w77*w40);
  /* #654: @40 = (@94*@40) */
  w40  = (w94*w40);
  /* #655: @82 = 0.357143 */
  w82 = 3.5714285714285715e-01;
  /* #656: @70 = (@70*@74) */
  w70 *= w74;
  /* #657: @70 = (@82*@70) */
  w70  = (w82*w70);
  /* #658: @70 = (@116*@70) */
  w70  = (w116*w70);
  /* #659: @128 = 00 */
  /* #660: @132 = vertcat(@121, @123, @127, @66, @40, @70, @128) */
  rr=w132;
  *rr++ = w66;
  *rr++ = w40;
  *rr++ = w70;
  /* #661: @132 = (-@132) */
  for (i=0, rr=w132, cs=w132; i<3; ++i) *rr++ = (- *cs++ );
  /* #662: @131 = @132[:3] */
  for (rr=w131, ss=w132+0; ss!=w132+3; ss+=1) *rr++ = *ss;
  /* #663: (@133[0, 1, 3] = @131) */
  for (cii=casadi_s14, rr=w133, ss=w131; cii!=casadi_s14+3; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #664: @121 = 00 */
  /* #665: @123 = 00 */
  /* #666: @127 = 00 */
  /* #667: @128 = 00 */
  /* #668: @66 = ones(2x1,1nz) */
  w66 = 1.;
  /* #669: {NULL, @40} = vertsplit(@66) */
  w40 = w66;
  /* #670: @66 = (@1*@40) */
  w66  = (w1*w40);
  /* #671: @95 = (@95*@66) */
  w95 *= w66;
  /* #672: @77 = (@77*@95) */
  w77 *= w95;
  /* #673: @94 = (@94*@77) */
  w94 *= w77;
  /* #674: @1 = (@1*@40) */
  w1 *= w40;
  /* #675: @82 = (@82*@1) */
  w82 *= w1;
  /* #676: @116 = (@116*@82) */
  w116 *= w82;
  /* #677: @131 = vertcat(@121, @123, @127, @128, @94, @116, @40) */
  rr=w131;
  *rr++ = w94;
  *rr++ = w116;
  *rr++ = w40;
  /* #678: @131 = (-@131) */
  for (i=0, rr=w131, cs=w131; i<3; ++i) *rr++ = (- *cs++ );
  /* #679: @132 = @131[:3] */
  for (rr=w132, ss=w131+0; ss!=w131+3; ss+=1) *rr++ = *ss;
  /* #680: (@133[2, 4, 5] = @132) */
  for (cii=casadi_s15, rr=w133, ss=w132; cii!=casadi_s15+3; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #681: @134 = @133' */
  casadi_trans(w133,casadi_s17, w134, casadi_s16, iw);
  /* #682: output[3][0] = @134 */
  casadi_copy(w134, 6, res[3]);
  return 0;
}

CASADI_SYMBOL_EXPORT int sim_car_impl_dae_fun_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int sim_car_impl_dae_fun_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int sim_car_impl_dae_fun_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void sim_car_impl_dae_fun_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int sim_car_impl_dae_fun_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void sim_car_impl_dae_fun_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void sim_car_impl_dae_fun_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void sim_car_impl_dae_fun_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int sim_car_impl_dae_fun_jac_x_xdot_u_z_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int sim_car_impl_dae_fun_jac_x_xdot_u_z_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real sim_car_impl_dae_fun_jac_x_xdot_u_z_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* sim_car_impl_dae_fun_jac_x_xdot_u_z_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* sim_car_impl_dae_fun_jac_x_xdot_u_z_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* sim_car_impl_dae_fun_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s18;
    case 1: return casadi_s18;
    case 2: return casadi_s19;
    case 3: return casadi_s20;
    case 4: return casadi_s20;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* sim_car_impl_dae_fun_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s18;
    case 1: return casadi_s11;
    case 2: return casadi_s13;
    case 3: return casadi_s16;
    case 4: return casadi_s21;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int sim_car_impl_dae_fun_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 12;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 237;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
