/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) sim_car_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_low CASADI_PREFIX(low)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[1] = {0};
static const casadi_int casadi_s1[1] = {1};
static const casadi_int casadi_s2[1] = {2};
static const casadi_int casadi_s3[2] = {0, 7};
static const casadi_int casadi_s4[1] = {3};
static const casadi_int casadi_s5[2] = {0, 9};
static const casadi_int casadi_s6[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s7[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s8[3] = {0, 0, 0};
static const casadi_int casadi_s9[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};

static const casadi_real casadi_c0[4] = {-2.7528570785764761e-21, 1.0587911840678754e-22, 0., 2.5410988417629010e-21};
static const casadi_real casadi_c1[7] = {0., 0., 0., 2., 4., 4., 4.};
static const casadi_real casadi_c2[5] = {1.0000000000000019e-06, 9.9999999999999995e-07, 1.0000000000000002e-06, 1.0000000000000002e-06, 1.0000000000000019e-06};
static const casadi_real casadi_c3[9] = {0., 0., 0., 0., 2., 4., 4., 4., 4.};

/* jac_kapparef_s:(x,out_f[1x1,0nz])->(jac) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c1,casadi_s3,casadi_s2,casadi_s1,casadi_c0,1,(&w0),casadi_s0, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* kapparef_s:(x)->(f) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c3,casadi_s5,casadi_s4,casadi_s1,casadi_c2,1,(&w0),casadi_s0, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* sim_car_expl_vde_adj:(i0[7],i1[7],i2[2],i3[])->(o0[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1;
  const casadi_real **arg1=arg+4;
  casadi_real w0, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, *w16=w+27, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35, w36, w37, w38, w39, w40, w41, w42, w43, w44, w45, w46, w47, w48, w49, w50, w51, w52, w53, w54, w55, w56, w57, w58, w59, w60, w61, w62, w63, w64, w65, w66, w67;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = 00 */
  /* #2: @2 = jac_kapparef_s(@0, @1) */
  arg1[0]=(&w0);
  arg1[1]=0;
  res1[0]=(&w2);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #3: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #4: @4 = input[0][3] */
  w4 = arg[0] ? arg[0][3] : 0;
  /* #5: @5 = input[0][2] */
  w5 = arg[0] ? arg[0][2] : 0;
  /* #6: @6 = cos(@5) */
  w6 = cos( w5 );
  /* #7: @7 = (@4*@6) */
  w7  = (w4*w6);
  /* #8: @8 = input[0][4] */
  w8 = arg[0] ? arg[0][4] : 0;
  /* #9: @9 = sin(@5) */
  w9 = sin( w5 );
  /* #10: @10 = (@8*@9) */
  w10  = (w8*w9);
  /* #11: @7 = (@7-@10) */
  w7 -= w10;
  /* #12: @10 = 1 */
  w10 = 1.;
  /* #13: @11 = 3 */
  w11 = 3.;
  /* #14: @11 = (@4-@11) */
  w11  = (w4-w11);
  /* #15: @12 = 2 */
  w12 = 2.;
  /* #16: @11 = (@11/@12) */
  w11 /= w12;
  /* #17: @12 = 0 */
  w12 = 0.;
  /* #18: @13 = fmax(@11,@12) */
  w13  = casadi_fmax(w11,w12);
  /* #19: @14 = 1 */
  w14 = 1.;
  /* #20: @15 = fmin(@13,@14) */
  w15  = casadi_fmin(w13,w14);
  /* #21: @10 = (@10-@15) */
  w10 -= w15;
  /* #22: @16 = input[1][0] */
  casadi_copy(arg[1], 7, w16);
  /* #23: {@17, @18, @19, @20, @21, @22, @23} = vertsplit(@16) */
  w17 = w16[0];
  w18 = w16[1];
  w19 = w16[2];
  w20 = w16[3];
  w21 = w16[4];
  w22 = w16[5];
  w23 = w16[6];
  /* #24: @10 = (@10*@19) */
  w10 *= w19;
  /* #25: @24 = 1 */
  w24 = 1.;
  /* #26: @25 = kapparef_s(@0) */
  arg1[0]=(&w0);
  res1[0]=(&w25);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #27: @26 = (@3*@25) */
  w26  = (w3*w25);
  /* #28: @24 = (@24-@26) */
  w24 -= w26;
  /* #29: @26 = (@10/@24) */
  w26  = (w10/w24);
  /* #30: @27 = (@7*@26) */
  w27  = (w7*w26);
  /* #31: @28 = (@3*@27) */
  w28  = (w3*w27);
  /* #32: @2 = (@2*@28) */
  w2 *= w28;
  /* #33: @2 = (-@2) */
  w2 = (- w2 );
  /* #34: @1 = 00 */
  /* #35: @28 = jac_kapparef_s(@0, @1) */
  arg1[0]=(&w0);
  arg1[1]=0;
  res1[0]=(&w28);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #36: @29 = kapparef_s(@0) */
  arg1[0]=(&w0);
  res1[0]=(&w29);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #37: @30 = (@3*@29) */
  w30  = (w3*w29);
  /* #38: @7 = (@30*@7) */
  w7  = (w30*w7);
  /* #39: @7 = (@7/@24) */
  w7 /= w24;
  /* #40: @24 = (@7/@24) */
  w24  = (w7/w24);
  /* #41: @24 = (@24*@10) */
  w24 *= w10;
  /* #42: @31 = (@3*@24) */
  w31  = (w3*w24);
  /* #43: @28 = (@28*@31) */
  w28 *= w31;
  /* #44: @2 = (@2-@28) */
  w2 -= w28;
  /* #45: @1 = 00 */
  /* #46: @28 = jac_kapparef_s(@0, @1) */
  arg1[0]=(&w0);
  arg1[1]=0;
  res1[0]=(&w28);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #47: @31 = kapparef_s(@0) */
  arg1[0]=(&w0);
  res1[0]=(&w31);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #48: @32 = (@3*@31) */
  w32  = (w3*w31);
  /* #49: @33 = cos(@5) */
  w33 = cos( w5 );
  /* #50: @34 = (@4*@33) */
  w34  = (w4*w33);
  /* #51: @35 = sin(@5) */
  w35 = sin( w5 );
  /* #52: @36 = (@8*@35) */
  w36  = (w8*w35);
  /* #53: @34 = (@34-@36) */
  w34 -= w36;
  /* #54: @36 = (@32*@34) */
  w36  = (w32*w34);
  /* #55: @37 = 1 */
  w37 = 1.;
  /* #56: @38 = kapparef_s(@0) */
  arg1[0]=(&w0);
  res1[0]=(&w38);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #57: @39 = (@3*@38) */
  w39  = (w3*w38);
  /* #58: @37 = (@37-@39) */
  w37 -= w39;
  /* #59: @36 = (@36/@37) */
  w36 /= w37;
  /* #60: @39 = (@36/@37) */
  w39  = (w36/w37);
  /* #61: @40 = (@15*@19) */
  w40  = (w15*w19);
  /* #62: @39 = (@39*@40) */
  w39 *= w40;
  /* #63: @41 = (@3*@39) */
  w41  = (w3*w39);
  /* #64: @28 = (@28*@41) */
  w28 *= w41;
  /* #65: @2 = (@2-@28) */
  w2 -= w28;
  /* #66: @1 = 00 */
  /* #67: @28 = jac_kapparef_s(@0, @1) */
  arg1[0]=(&w0);
  arg1[1]=0;
  res1[0]=(&w28);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #68: @37 = (@40/@37) */
  w37  = (w40/w37);
  /* #69: @34 = (@34*@37) */
  w34 *= w37;
  /* #70: @41 = (@3*@34) */
  w41  = (w3*w34);
  /* #71: @28 = (@28*@41) */
  w28 *= w41;
  /* #72: @2 = (@2-@28) */
  w2 -= w28;
  /* #73: @1 = 00 */
  /* #74: @28 = jac_kapparef_s(@0, @1) */
  arg1[0]=(&w0);
  arg1[1]=0;
  res1[0]=(&w28);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #75: @41 = cos(@5) */
  w41 = cos( w5 );
  /* #76: @42 = (@4*@41) */
  w42  = (w4*w41);
  /* #77: @43 = sin(@5) */
  w43 = sin( w5 );
  /* #78: @44 = (@8*@43) */
  w44  = (w8*w43);
  /* #79: @42 = (@42-@44) */
  w42 -= w44;
  /* #80: @44 = 1 */
  w44 = 1.;
  /* #81: @45 = kapparef_s(@0) */
  arg1[0]=(&w0);
  res1[0]=(&w45);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #82: @0 = (@3*@45) */
  w0  = (w3*w45);
  /* #83: @44 = (@44-@0) */
  w44 -= w0;
  /* #84: @42 = (@42/@44) */
  w42 /= w44;
  /* #85: @42 = (@42/@44) */
  w42 /= w44;
  /* #86: @42 = (@42*@17) */
  w42 *= w17;
  /* #87: @3 = (@3*@42) */
  w3 *= w42;
  /* #88: @28 = (@28*@3) */
  w28 *= w3;
  /* #89: @2 = (@2+@28) */
  w2 += w28;
  /* #90: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #91: @29 = (@29*@27) */
  w29 *= w27;
  /* #92: @29 = (-@29) */
  w29 = (- w29 );
  /* #93: @25 = (@25*@24) */
  w25 *= w24;
  /* #94: @29 = (@29-@25) */
  w29 -= w25;
  /* #95: @38 = (@38*@39) */
  w38 *= w39;
  /* #96: @29 = (@29-@38) */
  w29 -= w38;
  /* #97: @31 = (@31*@34) */
  w31 *= w34;
  /* #98: @29 = (@29-@31) */
  w29 -= w31;
  /* #99: @45 = (@45*@42) */
  w45 *= w42;
  /* #100: @29 = (@29+@45) */
  w29 += w45;
  /* #101: output[0][1] = @29 */
  if (res[0]) res[0][1] = w29;
  /* #102: @29 = cos(@5) */
  w29 = cos( w5 );
  /* #103: @30 = (@30*@26) */
  w30 *= w26;
  /* #104: @26 = (@8*@30) */
  w26  = (w8*w30);
  /* #105: @29 = (@29*@26) */
  w29 *= w26;
  /* #106: @26 = sin(@5) */
  w26 = sin( w5 );
  /* #107: @45 = (@4*@30) */
  w45  = (w4*w30);
  /* #108: @26 = (@26*@45) */
  w26 *= w45;
  /* #109: @29 = (@29+@26) */
  w29 += w26;
  /* #110: @26 = cos(@5) */
  w26 = cos( w5 );
  /* #111: @32 = (@32*@37) */
  w32 *= w37;
  /* #112: @37 = (@8*@32) */
  w37  = (w8*w32);
  /* #113: @26 = (@26*@37) */
  w26 *= w37;
  /* #114: @29 = (@29+@26) */
  w29 += w26;
  /* #115: @26 = sin(@5) */
  w26 = sin( w5 );
  /* #116: @37 = (@4*@32) */
  w37  = (w4*w32);
  /* #117: @26 = (@26*@37) */
  w26 *= w37;
  /* #118: @29 = (@29+@26) */
  w29 += w26;
  /* #119: @26 = sin(@5) */
  w26 = sin( w5 );
  /* #120: @37 = (@8*@18) */
  w37  = (w8*w18);
  /* #121: @26 = (@26*@37) */
  w26 *= w37;
  /* #122: @29 = (@29-@26) */
  w29 -= w26;
  /* #123: @26 = cos(@5) */
  w26 = cos( w5 );
  /* #124: @37 = (@4*@18) */
  w37  = (w4*w18);
  /* #125: @26 = (@26*@37) */
  w26 *= w37;
  /* #126: @29 = (@29+@26) */
  w29 += w26;
  /* #127: @26 = cos(@5) */
  w26 = cos( w5 );
  /* #128: @17 = (@17/@44) */
  w17 /= w44;
  /* #129: @44 = (@8*@17) */
  w44  = (w8*w17);
  /* #130: @26 = (@26*@44) */
  w26 *= w44;
  /* #131: @29 = (@29-@26) */
  w29 -= w26;
  /* #132: @26 = sin(@5) */
  w26 = sin( w5 );
  /* #133: @44 = (@4*@17) */
  w44  = (w4*w17);
  /* #134: @26 = (@26*@44) */
  w26 *= w44;
  /* #135: @29 = (@29-@26) */
  w29 -= w26;
  /* #136: output[0][2] = @29 */
  if (res[0]) res[0][2] = w29;
  /* #137: @29 = input[2][1] */
  w29 = arg[2] ? arg[2][1] : 0;
  /* #138: @26 = 0.357143 */
  w26 = 3.5714285714285715e-01;
  /* #139: @44 = 1 */
  w44 = 1.;
  /* #140: @44 = (@44-@15) */
  w44 -= w15;
  /* #141: @44 = (@44*@22) */
  w44 *= w22;
  /* #142: @26 = (@26*@44) */
  w26 *= w44;
  /* #143: @44 = (@29*@26) */
  w44  = (w29*w26);
  /* #144: @37 = 92731.3 */
  w37 = 9.2731265615302604e+04;
  /* #145: @45 = 1.4 */
  w45 = 1.3999999999999999e+00;
  /* #146: @42 = input[0][5] */
  w42 = arg[0] ? arg[0][5] : 0;
  /* #147: @31 = (@45*@42) */
  w31  = (w45*w42);
  /* #148: @31 = (@31-@8) */
  w31 -= w8;
  /* #149: @31 = (@37*@31) */
  w31  = (w37*w31);
  /* #150: @31 = (@31/@4) */
  w31 /= w4;
  /* #151: @34 = (@31/@4) */
  w34  = (w31/w4);
  /* #152: @38 = 1.4 */
  w38 = 1.3999999999999999e+00;
  /* #153: @39 = 0.000255102 */
  w39 = 2.5510204081632655e-04;
  /* #154: @25 = (@15*@22) */
  w25  = (w15*w22);
  /* #155: @25 = (@39*@25) */
  w25  = (w39*w25);
  /* #156: @24 = (@38*@25) */
  w24  = (w38*w25);
  /* #157: @34 = (@34*@24) */
  w34 *= w24;
  /* #158: @44 = (@44+@34) */
  w44 += w34;
  /* #159: @34 = 1.4 */
  w34 = 1.3999999999999999e+00;
  /* #160: @27 = (@34*@42) */
  w27  = (w34*w42);
  /* #161: @27 = (@8+@27) */
  w27  = (w8+w27);
  /* #162: @27 = (@27/@4) */
  w27 /= w4;
  /* #163: @2 = (@27/@4) */
  w2  = (w27/w4);
  /* #164: @28 = 92731.3 */
  w28 = 9.2731265615302604e+04;
  /* #165: @3 = 1.4 */
  w3 = 1.3999999999999999e+00;
  /* #166: @0 = input[0][6] */
  w0 = arg[0] ? arg[0][6] : 0;
  /* #167: @46 = cos(@0) */
  w46 = cos( w0 );
  /* #168: @47 = (@46*@25) */
  w47  = (w46*w25);
  /* #169: @47 = (@3*@47) */
  w47  = (w3*w47);
  /* #170: @47 = (@28*@47) */
  w47  = (w28*w47);
  /* #171: @2 = (@2*@47) */
  w2 *= w47;
  /* #172: @44 = (@44+@2) */
  w44 += w2;
  /* #173: @2 = 1.4 */
  w2 = 1.3999999999999999e+00;
  /* #174: @48 = 0.357143 */
  w48 = 3.5714285714285715e-01;
  /* #175: @49 = 1 */
  w49 = 1.;
  /* #176: @49 = (@49-@15) */
  w49 -= w15;
  /* #177: @49 = (@49*@21) */
  w49 *= w21;
  /* #178: @48 = (@48*@49) */
  w48 *= w49;
  /* #179: @48 = (@2*@48) */
  w48  = (w2*w48);
  /* #180: @49 = (@29*@48) */
  w49  = (w29*w48);
  /* #181: @44 = (@44+@49) */
  w44 += w49;
  /* #182: @49 = (@15*@21) */
  w49  = (w15*w21);
  /* #183: @50 = (@42*@49) */
  w50  = (w42*w49);
  /* #184: @44 = (@44-@50) */
  w44 -= w50;
  /* #185: @50 = 1.4 */
  w50 = 1.3999999999999999e+00;
  /* #186: @51 = (@50*@42) */
  w51  = (w50*w42);
  /* #187: @51 = (@8+@51) */
  w51  = (w8+w51);
  /* #188: @51 = (@51/@4) */
  w51 /= w4;
  /* #189: @52 = (@51/@4) */
  w52  = (w51/w4);
  /* #190: @53 = 92731.3 */
  w53 = 9.2731265615302604e+04;
  /* #191: @54 = cos(@0) */
  w54 = cos( w0 );
  /* #192: @55 = 0.0005 */
  w55 = 5.0000000000000001e-04;
  /* #193: @56 = (@55*@49) */
  w56  = (w55*w49);
  /* #194: @57 = (@54*@56) */
  w57  = (w54*w56);
  /* #195: @57 = (@53*@57) */
  w57  = (w53*w57);
  /* #196: @52 = (@52*@57) */
  w52 *= w57;
  /* #197: @44 = (@44+@52) */
  w44 += w52;
  /* #198: @52 = 92731.3 */
  w52 = 9.2731265615302604e+04;
  /* #199: @58 = 1.4 */
  w58 = 1.3999999999999999e+00;
  /* #200: @59 = (@58*@42) */
  w59  = (w58*w42);
  /* #201: @59 = (@59-@8) */
  w59 -= w8;
  /* #202: @59 = (@52*@59) */
  w59  = (w52*w59);
  /* #203: @59 = (@59/@4) */
  w59 /= w4;
  /* #204: @60 = (@59/@4) */
  w60  = (w59/w4);
  /* #205: @60 = (@60*@56) */
  w60 *= w56;
  /* #206: @44 = (@44-@60) */
  w44 -= w60;
  /* #207: @60 = 1.4 */
  w60 = 1.3999999999999999e+00;
  /* #208: @61 = (@60*@42) */
  w61  = (w60*w42);
  /* #209: @61 = (@8+@61) */
  w61  = (w8+w61);
  /* #210: @61 = (@61/@4) */
  w61 /= w4;
  /* #211: @62 = (@61/@4) */
  w62  = (w61/w4);
  /* #212: @63 = 92731.3 */
  w63 = 9.2731265615302604e+04;
  /* #213: @64 = 0.0005 */
  w64 = 5.0000000000000001e-04;
  /* #214: @65 = sin(@0) */
  w65 = sin( w0 );
  /* #215: @66 = (@15*@20) */
  w66  = (w15*w20);
  /* #216: @67 = (@65*@66) */
  w67  = (w65*w66);
  /* #217: @67 = (@64*@67) */
  w67  = (w64*w67);
  /* #218: @67 = (@63*@67) */
  w67  = (w63*w67);
  /* #219: @62 = (@62*@67) */
  w62 *= w67;
  /* #220: @44 = (@44-@62) */
  w44 -= w62;
  /* #221: @6 = (@6*@30) */
  w6 *= w30;
  /* #222: @44 = (@44-@6) */
  w44 -= w6;
  /* #223: @33 = (@33*@32) */
  w33 *= w32;
  /* #224: @44 = (@44-@33) */
  w44 -= w33;
  /* #225: @33 = 0.5 */
  w33 = 5.0000000000000000e-01;
  /* #226: @12 = (@12<=@11) */
  w12  = (w12<=w11);
  /* #227: @13 = (@13<=@14) */
  w13  = (w13<=w14);
  /* #228: @27 = (@0-@27) */
  w27  = (w0-w27);
  /* #229: @28 = (@28*@27) */
  w28 *= w27;
  /* #230: @3 = (@3*@28) */
  w3 *= w28;
  /* #231: @46 = (@3*@46) */
  w46  = (w3*w46);
  /* #232: @38 = (@38*@31) */
  w38 *= w31;
  /* #233: @46 = (@46-@38) */
  w46 -= w38;
  /* #234: @39 = (@39*@46) */
  w39 *= w46;
  /* #235: @39 = (@39*@22) */
  w39 *= w22;
  /* #236: @46 = (@29*@4) */
  w46  = (w29*w4);
  /* #237: @38 = input[2][0] */
  w38 = arg[2] ? arg[2][0] : 0;
  /* #238: @31 = (@0*@38) */
  w31  = (w0*w38);
  /* #239: @46 = (@46+@31) */
  w46 += w31;
  /* #240: @31 = 2.8 */
  w31 = 2.7999999999999998e+00;
  /* #241: @46 = (@46/@31) */
  w46 /= w31;
  /* #242: @46 = (@46*@22) */
  w46 *= w22;
  /* #243: @39 = (@39-@46) */
  w39 -= w46;
  /* #244: @29 = (@29*@4) */
  w29 *= w4;
  /* #245: @46 = (@0*@38) */
  w46  = (w0*w38);
  /* #246: @29 = (@29+@46) */
  w29 += w46;
  /* #247: @2 = (@2*@29) */
  w2 *= w29;
  /* #248: @29 = 2.8 */
  w29 = 2.7999999999999998e+00;
  /* #249: @2 = (@2/@29) */
  w2 /= w29;
  /* #250: @2 = (@2*@21) */
  w2 *= w21;
  /* #251: @39 = (@39-@2) */
  w39 -= w2;
  /* #252: @51 = (@0-@51) */
  w51  = (w0-w51);
  /* #253: @53 = (@53*@51) */
  w53 *= w51;
  /* #254: @54 = (@53*@54) */
  w54  = (w53*w54);
  /* #255: @59 = (@59+@54) */
  w59 += w54;
  /* #256: @55 = (@55*@59) */
  w55 *= w59;
  /* #257: @59 = (@4*@42) */
  w59  = (w4*w42);
  /* #258: @55 = (@55-@59) */
  w55 -= w59;
  /* #259: @55 = (@55*@21) */
  w55 *= w21;
  /* #260: @39 = (@39+@55) */
  w39 += w55;
  /* #261: @55 = (@38*@20) */
  w55  = (w38*w20);
  /* #262: @39 = (@39-@55) */
  w39 -= w55;
  /* #263: @61 = (@0-@61) */
  w61  = (w0-w61);
  /* #264: @63 = (@63*@61) */
  w63 *= w61;
  /* #265: @64 = (@64*@63) */
  w64 *= w63;
  /* #266: @65 = (@64*@65) */
  w65  = (w64*w65);
  /* #267: @65 = (@38-@65) */
  w65  = (w38-w65);
  /* #268: @63 = (@8*@42) */
  w63  = (w8*w42);
  /* #269: @65 = (@65+@63) */
  w65 += w63;
  /* #270: @65 = (@65*@20) */
  w65 *= w20;
  /* #271: @39 = (@39+@65) */
  w39 += w65;
  /* #272: @7 = (@42-@7) */
  w7  = (w42-w7);
  /* #273: @7 = (@7*@19) */
  w7 *= w19;
  /* #274: @39 = (@39-@7) */
  w39 -= w7;
  /* #275: @36 = (@42-@36) */
  w36  = (w42-w36);
  /* #276: @36 = (@36*@19) */
  w36 *= w19;
  /* #277: @39 = (@39+@36) */
  w39 += w36;
  /* #278: @13 = (@13*@39) */
  w13 *= w39;
  /* #279: @12 = (@12*@13) */
  w12 *= w13;
  /* #280: @33 = (@33*@12) */
  w33 *= w12;
  /* #281: @44 = (@44+@33) */
  w44 += w33;
  /* #282: @33 = sin(@5) */
  w33 = sin( w5 );
  /* #283: @33 = (@33*@18) */
  w33 *= w18;
  /* #284: @44 = (@44+@33) */
  w44 += w33;
  /* #285: @41 = (@41*@17) */
  w41 *= w17;
  /* #286: @44 = (@44+@41) */
  w44 += w41;
  /* #287: output[0][3] = @44 */
  if (res[0]) res[0][3] = w44;
  /* #288: @24 = (@24/@4) */
  w24 /= w4;
  /* #289: @37 = (@37*@24) */
  w37 *= w24;
  /* #290: @24 = (@47/@4) */
  w24  = (w47/w4);
  /* #291: @44 = (@37-@24) */
  w44  = (w37-w24);
  /* #292: @41 = (@57/@4) */
  w41  = (w57/w4);
  /* #293: @44 = (@44-@41) */
  w44 -= w41;
  /* #294: @33 = (@56/@4) */
  w33  = (w56/w4);
  /* #295: @52 = (@52*@33) */
  w52 *= w33;
  /* #296: @44 = (@44-@52) */
  w44 -= w52;
  /* #297: @42 = (@42*@66) */
  w42 *= w66;
  /* #298: @44 = (@44+@42) */
  w44 += w42;
  /* #299: @42 = (@67/@4) */
  w42  = (w67/w4);
  /* #300: @44 = (@44+@42) */
  w44 += w42;
  /* #301: @9 = (@9*@30) */
  w9 *= w30;
  /* #302: @44 = (@44+@9) */
  w44 += w9;
  /* #303: @35 = (@35*@32) */
  w35 *= w32;
  /* #304: @44 = (@44+@35) */
  w44 += w35;
  /* #305: @5 = cos(@5) */
  w5 = cos( w5 );
  /* #306: @5 = (@5*@18) */
  w5 *= w18;
  /* #307: @44 = (@44+@5) */
  w44 += w5;
  /* #308: @43 = (@43*@17) */
  w43 *= w17;
  /* #309: @44 = (@44-@43) */
  w44 -= w43;
  /* #310: output[0][4] = @44 */
  if (res[0]) res[0][4] = w44;
  /* #311: @34 = (@34*@24) */
  w34 *= w24;
  /* #312: @34 = (-@34) */
  w34 = (- w34 );
  /* #313: @45 = (@45*@37) */
  w45 *= w37;
  /* #314: @34 = (@34-@45) */
  w34 -= w45;
  /* #315: @49 = (@4*@49) */
  w49  = (w4*w49);
  /* #316: @34 = (@34-@49) */
  w34 -= w49;
  /* #317: @50 = (@50*@41) */
  w50 *= w41;
  /* #318: @34 = (@34-@50) */
  w34 -= w50;
  /* #319: @58 = (@58*@52) */
  w58 *= w52;
  /* #320: @34 = (@34+@58) */
  w34 += w58;
  /* #321: @8 = (@8*@66) */
  w8 *= w66;
  /* #322: @34 = (@34+@8) */
  w34 += w8;
  /* #323: @60 = (@60*@42) */
  w60 *= w42;
  /* #324: @34 = (@34+@60) */
  w34 += w60;
  /* #325: @34 = (@34+@10) */
  w34 += w10;
  /* #326: @34 = (@34+@40) */
  w34 += w40;
  /* #327: output[0][5] = @34 */
  if (res[0]) res[0][5] = w34;
  /* #328: @34 = (@38*@26) */
  w34  = (w38*w26);
  /* #329: @40 = sin(@0) */
  w40 = sin( w0 );
  /* #330: @3 = (@3*@25) */
  w3 *= w25;
  /* #331: @40 = (@40*@3) */
  w40 *= w3;
  /* #332: @34 = (@34-@40) */
  w34 -= w40;
  /* #333: @34 = (@34+@47) */
  w34 += w47;
  /* #334: @38 = (@38*@48) */
  w38 *= w48;
  /* #335: @34 = (@34+@38) */
  w34 += w38;
  /* #336: @38 = sin(@0) */
  w38 = sin( w0 );
  /* #337: @53 = (@53*@56) */
  w53 *= w56;
  /* #338: @38 = (@38*@53) */
  w38 *= w53;
  /* #339: @34 = (@34-@38) */
  w34 -= w38;
  /* #340: @34 = (@34+@57) */
  w34 += w57;
  /* #341: @57 = cos(@0) */
  w57 = cos( w0 );
  /* #342: @64 = (@64*@66) */
  w64 *= w66;
  /* #343: @57 = (@57*@64) */
  w57 *= w64;
  /* #344: @34 = (@34-@57) */
  w34 -= w57;
  /* #345: @34 = (@34-@67) */
  w34 -= w67;
  /* #346: output[0][6] = @34 */
  if (res[0]) res[0][6] = w34;
  /* #347: @34 = (@0*@26) */
  w34  = (w0*w26);
  /* #348: @0 = (@0*@48) */
  w0 *= w48;
  /* #349: @34 = (@34+@0) */
  w34 += w0;
  /* #350: @0 = 1 */
  w0 = 1.;
  /* #351: @0 = (@0-@15) */
  w0 -= w15;
  /* #352: @0 = (@0*@20) */
  w0 *= w20;
  /* #353: @34 = (@34+@0) */
  w34 += w0;
  /* #354: @34 = (@34+@66) */
  w34 += w66;
  /* #355: output[0][7] = @34 */
  if (res[0]) res[0][7] = w34;
  /* #356: @26 = (@4*@26) */
  w26  = (w4*w26);
  /* #357: @23 = (@23+@26) */
  w23 += w26;
  /* #358: @4 = (@4*@48) */
  w4 *= w48;
  /* #359: @23 = (@23+@4) */
  w23 += w4;
  /* #360: output[0][8] = @23 */
  if (res[0]) res[0][8] = w23;
  return 0;
}

CASADI_SYMBOL_EXPORT int sim_car_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int sim_car_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int sim_car_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void sim_car_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int sim_car_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void sim_car_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void sim_car_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void sim_car_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int sim_car_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int sim_car_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real sim_car_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* sim_car_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* sim_car_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* sim_car_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* sim_car_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int sim_car_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 85;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
